/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.dto;

import java.math.BigDecimal;
import java.util.Date;

import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto.AbstractDto;

public class CovidusTFile extends AbstractDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_size
     *
     * @mbg.generated
     */
    private BigDecimal fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_type
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_tipo_id
     *
     * @mbg.generated
     */
    private Integer fileTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_code
     *
     * @mbg.generated
     */
    private String fileCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file_note
     *
     * @mbg.generated
     */
    private String fileNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidus_t_file.file
     *
     * @mbg.generated
     */
    private byte[] file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_id
     *
     * @return the value of covidus_t_file.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_id
     *
     * @param fileId the value for covidus_t_file.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_name
     *
     * @return the value of covidus_t_file.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_name
     *
     * @param fileName the value for covidus_t_file.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_size
     *
     * @return the value of covidus_t_file.file_size
     *
     * @mbg.generated
     */
    public BigDecimal getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_size
     *
     * @param fileSize the value for covidus_t_file.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(BigDecimal fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_type
     *
     * @return the value of covidus_t_file.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_type
     *
     * @param fileType the value for covidus_t_file.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_tipo_id
     *
     * @return the value of covidus_t_file.file_tipo_id
     *
     * @mbg.generated
     */
    public Integer getFileTipoId() {
        return fileTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_tipo_id
     *
     * @param fileTipoId the value for covidus_t_file.file_tipo_id
     *
     * @mbg.generated
     */
    public void setFileTipoId(Integer fileTipoId) {
        this.fileTipoId = fileTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_code
     *
     * @return the value of covidus_t_file.file_code
     *
     * @mbg.generated
     */
    public String getFileCode() {
        return fileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_code
     *
     * @param fileCode the value for covidus_t_file.file_code
     *
     * @mbg.generated
     */
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file_note
     *
     * @return the value of covidus_t_file.file_note
     *
     * @mbg.generated
     */
    public String getFileNote() {
        return fileNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file_note
     *
     * @param fileNote the value for covidus_t_file.file_note
     *
     * @mbg.generated
     */
    public void setFileNote(String fileNote) {
        this.fileNote = fileNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.utente_operazione
     *
     * @return the value of covidus_t_file.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.utente_operazione
     *
     * @param utenteOperazione the value for covidus_t_file.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.data_creazione
     *
     * @return the value of covidus_t_file.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.data_creazione
     *
     * @param dataCreazione the value for covidus_t_file.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.data_modifica
     *
     * @return the value of covidus_t_file.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.data_modifica
     *
     * @param dataModifica the value for covidus_t_file.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.data_cancellazione
     *
     * @return the value of covidus_t_file.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.data_cancellazione
     *
     * @param dataCancellazione the value for covidus_t_file.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidus_t_file.file
     *
     * @return the value of covidus_t_file.file
     *
     * @mbg.generated
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidus_t_file.file
     *
     * @param file the value for covidus_t_file.file
     *
     * @mbg.generated
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}