/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.dto;

import java.util.Date;

import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto.AbstractDto;

public class CovidrsaRStrutturaWelfare extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_welfare_id
	 * @mbg.generated
	 */
	private Integer strWelfareId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_codice_fiscale
	 * @mbg.generated
	 */
	private String rapLegCodiceFiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_cognome
	 * @mbg.generated
	 */
	private String rapLegCognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_nome
	 * @mbg.generated
	 */
	private String rapLegNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_comune_nascita
	 * @mbg.generated
	 */
	private String rapLegComuneNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_provincia_nascita
	 * @mbg.generated
	 */
	private String rapLegProvinciaNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_data_nascita
	 * @mbg.generated
	 */
	private Date rapLegDataNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_comune_residenza
	 * @mbg.generated
	 */
	private String rapLegComuneResidenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_provincia_residenza
	 * @mbg.generated
	 */
	private String rapLegProvinciaResidenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_residenza
	 * @mbg.generated
	 */
	private String rapLegIndirizzoResidenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_comune_domicilio
	 * @mbg.generated
	 */
	private String rapLegComuneDomicilio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_provincia_domicilio
	 * @mbg.generated
	 */
	private String rapLegProvinciaDomicilio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_domicilio
	 * @mbg.generated
	 */
	private String rapLegIndirizzoDomicilio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_cellulare
	 * @mbg.generated
	 */
	private String rapLegCellulare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_email
	 * @mbg.generated
	 */
	private String rapLegEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_ragione_sociale
	 * @mbg.generated
	 */
	private String entGestRagioneSociale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_comune
	 * @mbg.generated
	 */
	private String entGestComune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_indirizzo
	 * @mbg.generated
	 */
	private String entGestIndirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_provincia
	 * @mbg.generated
	 */
	private String entGestProvincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_nome
	 * @mbg.generated
	 */
	private String strResNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_tipologia
	 * @mbg.generated
	 */
	private String strResTipologia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_comune
	 * @mbg.generated
	 */
	private String strResComune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_indirizzo
	 * @mbg.generated
	 */
	private String strResIndirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_provincia
	 * @mbg.generated
	 */
	private String strResProvincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_cf_piva
	 * @mbg.generated
	 */
	private String entGestCfPiva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_verificato
	 * @mbg.generated
	 */
	private Boolean rapLegVerificato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.rap_leg_invariato
	 * @mbg.generated
	 */
	private Boolean rapLegInvariato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_verificato
	 * @mbg.generated
	 */
	private Boolean entGestVerificato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.ent_gest_invariato
	 * @mbg.generated
	 */
	private Boolean entGestInvariato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.str_res_invariato
	 * @mbg.generated
	 */
	private Boolean strResInvariato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_verificato
	 * @mbg.generated
	 */
	private Boolean titEffVerificato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_invariato
	 * @mbg.generated
	 */
	private Boolean titEffInvariato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_codice_fiscale
	 * @mbg.generated
	 */
	private String titEffCodiceFiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_cognome
	 * @mbg.generated
	 */
	private String titEffCognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_nome
	 * @mbg.generated
	 */
	private String titEffNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_data_nascita
	 * @mbg.generated
	 */
	private Date titEffDataNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_comune_nascita
	 * @mbg.generated
	 */
	private String titEffComuneNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_provincia_nascita
	 * @mbg.generated
	 */
	private String titEffProvinciaNascita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_indirizzo_residenza
	 * @mbg.generated
	 */
	private String titEffIndirizzoResidenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_comune_residenza
	 * @mbg.generated
	 */
	private String titEffComuneResidenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_welfare.tit_eff_provincia_residenza
	 * @mbg.generated
	 */
	private String titEffProvinciaResidenza;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_welfare_id
	 * @return  the value of covidrsa_r_struttura_welfare.str_welfare_id
	 * @mbg.generated
	 */
	public Integer getStrWelfareId() {
		return strWelfareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_welfare_id
	 * @param strWelfareId  the value for covidrsa_r_struttura_welfare.str_welfare_id
	 * @mbg.generated
	 */
	public void setStrWelfareId(Integer strWelfareId) {
		this.strWelfareId = strWelfareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.id_struttura
	 * @return  the value of covidrsa_r_struttura_welfare.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.id_struttura
	 * @param idStruttura  the value for covidrsa_r_struttura_welfare.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_codice_fiscale
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_codice_fiscale
	 * @mbg.generated
	 */
	public String getRapLegCodiceFiscale() {
		return rapLegCodiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_codice_fiscale
	 * @param rapLegCodiceFiscale  the value for covidrsa_r_struttura_welfare.rap_leg_codice_fiscale
	 * @mbg.generated
	 */
	public void setRapLegCodiceFiscale(String rapLegCodiceFiscale) {
		this.rapLegCodiceFiscale = rapLegCodiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_cognome
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_cognome
	 * @mbg.generated
	 */
	public String getRapLegCognome() {
		return rapLegCognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_cognome
	 * @param rapLegCognome  the value for covidrsa_r_struttura_welfare.rap_leg_cognome
	 * @mbg.generated
	 */
	public void setRapLegCognome(String rapLegCognome) {
		this.rapLegCognome = rapLegCognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_nome
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_nome
	 * @mbg.generated
	 */
	public String getRapLegNome() {
		return rapLegNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_nome
	 * @param rapLegNome  the value for covidrsa_r_struttura_welfare.rap_leg_nome
	 * @mbg.generated
	 */
	public void setRapLegNome(String rapLegNome) {
		this.rapLegNome = rapLegNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_comune_nascita
	 * @mbg.generated
	 */
	public String getRapLegComuneNascita() {
		return rapLegComuneNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_nascita
	 * @param rapLegComuneNascita  the value for covidrsa_r_struttura_welfare.rap_leg_comune_nascita
	 * @mbg.generated
	 */
	public void setRapLegComuneNascita(String rapLegComuneNascita) {
		this.rapLegComuneNascita = rapLegComuneNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_provincia_nascita
	 * @mbg.generated
	 */
	public String getRapLegProvinciaNascita() {
		return rapLegProvinciaNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_nascita
	 * @param rapLegProvinciaNascita  the value for covidrsa_r_struttura_welfare.rap_leg_provincia_nascita
	 * @mbg.generated
	 */
	public void setRapLegProvinciaNascita(String rapLegProvinciaNascita) {
		this.rapLegProvinciaNascita = rapLegProvinciaNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_data_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_data_nascita
	 * @mbg.generated
	 */
	public Date getRapLegDataNascita() {
		return rapLegDataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_data_nascita
	 * @param rapLegDataNascita  the value for covidrsa_r_struttura_welfare.rap_leg_data_nascita
	 * @mbg.generated
	 */
	public void setRapLegDataNascita(Date rapLegDataNascita) {
		this.rapLegDataNascita = rapLegDataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_comune_residenza
	 * @mbg.generated
	 */
	public String getRapLegComuneResidenza() {
		return rapLegComuneResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_residenza
	 * @param rapLegComuneResidenza  the value for covidrsa_r_struttura_welfare.rap_leg_comune_residenza
	 * @mbg.generated
	 */
	public void setRapLegComuneResidenza(String rapLegComuneResidenza) {
		this.rapLegComuneResidenza = rapLegComuneResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_provincia_residenza
	 * @mbg.generated
	 */
	public String getRapLegProvinciaResidenza() {
		return rapLegProvinciaResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_residenza
	 * @param rapLegProvinciaResidenza  the value for covidrsa_r_struttura_welfare.rap_leg_provincia_residenza
	 * @mbg.generated
	 */
	public void setRapLegProvinciaResidenza(String rapLegProvinciaResidenza) {
		this.rapLegProvinciaResidenza = rapLegProvinciaResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_indirizzo_residenza
	 * @mbg.generated
	 */
	public String getRapLegIndirizzoResidenza() {
		return rapLegIndirizzoResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_residenza
	 * @param rapLegIndirizzoResidenza  the value for covidrsa_r_struttura_welfare.rap_leg_indirizzo_residenza
	 * @mbg.generated
	 */
	public void setRapLegIndirizzoResidenza(String rapLegIndirizzoResidenza) {
		this.rapLegIndirizzoResidenza = rapLegIndirizzoResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_domicilio
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_comune_domicilio
	 * @mbg.generated
	 */
	public String getRapLegComuneDomicilio() {
		return rapLegComuneDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_comune_domicilio
	 * @param rapLegComuneDomicilio  the value for covidrsa_r_struttura_welfare.rap_leg_comune_domicilio
	 * @mbg.generated
	 */
	public void setRapLegComuneDomicilio(String rapLegComuneDomicilio) {
		this.rapLegComuneDomicilio = rapLegComuneDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_domicilio
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_provincia_domicilio
	 * @mbg.generated
	 */
	public String getRapLegProvinciaDomicilio() {
		return rapLegProvinciaDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_provincia_domicilio
	 * @param rapLegProvinciaDomicilio  the value for covidrsa_r_struttura_welfare.rap_leg_provincia_domicilio
	 * @mbg.generated
	 */
	public void setRapLegProvinciaDomicilio(String rapLegProvinciaDomicilio) {
		this.rapLegProvinciaDomicilio = rapLegProvinciaDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_domicilio
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_indirizzo_domicilio
	 * @mbg.generated
	 */
	public String getRapLegIndirizzoDomicilio() {
		return rapLegIndirizzoDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_indirizzo_domicilio
	 * @param rapLegIndirizzoDomicilio  the value for covidrsa_r_struttura_welfare.rap_leg_indirizzo_domicilio
	 * @mbg.generated
	 */
	public void setRapLegIndirizzoDomicilio(String rapLegIndirizzoDomicilio) {
		this.rapLegIndirizzoDomicilio = rapLegIndirizzoDomicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_cellulare
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_cellulare
	 * @mbg.generated
	 */
	public String getRapLegCellulare() {
		return rapLegCellulare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_cellulare
	 * @param rapLegCellulare  the value for covidrsa_r_struttura_welfare.rap_leg_cellulare
	 * @mbg.generated
	 */
	public void setRapLegCellulare(String rapLegCellulare) {
		this.rapLegCellulare = rapLegCellulare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_email
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_email
	 * @mbg.generated
	 */
	public String getRapLegEmail() {
		return rapLegEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_email
	 * @param rapLegEmail  the value for covidrsa_r_struttura_welfare.rap_leg_email
	 * @mbg.generated
	 */
	public void setRapLegEmail(String rapLegEmail) {
		this.rapLegEmail = rapLegEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_ragione_sociale
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_ragione_sociale
	 * @mbg.generated
	 */
	public String getEntGestRagioneSociale() {
		return entGestRagioneSociale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_ragione_sociale
	 * @param entGestRagioneSociale  the value for covidrsa_r_struttura_welfare.ent_gest_ragione_sociale
	 * @mbg.generated
	 */
	public void setEntGestRagioneSociale(String entGestRagioneSociale) {
		this.entGestRagioneSociale = entGestRagioneSociale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_comune
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_comune
	 * @mbg.generated
	 */
	public String getEntGestComune() {
		return entGestComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_comune
	 * @param entGestComune  the value for covidrsa_r_struttura_welfare.ent_gest_comune
	 * @mbg.generated
	 */
	public void setEntGestComune(String entGestComune) {
		this.entGestComune = entGestComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_indirizzo
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_indirizzo
	 * @mbg.generated
	 */
	public String getEntGestIndirizzo() {
		return entGestIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_indirizzo
	 * @param entGestIndirizzo  the value for covidrsa_r_struttura_welfare.ent_gest_indirizzo
	 * @mbg.generated
	 */
	public void setEntGestIndirizzo(String entGestIndirizzo) {
		this.entGestIndirizzo = entGestIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_provincia
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_provincia
	 * @mbg.generated
	 */
	public String getEntGestProvincia() {
		return entGestProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_provincia
	 * @param entGestProvincia  the value for covidrsa_r_struttura_welfare.ent_gest_provincia
	 * @mbg.generated
	 */
	public void setEntGestProvincia(String entGestProvincia) {
		this.entGestProvincia = entGestProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_nome
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_nome
	 * @mbg.generated
	 */
	public String getStrResNome() {
		return strResNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_nome
	 * @param strResNome  the value for covidrsa_r_struttura_welfare.str_res_nome
	 * @mbg.generated
	 */
	public void setStrResNome(String strResNome) {
		this.strResNome = strResNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_tipologia
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_tipologia
	 * @mbg.generated
	 */
	public String getStrResTipologia() {
		return strResTipologia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_tipologia
	 * @param strResTipologia  the value for covidrsa_r_struttura_welfare.str_res_tipologia
	 * @mbg.generated
	 */
	public void setStrResTipologia(String strResTipologia) {
		this.strResTipologia = strResTipologia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_comune
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_comune
	 * @mbg.generated
	 */
	public String getStrResComune() {
		return strResComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_comune
	 * @param strResComune  the value for covidrsa_r_struttura_welfare.str_res_comune
	 * @mbg.generated
	 */
	public void setStrResComune(String strResComune) {
		this.strResComune = strResComune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_indirizzo
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_indirizzo
	 * @mbg.generated
	 */
	public String getStrResIndirizzo() {
		return strResIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_indirizzo
	 * @param strResIndirizzo  the value for covidrsa_r_struttura_welfare.str_res_indirizzo
	 * @mbg.generated
	 */
	public void setStrResIndirizzo(String strResIndirizzo) {
		this.strResIndirizzo = strResIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_provincia
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_provincia
	 * @mbg.generated
	 */
	public String getStrResProvincia() {
		return strResProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_provincia
	 * @param strResProvincia  the value for covidrsa_r_struttura_welfare.str_res_provincia
	 * @mbg.generated
	 */
	public void setStrResProvincia(String strResProvincia) {
		this.strResProvincia = strResProvincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.validita_inizio
	 * @return  the value of covidrsa_r_struttura_welfare.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.validita_inizio
	 * @param validitaInizio  the value for covidrsa_r_struttura_welfare.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.validita_fine
	 * @return  the value of covidrsa_r_struttura_welfare.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.validita_fine
	 * @param validitaFine  the value for covidrsa_r_struttura_welfare.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.utente_operazione
	 * @return  the value of covidrsa_r_struttura_welfare.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_r_struttura_welfare.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.data_creazione
	 * @return  the value of covidrsa_r_struttura_welfare.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.data_creazione
	 * @param dataCreazione  the value for covidrsa_r_struttura_welfare.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.data_modifica
	 * @return  the value of covidrsa_r_struttura_welfare.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.data_modifica
	 * @param dataModifica  the value for covidrsa_r_struttura_welfare.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.data_cancellazione
	 * @return  the value of covidrsa_r_struttura_welfare.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_r_struttura_welfare.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_cf_piva
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_cf_piva
	 * @mbg.generated
	 */
	public String getEntGestCfPiva() {
		return entGestCfPiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_cf_piva
	 * @param entGestCfPiva  the value for covidrsa_r_struttura_welfare.ent_gest_cf_piva
	 * @mbg.generated
	 */
	public void setEntGestCfPiva(String entGestCfPiva) {
		this.entGestCfPiva = entGestCfPiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_verificato
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_verificato
	 * @mbg.generated
	 */
	public Boolean getRapLegVerificato() {
		return rapLegVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_verificato
	 * @param rapLegVerificato  the value for covidrsa_r_struttura_welfare.rap_leg_verificato
	 * @mbg.generated
	 */
	public void setRapLegVerificato(Boolean rapLegVerificato) {
		this.rapLegVerificato = rapLegVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.rap_leg_invariato
	 * @return  the value of covidrsa_r_struttura_welfare.rap_leg_invariato
	 * @mbg.generated
	 */
	public Boolean getRapLegInvariato() {
		return rapLegInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.rap_leg_invariato
	 * @param rapLegInvariato  the value for covidrsa_r_struttura_welfare.rap_leg_invariato
	 * @mbg.generated
	 */
	public void setRapLegInvariato(Boolean rapLegInvariato) {
		this.rapLegInvariato = rapLegInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_verificato
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_verificato
	 * @mbg.generated
	 */
	public Boolean getEntGestVerificato() {
		return entGestVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_verificato
	 * @param entGestVerificato  the value for covidrsa_r_struttura_welfare.ent_gest_verificato
	 * @mbg.generated
	 */
	public void setEntGestVerificato(Boolean entGestVerificato) {
		this.entGestVerificato = entGestVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.ent_gest_invariato
	 * @return  the value of covidrsa_r_struttura_welfare.ent_gest_invariato
	 * @mbg.generated
	 */
	public Boolean getEntGestInvariato() {
		return entGestInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.ent_gest_invariato
	 * @param entGestInvariato  the value for covidrsa_r_struttura_welfare.ent_gest_invariato
	 * @mbg.generated
	 */
	public void setEntGestInvariato(Boolean entGestInvariato) {
		this.entGestInvariato = entGestInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.str_res_invariato
	 * @return  the value of covidrsa_r_struttura_welfare.str_res_invariato
	 * @mbg.generated
	 */
	public Boolean getStrResInvariato() {
		return strResInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.str_res_invariato
	 * @param strResInvariato  the value for covidrsa_r_struttura_welfare.str_res_invariato
	 * @mbg.generated
	 */
	public void setStrResInvariato(Boolean strResInvariato) {
		this.strResInvariato = strResInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_verificato
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_verificato
	 * @mbg.generated
	 */
	public Boolean getTitEffVerificato() {
		return titEffVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_verificato
	 * @param titEffVerificato  the value for covidrsa_r_struttura_welfare.tit_eff_verificato
	 * @mbg.generated
	 */
	public void setTitEffVerificato(Boolean titEffVerificato) {
		this.titEffVerificato = titEffVerificato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_invariato
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_invariato
	 * @mbg.generated
	 */
	public Boolean getTitEffInvariato() {
		return titEffInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_invariato
	 * @param titEffInvariato  the value for covidrsa_r_struttura_welfare.tit_eff_invariato
	 * @mbg.generated
	 */
	public void setTitEffInvariato(Boolean titEffInvariato) {
		this.titEffInvariato = titEffInvariato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_codice_fiscale
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_codice_fiscale
	 * @mbg.generated
	 */
	public String getTitEffCodiceFiscale() {
		return titEffCodiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_codice_fiscale
	 * @param titEffCodiceFiscale  the value for covidrsa_r_struttura_welfare.tit_eff_codice_fiscale
	 * @mbg.generated
	 */
	public void setTitEffCodiceFiscale(String titEffCodiceFiscale) {
		this.titEffCodiceFiscale = titEffCodiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_cognome
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_cognome
	 * @mbg.generated
	 */
	public String getTitEffCognome() {
		return titEffCognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_cognome
	 * @param titEffCognome  the value for covidrsa_r_struttura_welfare.tit_eff_cognome
	 * @mbg.generated
	 */
	public void setTitEffCognome(String titEffCognome) {
		this.titEffCognome = titEffCognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_nome
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_nome
	 * @mbg.generated
	 */
	public String getTitEffNome() {
		return titEffNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_nome
	 * @param titEffNome  the value for covidrsa_r_struttura_welfare.tit_eff_nome
	 * @mbg.generated
	 */
	public void setTitEffNome(String titEffNome) {
		this.titEffNome = titEffNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_data_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_data_nascita
	 * @mbg.generated
	 */
	public Date getTitEffDataNascita() {
		return titEffDataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_data_nascita
	 * @param titEffDataNascita  the value for covidrsa_r_struttura_welfare.tit_eff_data_nascita
	 * @mbg.generated
	 */
	public void setTitEffDataNascita(Date titEffDataNascita) {
		this.titEffDataNascita = titEffDataNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_comune_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_comune_nascita
	 * @mbg.generated
	 */
	public String getTitEffComuneNascita() {
		return titEffComuneNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_comune_nascita
	 * @param titEffComuneNascita  the value for covidrsa_r_struttura_welfare.tit_eff_comune_nascita
	 * @mbg.generated
	 */
	public void setTitEffComuneNascita(String titEffComuneNascita) {
		this.titEffComuneNascita = titEffComuneNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_provincia_nascita
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_provincia_nascita
	 * @mbg.generated
	 */
	public String getTitEffProvinciaNascita() {
		return titEffProvinciaNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_provincia_nascita
	 * @param titEffProvinciaNascita  the value for covidrsa_r_struttura_welfare.tit_eff_provincia_nascita
	 * @mbg.generated
	 */
	public void setTitEffProvinciaNascita(String titEffProvinciaNascita) {
		this.titEffProvinciaNascita = titEffProvinciaNascita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_indirizzo_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_indirizzo_residenza
	 * @mbg.generated
	 */
	public String getTitEffIndirizzoResidenza() {
		return titEffIndirizzoResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_indirizzo_residenza
	 * @param titEffIndirizzoResidenza  the value for covidrsa_r_struttura_welfare.tit_eff_indirizzo_residenza
	 * @mbg.generated
	 */
	public void setTitEffIndirizzoResidenza(String titEffIndirizzoResidenza) {
		this.titEffIndirizzoResidenza = titEffIndirizzoResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_comune_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_comune_residenza
	 * @mbg.generated
	 */
	public String getTitEffComuneResidenza() {
		return titEffComuneResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_comune_residenza
	 * @param titEffComuneResidenza  the value for covidrsa_r_struttura_welfare.tit_eff_comune_residenza
	 * @mbg.generated
	 */
	public void setTitEffComuneResidenza(String titEffComuneResidenza) {
		this.titEffComuneResidenza = titEffComuneResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_welfare.tit_eff_provincia_residenza
	 * @return  the value of covidrsa_r_struttura_welfare.tit_eff_provincia_residenza
	 * @mbg.generated
	 */
	public String getTitEffProvinciaResidenza() {
		return titEffProvinciaResidenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_welfare.tit_eff_provincia_residenza
	 * @param titEffProvinciaResidenza  the value for covidrsa_r_struttura_welfare.tit_eff_provincia_residenza
	 * @mbg.generated
	 */
	public void setTitEffProvinciaResidenza(String titEffProvinciaResidenza) {
		this.titEffProvinciaResidenza = titEffProvinciaResidenza;
	}
}