/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

public class Asr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asr.id_asr
	 * @mbg.generated
	 */
	private Long idAsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asr.descrizione
	 * @mbg.generated
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asr.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asr.id_asr
	 * @return  the value of asr.id_asr
	 * @mbg.generated
	 */
	public Long getIdAsr() {
		return idAsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asr.id_asr
	 * @param idAsr  the value for asr.id_asr
	 * @mbg.generated
	 */
	public void setIdAsr(Long idAsr) {
		this.idAsr = idAsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asr.descrizione
	 * @return  the value of asr.descrizione
	 * @mbg.generated
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asr.descrizione
	 * @param descrizione  the value for asr.descrizione
	 * @mbg.generated
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asr.id_ente
	 * @return  the value of asr.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asr.id_ente
	 * @param idEnte  the value for asr.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}
}