/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaRStrutturaConto extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.str_conto_id
	 * @mbg.generated
	 */
	private Integer strContoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.sti_id
	 * @mbg.generated
	 */
	private Integer stiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.str_conto_iban
	 * @mbg.generated
	 */
	private String strContoIban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.str_conto_istituto
	 * @mbg.generated
	 */
	private String strContoIstituto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.str_conto_desc
	 * @mbg.generated
	 */
	private String strContoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.flg_default
	 * @mbg.generated
	 */
	private Boolean flgDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_struttura_conto.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.str_conto_id
	 * @return  the value of covidrsa_r_struttura_conto.str_conto_id
	 * @mbg.generated
	 */
	public Integer getStrContoId() {
		return strContoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.str_conto_id
	 * @param strContoId  the value for covidrsa_r_struttura_conto.str_conto_id
	 * @mbg.generated
	 */
	public void setStrContoId(Integer strContoId) {
		this.strContoId = strContoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.sti_id
	 * @return  the value of covidrsa_r_struttura_conto.sti_id
	 * @mbg.generated
	 */
	public Integer getStiId() {
		return stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.sti_id
	 * @param stiId  the value for covidrsa_r_struttura_conto.sti_id
	 * @mbg.generated
	 */
	public void setStiId(Integer stiId) {
		this.stiId = stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.str_conto_iban
	 * @return  the value of covidrsa_r_struttura_conto.str_conto_iban
	 * @mbg.generated
	 */
	public String getStrContoIban() {
		return strContoIban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.str_conto_iban
	 * @param strContoIban  the value for covidrsa_r_struttura_conto.str_conto_iban
	 * @mbg.generated
	 */
	public void setStrContoIban(String strContoIban) {
		this.strContoIban = strContoIban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.str_conto_istituto
	 * @return  the value of covidrsa_r_struttura_conto.str_conto_istituto
	 * @mbg.generated
	 */
	public String getStrContoIstituto() {
		return strContoIstituto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.str_conto_istituto
	 * @param strContoIstituto  the value for covidrsa_r_struttura_conto.str_conto_istituto
	 * @mbg.generated
	 */
	public void setStrContoIstituto(String strContoIstituto) {
		this.strContoIstituto = strContoIstituto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.str_conto_desc
	 * @return  the value of covidrsa_r_struttura_conto.str_conto_desc
	 * @mbg.generated
	 */
	public String getStrContoDesc() {
		return strContoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.str_conto_desc
	 * @param strContoDesc  the value for covidrsa_r_struttura_conto.str_conto_desc
	 * @mbg.generated
	 */
	public void setStrContoDesc(String strContoDesc) {
		this.strContoDesc = strContoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.flg_default
	 * @return  the value of covidrsa_r_struttura_conto.flg_default
	 * @mbg.generated
	 */
	public Boolean getFlgDefault() {
		return flgDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.flg_default
	 * @param flgDefault  the value for covidrsa_r_struttura_conto.flg_default
	 * @mbg.generated
	 */
	public void setFlgDefault(Boolean flgDefault) {
		this.flgDefault = flgDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.validita_inizio
	 * @return  the value of covidrsa_r_struttura_conto.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.validita_inizio
	 * @param validitaInizio  the value for covidrsa_r_struttura_conto.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.validita_fine
	 * @return  the value of covidrsa_r_struttura_conto.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.validita_fine
	 * @param validitaFine  the value for covidrsa_r_struttura_conto.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.data_creazione
	 * @return  the value of covidrsa_r_struttura_conto.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.data_creazione
	 * @param dataCreazione  the value for covidrsa_r_struttura_conto.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.data_modifica
	 * @return  the value of covidrsa_r_struttura_conto.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.data_modifica
	 * @param dataModifica  the value for covidrsa_r_struttura_conto.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.data_cancellazione
	 * @return  the value of covidrsa_r_struttura_conto.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_r_struttura_conto.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_struttura_conto.utente_operazione
	 * @return  the value of covidrsa_r_struttura_conto.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_struttura_conto.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_r_struttura_conto.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}