/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.math.BigDecimal;
import java.util.Date;

public class CovidrsaTRendicontazione extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.rendicontazione_id
     *
     * @mbg.generated
     */
    private Integer rendicontazioneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.id_struttura
     *
     * @mbg.generated
     */
    private String idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.id_soggetto
     *
     * @mbg.generated
     */
    private Integer idSoggetto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.data_rendicontazione
     *
     * @mbg.generated
     */
    private Date dataRendicontazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.importo_retta
     *
     * @mbg.generated
     */
    private BigDecimal importoRetta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.str_conto_id
     *
     * @mbg.generated
     */
    private Integer strContoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.stato_rend_id
     *
     * @mbg.generated
     */
    private Integer statoRendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.welfare_fascia_id
     *
     * @mbg.generated
     */
    private Integer welfareFasciaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.flg_primo_ingresso
     *
     * @mbg.generated
     */
    private Boolean flgPrimoIngresso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.movimento_ospite_id_uscita
     *
     * @mbg.generated
     */
    private Integer movimentoOspiteIdUscita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.buonores_id
     *
     * @mbg.generated
     */
    private Integer buonoresId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.invio_pbandi_id
     *
     * @mbg.generated
     */
    private Integer invioPbandiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.rendicontazione_cod
     *
     * @mbg.generated
     */
    private String rendicontazioneCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.rendicontazione_cod_ext
     *
     * @mbg.generated
     */
    private String rendicontazioneCodExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_rendicontazione.note_operazione
     *
     * @mbg.generated
     */
    private String noteOperazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.rendicontazione_id
     *
     * @return the value of covidrsa_t_rendicontazione.rendicontazione_id
     *
     * @mbg.generated
     */
    public Integer getRendicontazioneId() {
        return rendicontazioneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.rendicontazione_id
     *
     * @param rendicontazioneId the value for covidrsa_t_rendicontazione.rendicontazione_id
     *
     * @mbg.generated
     */
    public void setRendicontazioneId(Integer rendicontazioneId) {
        this.rendicontazioneId = rendicontazioneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.id_struttura
     *
     * @return the value of covidrsa_t_rendicontazione.id_struttura
     *
     * @mbg.generated
     */
    public String getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.id_struttura
     *
     * @param idStruttura the value for covidrsa_t_rendicontazione.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(String idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.id_soggetto
     *
     * @return the value of covidrsa_t_rendicontazione.id_soggetto
     *
     * @mbg.generated
     */
    public Integer getIdSoggetto() {
        return idSoggetto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.id_soggetto
     *
     * @param idSoggetto the value for covidrsa_t_rendicontazione.id_soggetto
     *
     * @mbg.generated
     */
    public void setIdSoggetto(Integer idSoggetto) {
        this.idSoggetto = idSoggetto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.data_rendicontazione
     *
     * @return the value of covidrsa_t_rendicontazione.data_rendicontazione
     *
     * @mbg.generated
     */
    public Date getDataRendicontazione() {
        return dataRendicontazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.data_rendicontazione
     *
     * @param dataRendicontazione the value for covidrsa_t_rendicontazione.data_rendicontazione
     *
     * @mbg.generated
     */
    public void setDataRendicontazione(Date dataRendicontazione) {
        this.dataRendicontazione = dataRendicontazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.importo_retta
     *
     * @return the value of covidrsa_t_rendicontazione.importo_retta
     *
     * @mbg.generated
     */
    public BigDecimal getImportoRetta() {
        return importoRetta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.importo_retta
     *
     * @param importoRetta the value for covidrsa_t_rendicontazione.importo_retta
     *
     * @mbg.generated
     */
    public void setImportoRetta(BigDecimal importoRetta) {
        this.importoRetta = importoRetta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.str_conto_id
     *
     * @return the value of covidrsa_t_rendicontazione.str_conto_id
     *
     * @mbg.generated
     */
    public Integer getStrContoId() {
        return strContoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.str_conto_id
     *
     * @param strContoId the value for covidrsa_t_rendicontazione.str_conto_id
     *
     * @mbg.generated
     */
    public void setStrContoId(Integer strContoId) {
        this.strContoId = strContoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.stato_rend_id
     *
     * @return the value of covidrsa_t_rendicontazione.stato_rend_id
     *
     * @mbg.generated
     */
    public Integer getStatoRendId() {
        return statoRendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.stato_rend_id
     *
     * @param statoRendId the value for covidrsa_t_rendicontazione.stato_rend_id
     *
     * @mbg.generated
     */
    public void setStatoRendId(Integer statoRendId) {
        this.statoRendId = statoRendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.validita_inizio
     *
     * @return the value of covidrsa_t_rendicontazione.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_t_rendicontazione.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.validita_fine
     *
     * @return the value of covidrsa_t_rendicontazione.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.validita_fine
     *
     * @param validitaFine the value for covidrsa_t_rendicontazione.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.data_creazione
     *
     * @return the value of covidrsa_t_rendicontazione.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.data_creazione
     *
     * @param dataCreazione the value for covidrsa_t_rendicontazione.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.data_modifica
     *
     * @return the value of covidrsa_t_rendicontazione.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.data_modifica
     *
     * @param dataModifica the value for covidrsa_t_rendicontazione.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.data_cancellazione
     *
     * @return the value of covidrsa_t_rendicontazione.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_t_rendicontazione.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.utente_operazione
     *
     * @return the value of covidrsa_t_rendicontazione.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_t_rendicontazione.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.welfare_fascia_id
     *
     * @return the value of covidrsa_t_rendicontazione.welfare_fascia_id
     *
     * @mbg.generated
     */
    public Integer getWelfareFasciaId() {
        return welfareFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.welfare_fascia_id
     *
     * @param welfareFasciaId the value for covidrsa_t_rendicontazione.welfare_fascia_id
     *
     * @mbg.generated
     */
    public void setWelfareFasciaId(Integer welfareFasciaId) {
        this.welfareFasciaId = welfareFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.flg_primo_ingresso
     *
     * @return the value of covidrsa_t_rendicontazione.flg_primo_ingresso
     *
     * @mbg.generated
     */
    public Boolean getFlgPrimoIngresso() {
        return flgPrimoIngresso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.flg_primo_ingresso
     *
     * @param flgPrimoIngresso the value for covidrsa_t_rendicontazione.flg_primo_ingresso
     *
     * @mbg.generated
     */
    public void setFlgPrimoIngresso(Boolean flgPrimoIngresso) {
        this.flgPrimoIngresso = flgPrimoIngresso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.movimento_ospite_id_uscita
     *
     * @return the value of covidrsa_t_rendicontazione.movimento_ospite_id_uscita
     *
     * @mbg.generated
     */
    public Integer getMovimentoOspiteIdUscita() {
        return movimentoOspiteIdUscita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.movimento_ospite_id_uscita
     *
     * @param movimentoOspiteIdUscita the value for covidrsa_t_rendicontazione.movimento_ospite_id_uscita
     *
     * @mbg.generated
     */
    public void setMovimentoOspiteIdUscita(Integer movimentoOspiteIdUscita) {
        this.movimentoOspiteIdUscita = movimentoOspiteIdUscita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.note
     *
     * @return the value of covidrsa_t_rendicontazione.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.note
     *
     * @param note the value for covidrsa_t_rendicontazione.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.buonores_id
     *
     * @return the value of covidrsa_t_rendicontazione.buonores_id
     *
     * @mbg.generated
     */
    public Integer getBuonoresId() {
        return buonoresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.buonores_id
     *
     * @param buonoresId the value for covidrsa_t_rendicontazione.buonores_id
     *
     * @mbg.generated
     */
    public void setBuonoresId(Integer buonoresId) {
        this.buonoresId = buonoresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.invio_pbandi_id
     *
     * @return the value of covidrsa_t_rendicontazione.invio_pbandi_id
     *
     * @mbg.generated
     */
    public Integer getInvioPbandiId() {
        return invioPbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.invio_pbandi_id
     *
     * @param invioPbandiId the value for covidrsa_t_rendicontazione.invio_pbandi_id
     *
     * @mbg.generated
     */
    public void setInvioPbandiId(Integer invioPbandiId) {
        this.invioPbandiId = invioPbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.rendicontazione_cod
     *
     * @return the value of covidrsa_t_rendicontazione.rendicontazione_cod
     *
     * @mbg.generated
     */
    public String getRendicontazioneCod() {
        return rendicontazioneCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.rendicontazione_cod
     *
     * @param rendicontazioneCod the value for covidrsa_t_rendicontazione.rendicontazione_cod
     *
     * @mbg.generated
     */
    public void setRendicontazioneCod(String rendicontazioneCod) {
        this.rendicontazioneCod = rendicontazioneCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.rendicontazione_cod_ext
     *
     * @return the value of covidrsa_t_rendicontazione.rendicontazione_cod_ext
     *
     * @mbg.generated
     */
    public String getRendicontazioneCodExt() {
        return rendicontazioneCodExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.rendicontazione_cod_ext
     *
     * @param rendicontazioneCodExt the value for covidrsa_t_rendicontazione.rendicontazione_cod_ext
     *
     * @mbg.generated
     */
    public void setRendicontazioneCodExt(String rendicontazioneCodExt) {
        this.rendicontazioneCodExt = rendicontazioneCodExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_rendicontazione.note_operazione
     *
     * @return the value of covidrsa_t_rendicontazione.note_operazione
     *
     * @mbg.generated
     */
    public String getNoteOperazione() {
        return noteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_rendicontazione.note_operazione
     *
     * @param noteOperazione the value for covidrsa_t_rendicontazione.note_operazione
     *
     * @mbg.generated
     */
    public void setNoteOperazione(String noteOperazione) {
        this.noteOperazione = noteOperazione;
    }
}