/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaTIntegrazionePbandi extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_id
	 * @mbg.generated
	 */
	private Integer integrazionePbandiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.invio_pbandi_id
	 * @mbg.generated
	 */
	private Integer invioPbandiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_cod
	 * @mbg.generated
	 */
	private String integrazionePbandiCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_richiesta
	 * @mbg.generated
	 */
	private Date dataRichiesta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.note_richiesta
	 * @mbg.generated
	 */
	private String noteRichiesta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_risposta
	 * @mbg.generated
	 */
	private Date dataRisposta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_integrazione_pbandi.data_scadenza
	 * @mbg.generated
	 */
	private Date dataScadenza;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_id
	 * @return  the value of covidrsa_t_integrazione_pbandi.integrazione_pbandi_id
	 * @mbg.generated
	 */
	public Integer getIntegrazionePbandiId() {
		return integrazionePbandiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_id
	 * @param integrazionePbandiId  the value for covidrsa_t_integrazione_pbandi.integrazione_pbandi_id
	 * @mbg.generated
	 */
	public void setIntegrazionePbandiId(Integer integrazionePbandiId) {
		this.integrazionePbandiId = integrazionePbandiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.invio_pbandi_id
	 * @return  the value of covidrsa_t_integrazione_pbandi.invio_pbandi_id
	 * @mbg.generated
	 */
	public Integer getInvioPbandiId() {
		return invioPbandiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.invio_pbandi_id
	 * @param invioPbandiId  the value for covidrsa_t_integrazione_pbandi.invio_pbandi_id
	 * @mbg.generated
	 */
	public void setInvioPbandiId(Integer invioPbandiId) {
		this.invioPbandiId = invioPbandiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_cod
	 * @return  the value of covidrsa_t_integrazione_pbandi.integrazione_pbandi_cod
	 * @mbg.generated
	 */
	public String getIntegrazionePbandiCod() {
		return integrazionePbandiCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.integrazione_pbandi_cod
	 * @param integrazionePbandiCod  the value for covidrsa_t_integrazione_pbandi.integrazione_pbandi_cod
	 * @mbg.generated
	 */
	public void setIntegrazionePbandiCod(String integrazionePbandiCod) {
		this.integrazionePbandiCod = integrazionePbandiCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_richiesta
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_richiesta
	 * @mbg.generated
	 */
	public Date getDataRichiesta() {
		return dataRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_richiesta
	 * @param dataRichiesta  the value for covidrsa_t_integrazione_pbandi.data_richiesta
	 * @mbg.generated
	 */
	public void setDataRichiesta(Date dataRichiesta) {
		this.dataRichiesta = dataRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.note_richiesta
	 * @return  the value of covidrsa_t_integrazione_pbandi.note_richiesta
	 * @mbg.generated
	 */
	public String getNoteRichiesta() {
		return noteRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.note_richiesta
	 * @param noteRichiesta  the value for covidrsa_t_integrazione_pbandi.note_richiesta
	 * @mbg.generated
	 */
	public void setNoteRichiesta(String noteRichiesta) {
		this.noteRichiesta = noteRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_risposta
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_risposta
	 * @mbg.generated
	 */
	public Date getDataRisposta() {
		return dataRisposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_risposta
	 * @param dataRisposta  the value for covidrsa_t_integrazione_pbandi.data_risposta
	 * @mbg.generated
	 */
	public void setDataRisposta(Date dataRisposta) {
		this.dataRisposta = dataRisposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.validita_inizio
	 * @return  the value of covidrsa_t_integrazione_pbandi.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.validita_inizio
	 * @param validitaInizio  the value for covidrsa_t_integrazione_pbandi.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.validita_fine
	 * @return  the value of covidrsa_t_integrazione_pbandi.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.validita_fine
	 * @param validitaFine  the value for covidrsa_t_integrazione_pbandi.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.utente_operazione
	 * @return  the value of covidrsa_t_integrazione_pbandi.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_t_integrazione_pbandi.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_creazione
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_creazione
	 * @param dataCreazione  the value for covidrsa_t_integrazione_pbandi.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_modifica
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_modifica
	 * @param dataModifica  the value for covidrsa_t_integrazione_pbandi.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_cancellazione
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_t_integrazione_pbandi.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_integrazione_pbandi.data_scadenza
	 * @return  the value of covidrsa_t_integrazione_pbandi.data_scadenza
	 * @mbg.generated
	 */
	public Date getDataScadenza() {
		return dataScadenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_integrazione_pbandi.data_scadenza
	 * @param dataScadenza  the value for covidrsa_t_integrazione_pbandi.data_scadenza
	 * @mbg.generated
	 */
	public void setDataScadenza(Date dataScadenza) {
		this.dataScadenza = dataScadenza;
	}
}