/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidhrCParametro{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.param_id
     *
     * @mbg.generated
     */
    private Integer paramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.param_key
     *
     * @mbg.generated
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.param_value
     *
     * @mbg.generated
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidhr_c_parametro.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.param_id
     *
     * @return the value of covidhr_c_parametro.param_id
     *
     * @mbg.generated
     */
    public Integer getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.param_id
     *
     * @param paramId the value for covidhr_c_parametro.param_id
     *
     * @mbg.generated
     */
    public void setParamId(Integer paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.param_key
     *
     * @return the value of covidhr_c_parametro.param_key
     *
     * @mbg.generated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.param_key
     *
     * @param paramKey the value for covidhr_c_parametro.param_key
     *
     * @mbg.generated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.param_value
     *
     * @return the value of covidhr_c_parametro.param_value
     *
     * @mbg.generated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.param_value
     *
     * @param paramValue the value for covidhr_c_parametro.param_value
     *
     * @mbg.generated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.validita_inizio
     *
     * @return the value of covidhr_c_parametro.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.validita_inizio
     *
     * @param validitaInizio the value for covidhr_c_parametro.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.validita_fine
     *
     * @return the value of covidhr_c_parametro.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.validita_fine
     *
     * @param validitaFine the value for covidhr_c_parametro.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.data_creazione
     *
     * @return the value of covidhr_c_parametro.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.data_creazione
     *
     * @param dataCreazione the value for covidhr_c_parametro.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.data_modifica
     *
     * @return the value of covidhr_c_parametro.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.data_modifica
     *
     * @param dataModifica the value for covidhr_c_parametro.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.data_cancellazione
     *
     * @return the value of covidhr_c_parametro.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.data_cancellazione
     *
     * @param dataCancellazione the value for covidhr_c_parametro.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidhr_c_parametro.utente_operazione
     *
     * @return the value of covidhr_c_parametro.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidhr_c_parametro.utente_operazione
     *
     * @param utenteOperazione the value for covidhr_c_parametro.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }
}