/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsarIntegrazionePbandiFile extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_file_id
     *
     * @mbg.generated
     */
    private Integer integrazionePbandiFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_id
     *
     * @mbg.generated
     */
    private Integer integrazionePbandiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.file_tipo_id
     *
     * @mbg.generated
     */
    private Integer fileTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_integrazione_pbandi_file.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_file_id
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_file_id
     *
     * @mbg.generated
     */
    public Integer getIntegrazionePbandiFileId() {
        return integrazionePbandiFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_file_id
     *
     * @param integrazionePbandiFileId the value for covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_file_id
     *
     * @mbg.generated
     */
    public void setIntegrazionePbandiFileId(Integer integrazionePbandiFileId) {
        this.integrazionePbandiFileId = integrazionePbandiFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_id
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_id
     *
     * @mbg.generated
     */
    public Integer getIntegrazionePbandiId() {
        return integrazionePbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_id
     *
     * @param integrazionePbandiId the value for covidrsa_r_integrazione_pbandi_file.integrazione_pbandi_id
     *
     * @mbg.generated
     */
    public void setIntegrazionePbandiId(Integer integrazionePbandiId) {
        this.integrazionePbandiId = integrazionePbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.file_id
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.file_id
     *
     * @param fileId the value for covidrsa_r_integrazione_pbandi_file.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.file_tipo_id
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.file_tipo_id
     *
     * @mbg.generated
     */
    public Integer getFileTipoId() {
        return fileTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.file_tipo_id
     *
     * @param fileTipoId the value for covidrsa_r_integrazione_pbandi_file.file_tipo_id
     *
     * @mbg.generated
     */
    public void setFileTipoId(Integer fileTipoId) {
        this.fileTipoId = fileTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.validita_inizio
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_r_integrazione_pbandi_file.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.validita_fine
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.validita_fine
     *
     * @param validitaFine the value for covidrsa_r_integrazione_pbandi_file.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.utente_operazione
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_r_integrazione_pbandi_file.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.data_creazione
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.data_creazione
     *
     * @param dataCreazione the value for covidrsa_r_integrazione_pbandi_file.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.data_modifica
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.data_modifica
     *
     * @param dataModifica the value for covidrsa_r_integrazione_pbandi_file.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_integrazione_pbandi_file.data_cancellazione
     *
     * @return the value of covidrsa_r_integrazione_pbandi_file.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_integrazione_pbandi_file.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_r_integrazione_pbandi_file.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}