/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaTMovimentoOspite extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.movimento_ospite_id
	 * @mbg.generated
	 */
	private Integer movimentoOspiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.id_soggetto
	 * @mbg.generated
	 */
	private Integer idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.data_movimento
	 * @mbg.generated
	 */
	private Date dataMovimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	private Integer tipoMovOspiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.id_struttura_od
	 * @mbg.generated
	 */
	private String idStrutturaOd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.flg_preserva_posto
	 * @mbg.generated
	 */
	private Boolean flgPreservaPosto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.note
	 * @mbg.generated
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_movimento_ospite.condizioni_ospite_id
	 * @mbg.generated
	 */
	private Integer condizioniOspiteId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.movimento_ospite_id
	 * @return  the value of covidrsa_t_movimento_ospite.movimento_ospite_id
	 * @mbg.generated
	 */
	public Integer getMovimentoOspiteId() {
		return movimentoOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.movimento_ospite_id
	 * @param movimentoOspiteId  the value for covidrsa_t_movimento_ospite.movimento_ospite_id
	 * @mbg.generated
	 */
	public void setMovimentoOspiteId(Integer movimentoOspiteId) {
		this.movimentoOspiteId = movimentoOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.id_struttura
	 * @return  the value of covidrsa_t_movimento_ospite.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.id_struttura
	 * @param idStruttura  the value for covidrsa_t_movimento_ospite.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.id_soggetto
	 * @return  the value of covidrsa_t_movimento_ospite.id_soggetto
	 * @mbg.generated
	 */
	public Integer getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.id_soggetto
	 * @param idSoggetto  the value for covidrsa_t_movimento_ospite.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Integer idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.data_movimento
	 * @return  the value of covidrsa_t_movimento_ospite.data_movimento
	 * @mbg.generated
	 */
	public Date getDataMovimento() {
		return dataMovimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.data_movimento
	 * @param dataMovimento  the value for covidrsa_t_movimento_ospite.data_movimento
	 * @mbg.generated
	 */
	public void setDataMovimento(Date dataMovimento) {
		this.dataMovimento = dataMovimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.tipo_mov_ospite_id
	 * @return  the value of covidrsa_t_movimento_ospite.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	public Integer getTipoMovOspiteId() {
		return tipoMovOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.tipo_mov_ospite_id
	 * @param tipoMovOspiteId  the value for covidrsa_t_movimento_ospite.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	public void setTipoMovOspiteId(Integer tipoMovOspiteId) {
		this.tipoMovOspiteId = tipoMovOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.id_struttura_od
	 * @return  the value of covidrsa_t_movimento_ospite.id_struttura_od
	 * @mbg.generated
	 */
	public String getIdStrutturaOd() {
		return idStrutturaOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.id_struttura_od
	 * @param idStrutturaOd  the value for covidrsa_t_movimento_ospite.id_struttura_od
	 * @mbg.generated
	 */
	public void setIdStrutturaOd(String idStrutturaOd) {
		this.idStrutturaOd = idStrutturaOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.flg_preserva_posto
	 * @return  the value of covidrsa_t_movimento_ospite.flg_preserva_posto
	 * @mbg.generated
	 */
	public Boolean getFlgPreservaPosto() {
		return flgPreservaPosto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.flg_preserva_posto
	 * @param flgPreservaPosto  the value for covidrsa_t_movimento_ospite.flg_preserva_posto
	 * @mbg.generated
	 */
	public void setFlgPreservaPosto(Boolean flgPreservaPosto) {
		this.flgPreservaPosto = flgPreservaPosto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.note
	 * @return  the value of covidrsa_t_movimento_ospite.note
	 * @mbg.generated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.note
	 * @param note  the value for covidrsa_t_movimento_ospite.note
	 * @mbg.generated
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.validita_inizio
	 * @return  the value of covidrsa_t_movimento_ospite.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.validita_inizio
	 * @param validitaInizio  the value for covidrsa_t_movimento_ospite.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.validita_fine
	 * @return  the value of covidrsa_t_movimento_ospite.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.validita_fine
	 * @param validitaFine  the value for covidrsa_t_movimento_ospite.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.data_creazione
	 * @return  the value of covidrsa_t_movimento_ospite.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.data_creazione
	 * @param dataCreazione  the value for covidrsa_t_movimento_ospite.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.data_modifica
	 * @return  the value of covidrsa_t_movimento_ospite.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.data_modifica
	 * @param dataModifica  the value for covidrsa_t_movimento_ospite.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.data_cancellazione
	 * @return  the value of covidrsa_t_movimento_ospite.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_t_movimento_ospite.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.utente_operazione
	 * @return  the value of covidrsa_t_movimento_ospite.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_t_movimento_ospite.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_movimento_ospite.condizioni_ospite_id
	 * @return  the value of covidrsa_t_movimento_ospite.condizioni_ospite_id
	 * @mbg.generated
	 */
	public Integer getCondizioniOspiteId() {
		return condizioniOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_movimento_ospite.condizioni_ospite_id
	 * @param condizioniOspiteId  the value for covidrsa_t_movimento_ospite.condizioni_ospite_id
	 * @mbg.generated
	 */
	public void setCondizioniOspiteId(Integer condizioniOspiteId) {
		this.condizioniOspiteId = condizioniOspiteId;
	}
}