/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaDStatoRendicontazione extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.stato_rend_id
	 * @mbg.generated
	 */
	private Integer statoRendId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.stato_rend_cod
	 * @mbg.generated
	 */
	private String statoRendCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.stato_rend_desc
	 * @mbg.generated
	 */
	private String statoRendDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.flg_modificabile
	 * @mbg.generated
	 */
	private Boolean flgModificabile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.flg_stato_iniziale
	 * @mbg.generated
	 */
	private Boolean flgStatoIniziale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.flg_stato_finale
	 * @mbg.generated
	 */
	private Boolean flgStatoFinale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_stato_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_id
	 * @return  the value of covidrsa_d_stato_rendicontazione.stato_rend_id
	 * @mbg.generated
	 */
	public Integer getStatoRendId() {
		return statoRendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_id
	 * @param statoRendId  the value for covidrsa_d_stato_rendicontazione.stato_rend_id
	 * @mbg.generated
	 */
	public void setStatoRendId(Integer statoRendId) {
		this.statoRendId = statoRendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_cod
	 * @return  the value of covidrsa_d_stato_rendicontazione.stato_rend_cod
	 * @mbg.generated
	 */
	public String getStatoRendCod() {
		return statoRendCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_cod
	 * @param statoRendCod  the value for covidrsa_d_stato_rendicontazione.stato_rend_cod
	 * @mbg.generated
	 */
	public void setStatoRendCod(String statoRendCod) {
		this.statoRendCod = statoRendCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_desc
	 * @return  the value of covidrsa_d_stato_rendicontazione.stato_rend_desc
	 * @mbg.generated
	 */
	public String getStatoRendDesc() {
		return statoRendDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.stato_rend_desc
	 * @param statoRendDesc  the value for covidrsa_d_stato_rendicontazione.stato_rend_desc
	 * @mbg.generated
	 */
	public void setStatoRendDesc(String statoRendDesc) {
		this.statoRendDesc = statoRendDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.flg_modificabile
	 * @return  the value of covidrsa_d_stato_rendicontazione.flg_modificabile
	 * @mbg.generated
	 */
	public Boolean getFlgModificabile() {
		return flgModificabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.flg_modificabile
	 * @param flgModificabile  the value for covidrsa_d_stato_rendicontazione.flg_modificabile
	 * @mbg.generated
	 */
	public void setFlgModificabile(Boolean flgModificabile) {
		this.flgModificabile = flgModificabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.flg_stato_iniziale
	 * @return  the value of covidrsa_d_stato_rendicontazione.flg_stato_iniziale
	 * @mbg.generated
	 */
	public Boolean getFlgStatoIniziale() {
		return flgStatoIniziale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.flg_stato_iniziale
	 * @param flgStatoIniziale  the value for covidrsa_d_stato_rendicontazione.flg_stato_iniziale
	 * @mbg.generated
	 */
	public void setFlgStatoIniziale(Boolean flgStatoIniziale) {
		this.flgStatoIniziale = flgStatoIniziale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.flg_stato_finale
	 * @return  the value of covidrsa_d_stato_rendicontazione.flg_stato_finale
	 * @mbg.generated
	 */
	public Boolean getFlgStatoFinale() {
		return flgStatoFinale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.flg_stato_finale
	 * @param flgStatoFinale  the value for covidrsa_d_stato_rendicontazione.flg_stato_finale
	 * @mbg.generated
	 */
	public void setFlgStatoFinale(Boolean flgStatoFinale) {
		this.flgStatoFinale = flgStatoFinale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.validita_inizio
	 * @return  the value of covidrsa_d_stato_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.validita_inizio
	 * @param validitaInizio  the value for covidrsa_d_stato_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.validita_fine
	 * @return  the value of covidrsa_d_stato_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.validita_fine
	 * @param validitaFine  the value for covidrsa_d_stato_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.data_creazione
	 * @return  the value of covidrsa_d_stato_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.data_creazione
	 * @param dataCreazione  the value for covidrsa_d_stato_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.data_modifica
	 * @return  the value of covidrsa_d_stato_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.data_modifica
	 * @param dataModifica  the value for covidrsa_d_stato_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.data_cancellazione
	 * @return  the value of covidrsa_d_stato_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_d_stato_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_stato_rendicontazione.utente_operazione
	 * @return  the value of covidrsa_d_stato_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_stato_rendicontazione.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_d_stato_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}