/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaTInvioPbandi extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_pbandi_id
     *
     * @mbg.generated
     */
    private Integer invioPbandiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_pbandi_cod
     *
     * @mbg.generated
     */
    private String invioPbandiCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_pbandi_uuid_ext
     *
     * @mbg.generated
     */
    private String invioPbandiUuidExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_pbandi_cod_ext
     *
     * @mbg.generated
     */
    private String invioPbandiCodExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.file_id_dichiarazione_spesa
     *
     * @mbg.generated
     */
    private Integer fileIdDichiarazioneSpesa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_data
     *
     * @mbg.generated
     */
    private Date invioData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_request
     *
     * @mbg.generated
     */
    private String invioRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_result
     *
     * @mbg.generated
     */
    private String invioResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_error_cod
     *
     * @mbg.generated
     */
    private String invioErrorCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_error_message
     *
     * @mbg.generated
     */
    private String invioErrorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.callback_data
     *
     * @mbg.generated
     */
    private Date callbackData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.callback_esito
     *
     * @mbg.generated
     */
    private String callbackEsito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.callback_error_cod
     *
     * @mbg.generated
     */
    private String callbackErrorCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.callback_error_message
     *
     * @mbg.generated
     */
    private String callbackErrorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_invio_pbandi.invio_esito
     *
     * @mbg.generated
     */
    private String invioEsito;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_id
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_pbandi_id
     *
     * @mbg.generated
     */
    public Integer getInvioPbandiId() {
        return invioPbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_id
     *
     * @param invioPbandiId the value for covidrsa_t_invio_pbandi.invio_pbandi_id
     *
     * @mbg.generated
     */
    public void setInvioPbandiId(Integer invioPbandiId) {
        this.invioPbandiId = invioPbandiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_cod
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_pbandi_cod
     *
     * @mbg.generated
     */
    public String getInvioPbandiCod() {
        return invioPbandiCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_cod
     *
     * @param invioPbandiCod the value for covidrsa_t_invio_pbandi.invio_pbandi_cod
     *
     * @mbg.generated
     */
    public void setInvioPbandiCod(String invioPbandiCod) {
        this.invioPbandiCod = invioPbandiCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_uuid_ext
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_pbandi_uuid_ext
     *
     * @mbg.generated
     */
    public String getInvioPbandiUuidExt() {
        return invioPbandiUuidExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_uuid_ext
     *
     * @param invioPbandiUuidExt the value for covidrsa_t_invio_pbandi.invio_pbandi_uuid_ext
     *
     * @mbg.generated
     */
    public void setInvioPbandiUuidExt(String invioPbandiUuidExt) {
        this.invioPbandiUuidExt = invioPbandiUuidExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_cod_ext
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_pbandi_cod_ext
     *
     * @mbg.generated
     */
    public String getInvioPbandiCodExt() {
        return invioPbandiCodExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_pbandi_cod_ext
     *
     * @param invioPbandiCodExt the value for covidrsa_t_invio_pbandi.invio_pbandi_cod_ext
     *
     * @mbg.generated
     */
    public void setInvioPbandiCodExt(String invioPbandiCodExt) {
        this.invioPbandiCodExt = invioPbandiCodExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.file_id_dichiarazione_spesa
     *
     * @return the value of covidrsa_t_invio_pbandi.file_id_dichiarazione_spesa
     *
     * @mbg.generated
     */
    public Integer getFileIdDichiarazioneSpesa() {
        return fileIdDichiarazioneSpesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.file_id_dichiarazione_spesa
     *
     * @param fileIdDichiarazioneSpesa the value for covidrsa_t_invio_pbandi.file_id_dichiarazione_spesa
     *
     * @mbg.generated
     */
    public void setFileIdDichiarazioneSpesa(Integer fileIdDichiarazioneSpesa) {
        this.fileIdDichiarazioneSpesa = fileIdDichiarazioneSpesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_data
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_data
     *
     * @mbg.generated
     */
    public Date getInvioData() {
        return invioData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_data
     *
     * @param invioData the value for covidrsa_t_invio_pbandi.invio_data
     *
     * @mbg.generated
     */
    public void setInvioData(Date invioData) {
        this.invioData = invioData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_request
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_request
     *
     * @mbg.generated
     */
    public String getInvioRequest() {
        return invioRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_request
     *
     * @param invioRequest the value for covidrsa_t_invio_pbandi.invio_request
     *
     * @mbg.generated
     */
    public void setInvioRequest(String invioRequest) {
        this.invioRequest = invioRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_result
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_result
     *
     * @mbg.generated
     */
    public String getInvioResult() {
        return invioResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_result
     *
     * @param invioResult the value for covidrsa_t_invio_pbandi.invio_result
     *
     * @mbg.generated
     */
    public void setInvioResult(String invioResult) {
        this.invioResult = invioResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_error_cod
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_error_cod
     *
     * @mbg.generated
     */
    public String getInvioErrorCod() {
        return invioErrorCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_error_cod
     *
     * @param invioErrorCod the value for covidrsa_t_invio_pbandi.invio_error_cod
     *
     * @mbg.generated
     */
    public void setInvioErrorCod(String invioErrorCod) {
        this.invioErrorCod = invioErrorCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_error_message
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_error_message
     *
     * @mbg.generated
     */
    public String getInvioErrorMessage() {
        return invioErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_error_message
     *
     * @param invioErrorMessage the value for covidrsa_t_invio_pbandi.invio_error_message
     *
     * @mbg.generated
     */
    public void setInvioErrorMessage(String invioErrorMessage) {
        this.invioErrorMessage = invioErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.callback_data
     *
     * @return the value of covidrsa_t_invio_pbandi.callback_data
     *
     * @mbg.generated
     */
    public Date getCallbackData() {
        return callbackData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.callback_data
     *
     * @param callbackData the value for covidrsa_t_invio_pbandi.callback_data
     *
     * @mbg.generated
     */
    public void setCallbackData(Date callbackData) {
        this.callbackData = callbackData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.callback_esito
     *
     * @return the value of covidrsa_t_invio_pbandi.callback_esito
     *
     * @mbg.generated
     */
    public String getCallbackEsito() {
        return callbackEsito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.callback_esito
     *
     * @param callbackEsito the value for covidrsa_t_invio_pbandi.callback_esito
     *
     * @mbg.generated
     */
    public void setCallbackEsito(String callbackEsito) {
        this.callbackEsito = callbackEsito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.callback_error_cod
     *
     * @return the value of covidrsa_t_invio_pbandi.callback_error_cod
     *
     * @mbg.generated
     */
    public String getCallbackErrorCod() {
        return callbackErrorCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.callback_error_cod
     *
     * @param callbackErrorCod the value for covidrsa_t_invio_pbandi.callback_error_cod
     *
     * @mbg.generated
     */
    public void setCallbackErrorCod(String callbackErrorCod) {
        this.callbackErrorCod = callbackErrorCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.callback_error_message
     *
     * @return the value of covidrsa_t_invio_pbandi.callback_error_message
     *
     * @mbg.generated
     */
    public String getCallbackErrorMessage() {
        return callbackErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.callback_error_message
     *
     * @param callbackErrorMessage the value for covidrsa_t_invio_pbandi.callback_error_message
     *
     * @mbg.generated
     */
    public void setCallbackErrorMessage(String callbackErrorMessage) {
        this.callbackErrorMessage = callbackErrorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_invio_pbandi.invio_esito
     *
     * @return the value of covidrsa_t_invio_pbandi.invio_esito
     *
     * @mbg.generated
     */
    public String getInvioEsito() {
        return invioEsito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_invio_pbandi.invio_esito
     *
     * @param invioEsito the value for covidrsa_t_invio_pbandi.invio_esito
     *
     * @mbg.generated
     */
    public void setInvioEsito(String invioEsito) {
        this.invioEsito = invioEsito;
    }
}