/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.math.BigDecimal;
import java.util.Date;

public class CovidrsaRWelfareFascia extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.str_welf_fascia_id
     *
     * @mbg.generated
     */
    private Integer strWelfFasciaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.str_welfare_id
     *
     * @mbg.generated
     */
    private Integer strWelfareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.welfare_fascia_id
     *
     * @mbg.generated
     */
    private Integer welfareFasciaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.tariffa_mensile_massima
     *
     * @mbg.generated
     */
    private BigDecimal tariffaMensileMassima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_r_struttura_welfare_fascia.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.str_welf_fascia_id
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.str_welf_fascia_id
     *
     * @mbg.generated
     */
    public Integer getStrWelfFasciaId() {
        return strWelfFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.str_welf_fascia_id
     *
     * @param strWelfFasciaId the value for covidrsa_r_struttura_welfare_fascia.str_welf_fascia_id
     *
     * @mbg.generated
     */
    public void setStrWelfFasciaId(Integer strWelfFasciaId) {
        this.strWelfFasciaId = strWelfFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.str_welfare_id
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.str_welfare_id
     *
     * @mbg.generated
     */
    public Integer getStrWelfareId() {
        return strWelfareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.str_welfare_id
     *
     * @param strWelfareId the value for covidrsa_r_struttura_welfare_fascia.str_welfare_id
     *
     * @mbg.generated
     */
    public void setStrWelfareId(Integer strWelfareId) {
        this.strWelfareId = strWelfareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.welfare_fascia_id
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.welfare_fascia_id
     *
     * @mbg.generated
     */
    public Integer getWelfareFasciaId() {
        return welfareFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.welfare_fascia_id
     *
     * @param welfareFasciaId the value for covidrsa_r_struttura_welfare_fascia.welfare_fascia_id
     *
     * @mbg.generated
     */
    public void setWelfareFasciaId(Integer welfareFasciaId) {
        this.welfareFasciaId = welfareFasciaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.tariffa_mensile_massima
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.tariffa_mensile_massima
     *
     * @mbg.generated
     */
    public BigDecimal getTariffaMensileMassima() {
        return tariffaMensileMassima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.tariffa_mensile_massima
     *
     * @param tariffaMensileMassima the value for covidrsa_r_struttura_welfare_fascia.tariffa_mensile_massima
     *
     * @mbg.generated
     */
    public void setTariffaMensileMassima(BigDecimal tariffaMensileMassima) {
        this.tariffaMensileMassima = tariffaMensileMassima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.validita_inizio
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_r_struttura_welfare_fascia.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.validita_fine
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.validita_fine
     *
     * @param validitaFine the value for covidrsa_r_struttura_welfare_fascia.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.utente_operazione
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_r_struttura_welfare_fascia.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.data_creazione
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.data_creazione
     *
     * @param dataCreazione the value for covidrsa_r_struttura_welfare_fascia.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.data_modifica
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.data_modifica
     *
     * @param dataModifica the value for covidrsa_r_struttura_welfare_fascia.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_r_struttura_welfare_fascia.data_cancellazione
     *
     * @return the value of covidrsa_r_struttura_welfare_fascia.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_r_struttura_welfare_fascia.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_r_struttura_welfare_fascia.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}