/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaDTipoMovOspite extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_id
     *
     * @mbg.generated
     */
    private Integer tipoMovOspiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_cod
     *
     * @mbg.generated
     */
    private String tipoMovOspiteCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_desc
     *
     * @mbg.generated
     */
    private String tipoMovOspiteDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.flg_ingresso
     *
     * @mbg.generated
     */
    private Boolean flgIngresso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.flg_uscita
     *
     * @mbg.generated
     */
    private Boolean flgUscita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_hint
     *
     * @mbg.generated
     */
    private String tipoMovOspiteHint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_id
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_id
     *
     * @mbg.generated
     */
    public Integer getTipoMovOspiteId() {
        return tipoMovOspiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_id
     *
     * @param tipoMovOspiteId the value for covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_id
     *
     * @mbg.generated
     */
    public void setTipoMovOspiteId(Integer tipoMovOspiteId) {
        this.tipoMovOspiteId = tipoMovOspiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_cod
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_cod
     *
     * @mbg.generated
     */
    public String getTipoMovOspiteCod() {
        return tipoMovOspiteCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_cod
     *
     * @param tipoMovOspiteCod the value for covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_cod
     *
     * @mbg.generated
     */
    public void setTipoMovOspiteCod(String tipoMovOspiteCod) {
        this.tipoMovOspiteCod = tipoMovOspiteCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_desc
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_desc
     *
     * @mbg.generated
     */
    public String getTipoMovOspiteDesc() {
        return tipoMovOspiteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_desc
     *
     * @param tipoMovOspiteDesc the value for covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_desc
     *
     * @mbg.generated
     */
    public void setTipoMovOspiteDesc(String tipoMovOspiteDesc) {
        this.tipoMovOspiteDesc = tipoMovOspiteDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.flg_ingresso
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.flg_ingresso
     *
     * @mbg.generated
     */
    public Boolean getFlgIngresso() {
        return flgIngresso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.flg_ingresso
     *
     * @param flgIngresso the value for covidrsa_d_tipo_mov_ospite.flg_ingresso
     *
     * @mbg.generated
     */
    public void setFlgIngresso(Boolean flgIngresso) {
        this.flgIngresso = flgIngresso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.validita_inizio
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_d_tipo_mov_ospite.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.validita_fine
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.validita_fine
     *
     * @param validitaFine the value for covidrsa_d_tipo_mov_ospite.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.data_creazione
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.data_creazione
     *
     * @param dataCreazione the value for covidrsa_d_tipo_mov_ospite.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.data_modifica
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.data_modifica
     *
     * @param dataModifica the value for covidrsa_d_tipo_mov_ospite.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.data_cancellazione
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_d_tipo_mov_ospite.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.utente_operazione
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_d_tipo_mov_ospite.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.flg_uscita
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.flg_uscita
     *
     * @mbg.generated
     */
    public Boolean getFlgUscita() {
        return flgUscita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.flg_uscita
     *
     * @param flgUscita the value for covidrsa_d_tipo_mov_ospite.flg_uscita
     *
     * @mbg.generated
     */
    public void setFlgUscita(Boolean flgUscita) {
        this.flgUscita = flgUscita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_hint
     *
     * @return the value of covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_hint
     *
     * @mbg.generated
     */
    public String getTipoMovOspiteHint() {
        return tipoMovOspiteHint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_hint
     *
     * @param tipoMovOspiteHint the value for covidrsa_d_tipo_mov_ospite.tipo_mov_ospite_hint
     *
     * @mbg.generated
     */
    public void setTipoMovOspiteHint(String tipoMovOspiteHint) {
        this.tipoMovOspiteHint = tipoMovOspiteHint;
    }
}