/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaDWorkflowRendicontazione extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.workflow_rend_id
	 * @mbg.generated
	 */
	private Integer workflowRendId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_old
	 * @mbg.generated
	 */
	private Integer statoRendIdOld;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_new
	 * @mbg.generated
	 */
	private Integer statoRendIdNew;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.flg_struttura
	 * @mbg.generated
	 */
	private Boolean flgStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.flg_ente_gestore
	 * @mbg.generated
	 */
	private Boolean flgEnteGestore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.flg_controlla_file
	 * @mbg.generated
	 */
	private Boolean flgControllaFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.informativa_utente
	 * @mbg.generated
	 */
	private String informativaUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_d_workflow_rendicontazione.flg_genera_dichiarazione
	 * @mbg.generated
	 */
	private Boolean flgGeneraDichiarazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.workflow_rend_id
	 * @return  the value of covidrsa_d_workflow_rendicontazione.workflow_rend_id
	 * @mbg.generated
	 */
	public Integer getWorkflowRendId() {
		return workflowRendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.workflow_rend_id
	 * @param workflowRendId  the value for covidrsa_d_workflow_rendicontazione.workflow_rend_id
	 * @mbg.generated
	 */
	public void setWorkflowRendId(Integer workflowRendId) {
		this.workflowRendId = workflowRendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_old
	 * @return  the value of covidrsa_d_workflow_rendicontazione.stato_rend_id_old
	 * @mbg.generated
	 */
	public Integer getStatoRendIdOld() {
		return statoRendIdOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_old
	 * @param statoRendIdOld  the value for covidrsa_d_workflow_rendicontazione.stato_rend_id_old
	 * @mbg.generated
	 */
	public void setStatoRendIdOld(Integer statoRendIdOld) {
		this.statoRendIdOld = statoRendIdOld;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_new
	 * @return  the value of covidrsa_d_workflow_rendicontazione.stato_rend_id_new
	 * @mbg.generated
	 */
	public Integer getStatoRendIdNew() {
		return statoRendIdNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.stato_rend_id_new
	 * @param statoRendIdNew  the value for covidrsa_d_workflow_rendicontazione.stato_rend_id_new
	 * @mbg.generated
	 */
	public void setStatoRendIdNew(Integer statoRendIdNew) {
		this.statoRendIdNew = statoRendIdNew;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.flg_struttura
	 * @return  the value of covidrsa_d_workflow_rendicontazione.flg_struttura
	 * @mbg.generated
	 */
	public Boolean getFlgStruttura() {
		return flgStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.flg_struttura
	 * @param flgStruttura  the value for covidrsa_d_workflow_rendicontazione.flg_struttura
	 * @mbg.generated
	 */
	public void setFlgStruttura(Boolean flgStruttura) {
		this.flgStruttura = flgStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.flg_ente_gestore
	 * @return  the value of covidrsa_d_workflow_rendicontazione.flg_ente_gestore
	 * @mbg.generated
	 */
	public Boolean getFlgEnteGestore() {
		return flgEnteGestore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.flg_ente_gestore
	 * @param flgEnteGestore  the value for covidrsa_d_workflow_rendicontazione.flg_ente_gestore
	 * @mbg.generated
	 */
	public void setFlgEnteGestore(Boolean flgEnteGestore) {
		this.flgEnteGestore = flgEnteGestore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.validita_inizio
	 * @return  the value of covidrsa_d_workflow_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.validita_inizio
	 * @param validitaInizio  the value for covidrsa_d_workflow_rendicontazione.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.validita_fine
	 * @return  the value of covidrsa_d_workflow_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.validita_fine
	 * @param validitaFine  the value for covidrsa_d_workflow_rendicontazione.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.data_creazione
	 * @return  the value of covidrsa_d_workflow_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.data_creazione
	 * @param dataCreazione  the value for covidrsa_d_workflow_rendicontazione.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.data_modifica
	 * @return  the value of covidrsa_d_workflow_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.data_modifica
	 * @param dataModifica  the value for covidrsa_d_workflow_rendicontazione.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.data_cancellazione
	 * @return  the value of covidrsa_d_workflow_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_d_workflow_rendicontazione.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.utente_operazione
	 * @return  the value of covidrsa_d_workflow_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_d_workflow_rendicontazione.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.flg_controlla_file
	 * @return  the value of covidrsa_d_workflow_rendicontazione.flg_controlla_file
	 * @mbg.generated
	 */
	public Boolean getFlgControllaFile() {
		return flgControllaFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.flg_controlla_file
	 * @param flgControllaFile  the value for covidrsa_d_workflow_rendicontazione.flg_controlla_file
	 * @mbg.generated
	 */
	public void setFlgControllaFile(Boolean flgControllaFile) {
		this.flgControllaFile = flgControllaFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.informativa_utente
	 * @return  the value of covidrsa_d_workflow_rendicontazione.informativa_utente
	 * @mbg.generated
	 */
	public String getInformativaUtente() {
		return informativaUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.informativa_utente
	 * @param informativaUtente  the value for covidrsa_d_workflow_rendicontazione.informativa_utente
	 * @mbg.generated
	 */
	public void setInformativaUtente(String informativaUtente) {
		this.informativaUtente = informativaUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_d_workflow_rendicontazione.flg_genera_dichiarazione
	 * @return  the value of covidrsa_d_workflow_rendicontazione.flg_genera_dichiarazione
	 * @mbg.generated
	 */
	public Boolean getFlgGeneraDichiarazione() {
		return flgGeneraDichiarazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_d_workflow_rendicontazione.flg_genera_dichiarazione
	 * @param flgGeneraDichiarazione  the value for covidrsa_d_workflow_rendicontazione.flg_genera_dichiarazione
	 * @mbg.generated
	 */
	public void setFlgGeneraDichiarazione(Boolean flgGeneraDichiarazione) {
		this.flgGeneraDichiarazione = flgGeneraDichiarazione;
	}
}