/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidrsaRTipoMovOspiteNaturaSad extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.tmo_natura_sod_id
	 * @mbg.generated
	 */
	private Integer tmoNaturaSodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	private Integer tipoMovOspiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.natura_struttura_od
	 * @mbg.generated
	 */
	private String naturaStrutturaOd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_r_tipo_mov_ospite_natura_sod.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.tmo_natura_sod_id
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.tmo_natura_sod_id
	 * @mbg.generated
	 */
	public Integer getTmoNaturaSodId() {
		return tmoNaturaSodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.tmo_natura_sod_id
	 * @param tmoNaturaSodId  the value for covidrsa_r_tipo_mov_ospite_natura_sod.tmo_natura_sod_id
	 * @mbg.generated
	 */
	public void setTmoNaturaSodId(Integer tmoNaturaSodId) {
		this.tmoNaturaSodId = tmoNaturaSodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.tipo_mov_ospite_id
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	public Integer getTipoMovOspiteId() {
		return tipoMovOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.tipo_mov_ospite_id
	 * @param tipoMovOspiteId  the value for covidrsa_r_tipo_mov_ospite_natura_sod.tipo_mov_ospite_id
	 * @mbg.generated
	 */
	public void setTipoMovOspiteId(Integer tipoMovOspiteId) {
		this.tipoMovOspiteId = tipoMovOspiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.natura_struttura_od
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.natura_struttura_od
	 * @mbg.generated
	 */
	public String getNaturaStrutturaOd() {
		return naturaStrutturaOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.natura_struttura_od
	 * @param naturaStrutturaOd  the value for covidrsa_r_tipo_mov_ospite_natura_sod.natura_struttura_od
	 * @mbg.generated
	 */
	public void setNaturaStrutturaOd(String naturaStrutturaOd) {
		this.naturaStrutturaOd = naturaStrutturaOd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_inizio
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_inizio
	 * @param validitaInizio  the value for covidrsa_r_tipo_mov_ospite_natura_sod.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_fine
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.validita_fine
	 * @param validitaFine  the value for covidrsa_r_tipo_mov_ospite_natura_sod.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_creazione
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_creazione
	 * @param dataCreazione  the value for covidrsa_r_tipo_mov_ospite_natura_sod.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_modifica
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_modifica
	 * @param dataModifica  the value for covidrsa_r_tipo_mov_ospite_natura_sod.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_cancellazione
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_r_tipo_mov_ospite_natura_sod.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.utente_operazione
	 * @return  the value of covidrsa_r_tipo_mov_ospite_natura_sod.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_r_tipo_mov_ospite_natura_sod.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_r_tipo_mov_ospite_natura_sod.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}