/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class MedicoSoggettoAura {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_sogg_aura.id_medico
     *
     * @mbg.generated
     */
    private Long idMedico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_sogg_aura.id_aura_sogg
     *
     * @mbg.generated
     */
    private Long idAuraSogg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_sogg_aura.data_scelta
     *
     * @mbg.generated
     */
    private Date dataScelta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_sogg_aura.data_revoca
     *
     * @mbg.generated
     */
    private Date dataRevoca;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_sogg_aura.id_medico
     *
     * @return the value of r_medico_sogg_aura.id_medico
     *
     * @mbg.generated
     */
    public Long getIdMedico() {
        return idMedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_sogg_aura.id_medico
     *
     * @param idMedico the value for r_medico_sogg_aura.id_medico
     *
     * @mbg.generated
     */
    public void setIdMedico(Long idMedico) {
        this.idMedico = idMedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_sogg_aura.id_aura_sogg
     *
     * @return the value of r_medico_sogg_aura.id_aura_sogg
     *
     * @mbg.generated
     */
    public Long getIdAuraSogg() {
        return idAuraSogg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_sogg_aura.id_aura_sogg
     *
     * @param idAuraSogg the value for r_medico_sogg_aura.id_aura_sogg
     *
     * @mbg.generated
     */
    public void setIdAuraSogg(Long idAuraSogg) {
        this.idAuraSogg = idAuraSogg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_sogg_aura.data_scelta
     *
     * @return the value of r_medico_sogg_aura.data_scelta
     *
     * @mbg.generated
     */
    public Date getDataScelta() {
        return dataScelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_sogg_aura.data_scelta
     *
     * @param dataScelta the value for r_medico_sogg_aura.data_scelta
     *
     * @mbg.generated
     */
    public void setDataScelta(Date dataScelta) {
        this.dataScelta = dataScelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_sogg_aura.data_revoca
     *
     * @return the value of r_medico_sogg_aura.data_revoca
     *
     * @mbg.generated
     */
    public Date getDataRevoca() {
        return dataRevoca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_sogg_aura.data_revoca
     *
     * @param dataRevoca the value for r_medico_sogg_aura.data_revoca
     *
     * @mbg.generated
     */
    public void setDataRevoca(Date dataRevoca) {
        this.dataRevoca = dataRevoca;
    }
}
