/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

public class Medico {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.id_medico
	 * @mbg.generated
	 */
	private Long idMedico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.cf_medico
	 * @mbg.generated
	 */
	private String cfMedico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.codice_reg
	 * @mbg.generated
	 */
	private String codiceReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.cognome
	 * @mbg.generated
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.nome
	 * @mbg.generated
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.sostituito_da
	 * @mbg.generated
	 */
	private String sostituitoDa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico.sostituisce
	 * @mbg.generated
	 */
	private String sostituisce;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.id_medico
	 * @return  the value of medico.id_medico
	 * @mbg.generated
	 */
	public Long getIdMedico() {
		return idMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.id_medico
	 * @param idMedico  the value for medico.id_medico
	 * @mbg.generated
	 */
	public void setIdMedico(Long idMedico) {
		this.idMedico = idMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.cf_medico
	 * @return  the value of medico.cf_medico
	 * @mbg.generated
	 */
	public String getCfMedico() {
		return cfMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.cf_medico
	 * @param cfMedico  the value for medico.cf_medico
	 * @mbg.generated
	 */
	public void setCfMedico(String cfMedico) {
		this.cfMedico = cfMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.codice_reg
	 * @return  the value of medico.codice_reg
	 * @mbg.generated
	 */
	public String getCodiceReg() {
		return codiceReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.codice_reg
	 * @param codiceReg  the value for medico.codice_reg
	 * @mbg.generated
	 */
	public void setCodiceReg(String codiceReg) {
		this.codiceReg = codiceReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.cognome
	 * @return  the value of medico.cognome
	 * @mbg.generated
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.cognome
	 * @param cognome  the value for medico.cognome
	 * @mbg.generated
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.nome
	 * @return  the value of medico.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.nome
	 * @param nome  the value for medico.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.sostituito_da
	 * @return  the value of medico.sostituito_da
	 * @mbg.generated
	 */
	public String getSostituitoDa() {
		return sostituitoDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.sostituito_da
	 * @param sostituitoDa  the value for medico.sostituito_da
	 * @mbg.generated
	 */
	public void setSostituitoDa(String sostituitoDa) {
		this.sostituitoDa = sostituitoDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico.sostituisce
	 * @return  the value of medico.sostituisce
	 * @mbg.generated
	 */
	public String getSostituisce() {
		return sostituisce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico.sostituisce
	 * @param sostituisce  the value for medico.sostituisce
	 * @mbg.generated
	 */
	public void setSostituisce(String sostituisce) {
		this.sostituisce = sostituisce;
	}
}