/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class RsaDecessi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_id
     *
     * @mbg.generated
     */
    private Integer decId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_totali_anno_precedente
     *
     * @mbg.generated
     */
    private Integer decNumTotaliAnnoPrecedente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_totali
     *
     * @mbg.generated
     */
    private Integer decNumTotali;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_totali_covid
     *
     * @mbg.generated
     */
    private Integer decNumTotaliCovid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_ospedale
     *
     * @mbg.generated
     */
    private Integer decNumInOspedale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_ospedale_covid
     *
     * @mbg.generated
     */
    private Integer decNumInOspedaleCovid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.id_struttura
     *
     * @mbg.generated
     */
    private String idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.str_categoria_id
     *
     * @mbg.generated
     */
    private Integer strCategoriaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.data_rilevazione
     *
     * @mbg.generated
     */
    private Date dataRilevazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.data_visibilita
     *
     * @mbg.generated
     */
    private Date dataVisibilita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_ospedale_anno_precedente
     *
     * @mbg.generated
     */
    private Integer decNumInOspedaleAnnoPrecedente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_struttura_anno_precedente
     *
     * @mbg.generated
     */
    private Integer decNumInStrutturaAnnoPrecedente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_struttura
     *
     * @mbg.generated
     */
    private Integer decNumInStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_struttura_covid
     *
     * @mbg.generated
     */
    private Integer decNumInStrutturaCovid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumUltimaSettimana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_covid_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumCovidUltimaSettimana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_struttura_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumInStrutturaUltimaSettimana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_struttura_covid_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumInStrutturaCovidUltimaSettimana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_ospedale_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumInOspedaleUltimaSettimana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_decessi.dec_num_in_ospedale_covid_ultima_settimana
     *
     * @mbg.generated
     */
    private Integer decNumInOspedaleCovidUltimaSettimana;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_id
     *
     * @return the value of covidrsa_t_decessi.dec_id
     *
     * @mbg.generated
     */
    public Integer getDecId() {
        return decId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_id
     *
     * @param decId the value for covidrsa_t_decessi.dec_id
     *
     * @mbg.generated
     */
    public void setDecId(Integer decId) {
        this.decId = decId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_totali_anno_precedente
     *
     * @return the value of covidrsa_t_decessi.dec_num_totali_anno_precedente
     *
     * @mbg.generated
     */
    public Integer getDecNumTotaliAnnoPrecedente() {
        return decNumTotaliAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_totali_anno_precedente
     *
     * @param decNumTotaliAnnoPrecedente the value for covidrsa_t_decessi.dec_num_totali_anno_precedente
     *
     * @mbg.generated
     */
    public void setDecNumTotaliAnnoPrecedente(Integer decNumTotaliAnnoPrecedente) {
        this.decNumTotaliAnnoPrecedente = decNumTotaliAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_totali
     *
     * @return the value of covidrsa_t_decessi.dec_num_totali
     *
     * @mbg.generated
     */
    public Integer getDecNumTotali() {
        return decNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_totali
     *
     * @param decNumTotali the value for covidrsa_t_decessi.dec_num_totali
     *
     * @mbg.generated
     */
    public void setDecNumTotali(Integer decNumTotali) {
        this.decNumTotali = decNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_totali_covid
     *
     * @return the value of covidrsa_t_decessi.dec_num_totali_covid
     *
     * @mbg.generated
     */
    public Integer getDecNumTotaliCovid() {
        return decNumTotaliCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_totali_covid
     *
     * @param decNumTotaliCovid the value for covidrsa_t_decessi.dec_num_totali_covid
     *
     * @mbg.generated
     */
    public void setDecNumTotaliCovid(Integer decNumTotaliCovid) {
        this.decNumTotaliCovid = decNumTotaliCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_ospedale
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_ospedale
     *
     * @mbg.generated
     */
    public Integer getDecNumInOspedale() {
        return decNumInOspedale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_ospedale
     *
     * @param decNumInOspedale the value for covidrsa_t_decessi.dec_num_in_ospedale
     *
     * @mbg.generated
     */
    public void setDecNumInOspedale(Integer decNumInOspedale) {
        this.decNumInOspedale = decNumInOspedale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_covid
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_ospedale_covid
     *
     * @mbg.generated
     */
    public Integer getDecNumInOspedaleCovid() {
        return decNumInOspedaleCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_covid
     *
     * @param decNumInOspedaleCovid the value for covidrsa_t_decessi.dec_num_in_ospedale_covid
     *
     * @mbg.generated
     */
    public void setDecNumInOspedaleCovid(Integer decNumInOspedaleCovid) {
        this.decNumInOspedaleCovid = decNumInOspedaleCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.id_struttura
     *
     * @return the value of covidrsa_t_decessi.id_struttura
     *
     * @mbg.generated
     */
    public String getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.id_struttura
     *
     * @param idStruttura the value for covidrsa_t_decessi.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(String idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.str_categoria_id
     *
     * @return the value of covidrsa_t_decessi.str_categoria_id
     *
     * @mbg.generated
     */
    public Integer getStrCategoriaId() {
        return strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.str_categoria_id
     *
     * @param strCategoriaId the value for covidrsa_t_decessi.str_categoria_id
     *
     * @mbg.generated
     */
    public void setStrCategoriaId(Integer strCategoriaId) {
        this.strCategoriaId = strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.data_rilevazione
     *
     * @return the value of covidrsa_t_decessi.data_rilevazione
     *
     * @mbg.generated
     */
    public Date getDataRilevazione() {
        return dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.data_rilevazione
     *
     * @param dataRilevazione the value for covidrsa_t_decessi.data_rilevazione
     *
     * @mbg.generated
     */
    public void setDataRilevazione(Date dataRilevazione) {
        this.dataRilevazione = dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.validita_inizio
     *
     * @return the value of covidrsa_t_decessi.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_t_decessi.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.validita_fine
     *
     * @return the value of covidrsa_t_decessi.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.validita_fine
     *
     * @param validitaFine the value for covidrsa_t_decessi.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.utente_operazione
     *
     * @return the value of covidrsa_t_decessi.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_t_decessi.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.data_creazione
     *
     * @return the value of covidrsa_t_decessi.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.data_creazione
     *
     * @param dataCreazione the value for covidrsa_t_decessi.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.data_modifica
     *
     * @return the value of covidrsa_t_decessi.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.data_modifica
     *
     * @param dataModifica the value for covidrsa_t_decessi.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.data_cancellazione
     *
     * @return the value of covidrsa_t_decessi.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_t_decessi.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.data_visibilita
     *
     * @return the value of covidrsa_t_decessi.data_visibilita
     *
     * @mbg.generated
     */
    public Date getDataVisibilita() {
        return dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.data_visibilita
     *
     * @param dataVisibilita the value for covidrsa_t_decessi.data_visibilita
     *
     * @mbg.generated
     */
    public void setDataVisibilita(Date dataVisibilita) {
        this.dataVisibilita = dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_anno_precedente
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_ospedale_anno_precedente
     *
     * @mbg.generated
     */
    public Integer getDecNumInOspedaleAnnoPrecedente() {
        return decNumInOspedaleAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_anno_precedente
     *
     * @param decNumInOspedaleAnnoPrecedente the value for covidrsa_t_decessi.dec_num_in_ospedale_anno_precedente
     *
     * @mbg.generated
     */
    public void setDecNumInOspedaleAnnoPrecedente(Integer decNumInOspedaleAnnoPrecedente) {
        this.decNumInOspedaleAnnoPrecedente = decNumInOspedaleAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_struttura_anno_precedente
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_struttura_anno_precedente
     *
     * @mbg.generated
     */
    public Integer getDecNumInStrutturaAnnoPrecedente() {
        return decNumInStrutturaAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_struttura_anno_precedente
     *
     * @param decNumInStrutturaAnnoPrecedente the value for covidrsa_t_decessi.dec_num_in_struttura_anno_precedente
     *
     * @mbg.generated
     */
    public void setDecNumInStrutturaAnnoPrecedente(Integer decNumInStrutturaAnnoPrecedente) {
        this.decNumInStrutturaAnnoPrecedente = decNumInStrutturaAnnoPrecedente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_struttura
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_struttura
     *
     * @mbg.generated
     */
    public Integer getDecNumInStruttura() {
        return decNumInStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_struttura
     *
     * @param decNumInStruttura the value for covidrsa_t_decessi.dec_num_in_struttura
     *
     * @mbg.generated
     */
    public void setDecNumInStruttura(Integer decNumInStruttura) {
        this.decNumInStruttura = decNumInStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_struttura_covid
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_struttura_covid
     *
     * @mbg.generated
     */
    public Integer getDecNumInStrutturaCovid() {
        return decNumInStrutturaCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_struttura_covid
     *
     * @param decNumInStrutturaCovid the value for covidrsa_t_decessi.dec_num_in_struttura_covid
     *
     * @mbg.generated
     */
    public void setDecNumInStrutturaCovid(Integer decNumInStrutturaCovid) {
        this.decNumInStrutturaCovid = decNumInStrutturaCovid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumUltimaSettimana() {
        return decNumUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_ultima_settimana
     *
     * @param decNumUltimaSettimana the value for covidrsa_t_decessi.dec_num_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumUltimaSettimana(Integer decNumUltimaSettimana) {
        this.decNumUltimaSettimana = decNumUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_covid_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumCovidUltimaSettimana() {
        return decNumCovidUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_covid_ultima_settimana
     *
     * @param decNumCovidUltimaSettimana the value for covidrsa_t_decessi.dec_num_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumCovidUltimaSettimana(Integer decNumCovidUltimaSettimana) {
        this.decNumCovidUltimaSettimana = decNumCovidUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_struttura_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_struttura_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumInStrutturaUltimaSettimana() {
        return decNumInStrutturaUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_struttura_ultima_settimana
     *
     * @param decNumInStrutturaUltimaSettimana the value for covidrsa_t_decessi.dec_num_in_struttura_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumInStrutturaUltimaSettimana(Integer decNumInStrutturaUltimaSettimana) {
        this.decNumInStrutturaUltimaSettimana = decNumInStrutturaUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_struttura_covid_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_struttura_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumInStrutturaCovidUltimaSettimana() {
        return decNumInStrutturaCovidUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_struttura_covid_ultima_settimana
     *
     * @param decNumInStrutturaCovidUltimaSettimana the value for covidrsa_t_decessi.dec_num_in_struttura_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumInStrutturaCovidUltimaSettimana(Integer decNumInStrutturaCovidUltimaSettimana) {
        this.decNumInStrutturaCovidUltimaSettimana = decNumInStrutturaCovidUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_ospedale_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumInOspedaleUltimaSettimana() {
        return decNumInOspedaleUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_ultima_settimana
     *
     * @param decNumInOspedaleUltimaSettimana the value for covidrsa_t_decessi.dec_num_in_ospedale_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumInOspedaleUltimaSettimana(Integer decNumInOspedaleUltimaSettimana) {
        this.decNumInOspedaleUltimaSettimana = decNumInOspedaleUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_covid_ultima_settimana
     *
     * @return the value of covidrsa_t_decessi.dec_num_in_ospedale_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public Integer getDecNumInOspedaleCovidUltimaSettimana() {
        return decNumInOspedaleCovidUltimaSettimana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_decessi.dec_num_in_ospedale_covid_ultima_settimana
     *
     * @param decNumInOspedaleCovidUltimaSettimana the value for covidrsa_t_decessi.dec_num_in_ospedale_covid_ultima_settimana
     *
     * @mbg.generated
     */
    public void setDecNumInOspedaleCovidUltimaSettimana(Integer decNumInOspedaleCovidUltimaSettimana) {
        this.decNumInOspedaleCovidUltimaSettimana = decNumInOspedaleCovidUltimaSettimana;
    }
}