/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class RsaPosti extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_id
     *
     * @mbg.generated
     */
    private Integer postiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_totali
     *
     * @mbg.generated
     */
    private Integer postiNumTotali;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_ospedalizzati
     *
     * @mbg.generated
     */
    private Integer postiNumOspedalizzati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_totali_singole
     *
     * @mbg.generated
     */
    private Integer postiNumTotaliSingole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_singole_residue
     *
     * @mbg.generated
     */
    private Integer postiNumSingoleResidue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.id_struttura
     *
     * @mbg.generated
     */
    private String idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.str_categoria_id
     *
     * @mbg.generated
     */
    private Integer strCategoriaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.data_rilevazione
     *
     * @mbg.generated
     */
    private Date dataRilevazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.data_visibilita
     *
     * @mbg.generated
     */
    private Date dataVisibilita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.accessi_in_ps_num
     *
     * @mbg.generated
     */
    private Integer accessiInPsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_paganti
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiPaganti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_convenzionati
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiConvenzionati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_dgr23
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiDgr23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupabili_dgr10
     *
     * @mbg.generated
     */
    private Integer postiNumOccupabiliDgr10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_dgr_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiDgrUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_dgr_donne
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiDgrDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupabili_dgr_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumOccupabiliDgrUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupabili_dgr_donne
     *
     * @mbg.generated
     */
    private Integer postiNumOccupabiliDgrDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_occupati_paganti_ss
     *
     * @mbg.generated
     */
    private Integer postiNumOccupatiPagantiSs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_sollievo_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumSollievoOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_sollievo_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumSollievoLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_sollievo_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumSollievoLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_sollievo_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumSollievoLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_sollievo_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumSollievoLiberiIndiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_dim_prot_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumDimProtOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_dim_prot_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumDimProtLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_dim_prot_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumDimProtLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_dim_prot_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumDimProtLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_dim_prot_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumDimProtLiberiIndiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_cavs_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumCavsOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_cavs_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumCavsLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_cavs_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumCavsLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_cavs_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumCavsLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_cavs_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumCavsLiberiIndiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_lungodeg_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumLungodegOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_lungodeg_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumLungodegLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_lungodeg_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumLungodegLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_lungodeg_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumLungodegLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_lungodeg_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumLungodegLiberiIndiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_hospice_occupati
     *
     * @mbg.generated
     */
    private Integer postiNumHospiceOccupati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_hospice_liberi
     *
     * @mbg.generated
     */
    private Integer postiNumHospiceLiberi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_hospice_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumHospiceLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_hospice_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumHospiceLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_hospice_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumHospiceLiberiIndiff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_liberi_uomini
     *
     * @mbg.generated
     */
    private Integer postiNumLiberiUomini;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_liberi_donne
     *
     * @mbg.generated
     */
    private Integer postiNumLiberiDonne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_posti.posti_num_liberi_indiff
     *
     * @mbg.generated
     */
    private Integer postiNumLiberiIndiff;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_id
     *
     * @return the value of covidrsa_t_posti.posti_id
     *
     * @mbg.generated
     */
    public Integer getPostiId() {
        return postiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_id
     *
     * @param postiId the value for covidrsa_t_posti.posti_id
     *
     * @mbg.generated
     */
    public void setPostiId(Integer postiId) {
        this.postiId = postiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_totali
     *
     * @return the value of covidrsa_t_posti.posti_num_totali
     *
     * @mbg.generated
     */
    public Integer getPostiNumTotali() {
        return postiNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_totali
     *
     * @param postiNumTotali the value for covidrsa_t_posti.posti_num_totali
     *
     * @mbg.generated
     */
    public void setPostiNumTotali(Integer postiNumTotali) {
        this.postiNumTotali = postiNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupati() {
        return postiNumOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati
     *
     * @param postiNumOccupati the value for covidrsa_t_posti.posti_num_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumOccupati(Integer postiNumOccupati) {
        this.postiNumOccupati = postiNumOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_ospedalizzati
     *
     * @return the value of covidrsa_t_posti.posti_num_ospedalizzati
     *
     * @mbg.generated
     */
    public Integer getPostiNumOspedalizzati() {
        return postiNumOspedalizzati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_ospedalizzati
     *
     * @param postiNumOspedalizzati the value for covidrsa_t_posti.posti_num_ospedalizzati
     *
     * @mbg.generated
     */
    public void setPostiNumOspedalizzati(Integer postiNumOspedalizzati) {
        this.postiNumOspedalizzati = postiNumOspedalizzati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_totali_singole
     *
     * @return the value of covidrsa_t_posti.posti_num_totali_singole
     *
     * @mbg.generated
     */
    public Integer getPostiNumTotaliSingole() {
        return postiNumTotaliSingole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_totali_singole
     *
     * @param postiNumTotaliSingole the value for covidrsa_t_posti.posti_num_totali_singole
     *
     * @mbg.generated
     */
    public void setPostiNumTotaliSingole(Integer postiNumTotaliSingole) {
        this.postiNumTotaliSingole = postiNumTotaliSingole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_singole_residue
     *
     * @return the value of covidrsa_t_posti.posti_num_singole_residue
     *
     * @mbg.generated
     */
    public Integer getPostiNumSingoleResidue() {
        return postiNumSingoleResidue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_singole_residue
     *
     * @param postiNumSingoleResidue the value for covidrsa_t_posti.posti_num_singole_residue
     *
     * @mbg.generated
     */
    public void setPostiNumSingoleResidue(Integer postiNumSingoleResidue) {
        this.postiNumSingoleResidue = postiNumSingoleResidue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.id_struttura
     *
     * @return the value of covidrsa_t_posti.id_struttura
     *
     * @mbg.generated
     */
    public String getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.id_struttura
     *
     * @param idStruttura the value for covidrsa_t_posti.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(String idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.str_categoria_id
     *
     * @return the value of covidrsa_t_posti.str_categoria_id
     *
     * @mbg.generated
     */
    public Integer getStrCategoriaId() {
        return strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.str_categoria_id
     *
     * @param strCategoriaId the value for covidrsa_t_posti.str_categoria_id
     *
     * @mbg.generated
     */
    public void setStrCategoriaId(Integer strCategoriaId) {
        this.strCategoriaId = strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.data_rilevazione
     *
     * @return the value of covidrsa_t_posti.data_rilevazione
     *
     * @mbg.generated
     */
    public Date getDataRilevazione() {
        return dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.data_rilevazione
     *
     * @param dataRilevazione the value for covidrsa_t_posti.data_rilevazione
     *
     * @mbg.generated
     */
    public void setDataRilevazione(Date dataRilevazione) {
        this.dataRilevazione = dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.validita_inizio
     *
     * @return the value of covidrsa_t_posti.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_t_posti.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.validita_fine
     *
     * @return the value of covidrsa_t_posti.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.validita_fine
     *
     * @param validitaFine the value for covidrsa_t_posti.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.utente_operazione
     *
     * @return the value of covidrsa_t_posti.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_t_posti.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.data_creazione
     *
     * @return the value of covidrsa_t_posti.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.data_creazione
     *
     * @param dataCreazione the value for covidrsa_t_posti.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.data_modifica
     *
     * @return the value of covidrsa_t_posti.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.data_modifica
     *
     * @param dataModifica the value for covidrsa_t_posti.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.data_cancellazione
     *
     * @return the value of covidrsa_t_posti.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_t_posti.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.data_visibilita
     *
     * @return the value of covidrsa_t_posti.data_visibilita
     *
     * @mbg.generated
     */
    public Date getDataVisibilita() {
        return dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.data_visibilita
     *
     * @param dataVisibilita the value for covidrsa_t_posti.data_visibilita
     *
     * @mbg.generated
     */
    public void setDataVisibilita(Date dataVisibilita) {
        this.dataVisibilita = dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.accessi_in_ps_num
     *
     * @return the value of covidrsa_t_posti.accessi_in_ps_num
     *
     * @mbg.generated
     */
    public Integer getAccessiInPsNum() {
        return accessiInPsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.accessi_in_ps_num
     *
     * @param accessiInPsNum the value for covidrsa_t_posti.accessi_in_ps_num
     *
     * @mbg.generated
     */
    public void setAccessiInPsNum(Integer accessiInPsNum) {
        this.accessiInPsNum = accessiInPsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_paganti
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_paganti
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiPaganti() {
        return postiNumOccupatiPaganti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_paganti
     *
     * @param postiNumOccupatiPaganti the value for covidrsa_t_posti.posti_num_occupati_paganti
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiPaganti(Integer postiNumOccupatiPaganti) {
        this.postiNumOccupatiPaganti = postiNumOccupatiPaganti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_convenzionati
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_convenzionati
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiConvenzionati() {
        return postiNumOccupatiConvenzionati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_convenzionati
     *
     * @param postiNumOccupatiConvenzionati the value for covidrsa_t_posti.posti_num_occupati_convenzionati
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiConvenzionati(Integer postiNumOccupatiConvenzionati) {
        this.postiNumOccupatiConvenzionati = postiNumOccupatiConvenzionati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_dgr23
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_dgr23
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiDgr23() {
        return postiNumOccupatiDgr23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_dgr23
     *
     * @param postiNumOccupatiDgr23 the value for covidrsa_t_posti.posti_num_occupati_dgr23
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiDgr23(Integer postiNumOccupatiDgr23) {
        this.postiNumOccupatiDgr23 = postiNumOccupatiDgr23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr10
     *
     * @return the value of covidrsa_t_posti.posti_num_occupabili_dgr10
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupabiliDgr10() {
        return postiNumOccupabiliDgr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr10
     *
     * @param postiNumOccupabiliDgr10 the value for covidrsa_t_posti.posti_num_occupabili_dgr10
     *
     * @mbg.generated
     */
    public void setPostiNumOccupabiliDgr10(Integer postiNumOccupabiliDgr10) {
        this.postiNumOccupabiliDgr10 = postiNumOccupabiliDgr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_dgr_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_dgr_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiDgrUomini() {
        return postiNumOccupatiDgrUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_dgr_uomini
     *
     * @param postiNumOccupatiDgrUomini the value for covidrsa_t_posti.posti_num_occupati_dgr_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiDgrUomini(Integer postiNumOccupatiDgrUomini) {
        this.postiNumOccupatiDgrUomini = postiNumOccupatiDgrUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_dgr_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_dgr_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiDgrDonne() {
        return postiNumOccupatiDgrDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_dgr_donne
     *
     * @param postiNumOccupatiDgrDonne the value for covidrsa_t_posti.posti_num_occupati_dgr_donne
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiDgrDonne(Integer postiNumOccupatiDgrDonne) {
        this.postiNumOccupatiDgrDonne = postiNumOccupatiDgrDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_occupabili_dgr_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupabiliDgrUomini() {
        return postiNumOccupabiliDgrUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr_uomini
     *
     * @param postiNumOccupabiliDgrUomini the value for covidrsa_t_posti.posti_num_occupabili_dgr_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumOccupabiliDgrUomini(Integer postiNumOccupabiliDgrUomini) {
        this.postiNumOccupabiliDgrUomini = postiNumOccupabiliDgrUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_occupabili_dgr_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupabiliDgrDonne() {
        return postiNumOccupabiliDgrDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupabili_dgr_donne
     *
     * @param postiNumOccupabiliDgrDonne the value for covidrsa_t_posti.posti_num_occupabili_dgr_donne
     *
     * @mbg.generated
     */
    public void setPostiNumOccupabiliDgrDonne(Integer postiNumOccupabiliDgrDonne) {
        this.postiNumOccupabiliDgrDonne = postiNumOccupabiliDgrDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumLiberi() {
        return postiNumLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_liberi
     *
     * @param postiNumLiberi the value for covidrsa_t_posti.posti_num_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumLiberi(Integer postiNumLiberi) {
        this.postiNumLiberi = postiNumLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_occupati_paganti_ss
     *
     * @return the value of covidrsa_t_posti.posti_num_occupati_paganti_ss
     *
     * @mbg.generated
     */
    public Integer getPostiNumOccupatiPagantiSs() {
        return postiNumOccupatiPagantiSs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_occupati_paganti_ss
     *
     * @param postiNumOccupatiPagantiSs the value for covidrsa_t_posti.posti_num_occupati_paganti_ss
     *
     * @mbg.generated
     */
    public void setPostiNumOccupatiPagantiSs(Integer postiNumOccupatiPagantiSs) {
        this.postiNumOccupatiPagantiSs = postiNumOccupatiPagantiSs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_sollievo_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_sollievo_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumSollievoOccupati() {
        return postiNumSollievoOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_sollievo_occupati
     *
     * @param postiNumSollievoOccupati the value for covidrsa_t_posti.posti_num_sollievo_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumSollievoOccupati(Integer postiNumSollievoOccupati) {
        this.postiNumSollievoOccupati = postiNumSollievoOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_sollievo_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumSollievoLiberi() {
        return postiNumSollievoLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi
     *
     * @param postiNumSollievoLiberi the value for covidrsa_t_posti.posti_num_sollievo_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumSollievoLiberi(Integer postiNumSollievoLiberi) {
        this.postiNumSollievoLiberi = postiNumSollievoLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_sollievo_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumSollievoLiberiUomini() {
        return postiNumSollievoLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_uomini
     *
     * @param postiNumSollievoLiberiUomini the value for covidrsa_t_posti.posti_num_sollievo_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumSollievoLiberiUomini(Integer postiNumSollievoLiberiUomini) {
        this.postiNumSollievoLiberiUomini = postiNumSollievoLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_sollievo_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumSollievoLiberiDonne() {
        return postiNumSollievoLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_donne
     *
     * @param postiNumSollievoLiberiDonne the value for covidrsa_t_posti.posti_num_sollievo_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumSollievoLiberiDonne(Integer postiNumSollievoLiberiDonne) {
        this.postiNumSollievoLiberiDonne = postiNumSollievoLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_sollievo_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumSollievoLiberiIndiff() {
        return postiNumSollievoLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_sollievo_liberi_indiff
     *
     * @param postiNumSollievoLiberiIndiff the value for covidrsa_t_posti.posti_num_sollievo_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumSollievoLiberiIndiff(Integer postiNumSollievoLiberiIndiff) {
        this.postiNumSollievoLiberiIndiff = postiNumSollievoLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_dim_prot_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_dim_prot_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumDimProtOccupati() {
        return postiNumDimProtOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_dim_prot_occupati
     *
     * @param postiNumDimProtOccupati the value for covidrsa_t_posti.posti_num_dim_prot_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumDimProtOccupati(Integer postiNumDimProtOccupati) {
        this.postiNumDimProtOccupati = postiNumDimProtOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_dim_prot_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumDimProtLiberi() {
        return postiNumDimProtLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi
     *
     * @param postiNumDimProtLiberi the value for covidrsa_t_posti.posti_num_dim_prot_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumDimProtLiberi(Integer postiNumDimProtLiberi) {
        this.postiNumDimProtLiberi = postiNumDimProtLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_dim_prot_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumDimProtLiberiUomini() {
        return postiNumDimProtLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_uomini
     *
     * @param postiNumDimProtLiberiUomini the value for covidrsa_t_posti.posti_num_dim_prot_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumDimProtLiberiUomini(Integer postiNumDimProtLiberiUomini) {
        this.postiNumDimProtLiberiUomini = postiNumDimProtLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_dim_prot_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumDimProtLiberiDonne() {
        return postiNumDimProtLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_donne
     *
     * @param postiNumDimProtLiberiDonne the value for covidrsa_t_posti.posti_num_dim_prot_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumDimProtLiberiDonne(Integer postiNumDimProtLiberiDonne) {
        this.postiNumDimProtLiberiDonne = postiNumDimProtLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_dim_prot_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumDimProtLiberiIndiff() {
        return postiNumDimProtLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_dim_prot_liberi_indiff
     *
     * @param postiNumDimProtLiberiIndiff the value for covidrsa_t_posti.posti_num_dim_prot_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumDimProtLiberiIndiff(Integer postiNumDimProtLiberiIndiff) {
        this.postiNumDimProtLiberiIndiff = postiNumDimProtLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_cavs_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_cavs_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumCavsOccupati() {
        return postiNumCavsOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_cavs_occupati
     *
     * @param postiNumCavsOccupati the value for covidrsa_t_posti.posti_num_cavs_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumCavsOccupati(Integer postiNumCavsOccupati) {
        this.postiNumCavsOccupati = postiNumCavsOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_cavs_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_cavs_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumCavsLiberi() {
        return postiNumCavsLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_cavs_liberi
     *
     * @param postiNumCavsLiberi the value for covidrsa_t_posti.posti_num_cavs_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumCavsLiberi(Integer postiNumCavsLiberi) {
        this.postiNumCavsLiberi = postiNumCavsLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_cavs_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumCavsLiberiUomini() {
        return postiNumCavsLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_uomini
     *
     * @param postiNumCavsLiberiUomini the value for covidrsa_t_posti.posti_num_cavs_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumCavsLiberiUomini(Integer postiNumCavsLiberiUomini) {
        this.postiNumCavsLiberiUomini = postiNumCavsLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_cavs_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumCavsLiberiDonne() {
        return postiNumCavsLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_donne
     *
     * @param postiNumCavsLiberiDonne the value for covidrsa_t_posti.posti_num_cavs_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumCavsLiberiDonne(Integer postiNumCavsLiberiDonne) {
        this.postiNumCavsLiberiDonne = postiNumCavsLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_cavs_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumCavsLiberiIndiff() {
        return postiNumCavsLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_cavs_liberi_indiff
     *
     * @param postiNumCavsLiberiIndiff the value for covidrsa_t_posti.posti_num_cavs_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumCavsLiberiIndiff(Integer postiNumCavsLiberiIndiff) {
        this.postiNumCavsLiberiIndiff = postiNumCavsLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_lungodeg_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_lungodeg_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumLungodegOccupati() {
        return postiNumLungodegOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_lungodeg_occupati
     *
     * @param postiNumLungodegOccupati the value for covidrsa_t_posti.posti_num_lungodeg_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumLungodegOccupati(Integer postiNumLungodegOccupati) {
        this.postiNumLungodegOccupati = postiNumLungodegOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_lungodeg_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumLungodegLiberi() {
        return postiNumLungodegLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi
     *
     * @param postiNumLungodegLiberi the value for covidrsa_t_posti.posti_num_lungodeg_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumLungodegLiberi(Integer postiNumLungodegLiberi) {
        this.postiNumLungodegLiberi = postiNumLungodegLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_lungodeg_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumLungodegLiberiUomini() {
        return postiNumLungodegLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_uomini
     *
     * @param postiNumLungodegLiberiUomini the value for covidrsa_t_posti.posti_num_lungodeg_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumLungodegLiberiUomini(Integer postiNumLungodegLiberiUomini) {
        this.postiNumLungodegLiberiUomini = postiNumLungodegLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_lungodeg_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumLungodegLiberiDonne() {
        return postiNumLungodegLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_donne
     *
     * @param postiNumLungodegLiberiDonne the value for covidrsa_t_posti.posti_num_lungodeg_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumLungodegLiberiDonne(Integer postiNumLungodegLiberiDonne) {
        this.postiNumLungodegLiberiDonne = postiNumLungodegLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_lungodeg_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumLungodegLiberiIndiff() {
        return postiNumLungodegLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_lungodeg_liberi_indiff
     *
     * @param postiNumLungodegLiberiIndiff the value for covidrsa_t_posti.posti_num_lungodeg_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumLungodegLiberiIndiff(Integer postiNumLungodegLiberiIndiff) {
        this.postiNumLungodegLiberiIndiff = postiNumLungodegLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_hospice_occupati
     *
     * @return the value of covidrsa_t_posti.posti_num_hospice_occupati
     *
     * @mbg.generated
     */
    public Integer getPostiNumHospiceOccupati() {
        return postiNumHospiceOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_hospice_occupati
     *
     * @param postiNumHospiceOccupati the value for covidrsa_t_posti.posti_num_hospice_occupati
     *
     * @mbg.generated
     */
    public void setPostiNumHospiceOccupati(Integer postiNumHospiceOccupati) {
        this.postiNumHospiceOccupati = postiNumHospiceOccupati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_hospice_liberi
     *
     * @return the value of covidrsa_t_posti.posti_num_hospice_liberi
     *
     * @mbg.generated
     */
    public Integer getPostiNumHospiceLiberi() {
        return postiNumHospiceLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_hospice_liberi
     *
     * @param postiNumHospiceLiberi the value for covidrsa_t_posti.posti_num_hospice_liberi
     *
     * @mbg.generated
     */
    public void setPostiNumHospiceLiberi(Integer postiNumHospiceLiberi) {
        this.postiNumHospiceLiberi = postiNumHospiceLiberi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_hospice_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumHospiceLiberiUomini() {
        return postiNumHospiceLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_uomini
     *
     * @param postiNumHospiceLiberiUomini the value for covidrsa_t_posti.posti_num_hospice_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumHospiceLiberiUomini(Integer postiNumHospiceLiberiUomini) {
        this.postiNumHospiceLiberiUomini = postiNumHospiceLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_hospice_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumHospiceLiberiDonne() {
        return postiNumHospiceLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_donne
     *
     * @param postiNumHospiceLiberiDonne the value for covidrsa_t_posti.posti_num_hospice_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumHospiceLiberiDonne(Integer postiNumHospiceLiberiDonne) {
        this.postiNumHospiceLiberiDonne = postiNumHospiceLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_hospice_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumHospiceLiberiIndiff() {
        return postiNumHospiceLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_hospice_liberi_indiff
     *
     * @param postiNumHospiceLiberiIndiff the value for covidrsa_t_posti.posti_num_hospice_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumHospiceLiberiIndiff(Integer postiNumHospiceLiberiIndiff) {
        this.postiNumHospiceLiberiIndiff = postiNumHospiceLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_liberi_uomini
     *
     * @return the value of covidrsa_t_posti.posti_num_liberi_uomini
     *
     * @mbg.generated
     */
    public Integer getPostiNumLiberiUomini() {
        return postiNumLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_liberi_uomini
     *
     * @param postiNumLiberiUomini the value for covidrsa_t_posti.posti_num_liberi_uomini
     *
     * @mbg.generated
     */
    public void setPostiNumLiberiUomini(Integer postiNumLiberiUomini) {
        this.postiNumLiberiUomini = postiNumLiberiUomini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_liberi_donne
     *
     * @return the value of covidrsa_t_posti.posti_num_liberi_donne
     *
     * @mbg.generated
     */
    public Integer getPostiNumLiberiDonne() {
        return postiNumLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_liberi_donne
     *
     * @param postiNumLiberiDonne the value for covidrsa_t_posti.posti_num_liberi_donne
     *
     * @mbg.generated
     */
    public void setPostiNumLiberiDonne(Integer postiNumLiberiDonne) {
        this.postiNumLiberiDonne = postiNumLiberiDonne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_posti.posti_num_liberi_indiff
     *
     * @return the value of covidrsa_t_posti.posti_num_liberi_indiff
     *
     * @mbg.generated
     */
    public Integer getPostiNumLiberiIndiff() {
        return postiNumLiberiIndiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_posti.posti_num_liberi_indiff
     *
     * @param postiNumLiberiIndiff the value for covidrsa_t_posti.posti_num_liberi_indiff
     *
     * @mbg.generated
     */
    public void setPostiNumLiberiIndiff(Integer postiNumLiberiIndiff) {
        this.postiNumLiberiIndiff = postiNumLiberiIndiff;
    }
}