/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class RsaStrutturaNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.stn_id
     *
     * @mbg.generated
     */
	@JsonIgnore
    private Integer stnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.stn_note
     *
     * @mbg.generated
     */
	@JsonProperty("Nota")
    private String stnNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.id_struttura
     *
     * @mbg.generated
     */
    @JsonIgnore
    private String idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.str_categoria_id
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Integer strCategoriaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.data_rilevazione
     *
     * @mbg.generated
     */
    @JsonProperty("Data nota")
    private Date dataRilevazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.validita_inizio
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.validita_fine
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.utente_operazione
     *
     * @mbg.generated
     */
    @JsonIgnore
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.data_creazione
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.data_modifica
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.data_cancellazione
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_note.data_visibilita
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Date dataVisibilita;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.stn_id
     *
     * @return the value of covidrsa_t_struttura_note.stn_id
     *
     * @mbg.generated
     */
    public Integer getStnId() {
        return stnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.stn_id
     *
     * @param stnId the value for covidrsa_t_struttura_note.stn_id
     *
     * @mbg.generated
     */
    public void setStnId(Integer stnId) {
        this.stnId = stnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.stn_note
     *
     * @return the value of covidrsa_t_struttura_note.stn_note
     *
     * @mbg.generated
     */
    public String getStnNote() {
        return stnNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.stn_note
     *
     * @param stnNote the value for covidrsa_t_struttura_note.stn_note
     *
     * @mbg.generated
     */
    public void setStnNote(String stnNote) {
        this.stnNote = stnNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.id_struttura
     *
     * @return the value of covidrsa_t_struttura_note.id_struttura
     *
     * @mbg.generated
     */
    public String getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.id_struttura
     *
     * @param idStruttura the value for covidrsa_t_struttura_note.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(String idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.str_categoria_id
     *
     * @return the value of covidrsa_t_struttura_note.str_categoria_id
     *
     * @mbg.generated
     */
    public Integer getStrCategoriaId() {
        return strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.str_categoria_id
     *
     * @param strCategoriaId the value for covidrsa_t_struttura_note.str_categoria_id
     *
     * @mbg.generated
     */
    public void setStrCategoriaId(Integer strCategoriaId) {
        this.strCategoriaId = strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.data_rilevazione
     *
     * @return the value of covidrsa_t_struttura_note.data_rilevazione
     *
     * @mbg.generated
     */
    public Date getDataRilevazione() {
        return dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.data_rilevazione
     *
     * @param dataRilevazione the value for covidrsa_t_struttura_note.data_rilevazione
     *
     * @mbg.generated
     */
    public void setDataRilevazione(Date dataRilevazione) {
        this.dataRilevazione = dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.validita_inizio
     *
     * @return the value of covidrsa_t_struttura_note.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_t_struttura_note.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.validita_fine
     *
     * @return the value of covidrsa_t_struttura_note.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.validita_fine
     *
     * @param validitaFine the value for covidrsa_t_struttura_note.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.utente_operazione
     *
     * @return the value of covidrsa_t_struttura_note.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_t_struttura_note.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.data_creazione
     *
     * @return the value of covidrsa_t_struttura_note.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.data_creazione
     *
     * @param dataCreazione the value for covidrsa_t_struttura_note.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.data_modifica
     *
     * @return the value of covidrsa_t_struttura_note.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.data_modifica
     *
     * @param dataModifica the value for covidrsa_t_struttura_note.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.data_cancellazione
     *
     * @return the value of covidrsa_t_struttura_note.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_t_struttura_note.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_struttura_note.data_visibilita
     *
     * @return the value of covidrsa_t_struttura_note.data_visibilita
     *
     * @mbg.generated
     */
    public Date getDataVisibilita() {
        return dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_struttura_note.data_visibilita
     *
     * @param dataVisibilita the value for covidrsa_t_struttura_note.data_visibilita
     *
     * @mbg.generated
     */
    public void setDataVisibilita(Date dataVisibilita) {
        this.dataVisibilita = dataVisibilita;
    }
}