/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class RsaTamponi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_id
     *
     * @mbg.generated
     */
    private Integer tampId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_totali
     *
     * @mbg.generated
     */
    private Integer tampNumTotali;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_positivi
     *
     * @mbg.generated
     */
    private Integer tampNumPositivi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_negativi
     *
     * @mbg.generated
     */
    private Integer tampNumNegativi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_in_attesa
     *
     * @mbg.generated
     */
    private Integer tampNumInAttesa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_indeterminati
     *
     * @mbg.generated
     */
    private Integer tampNumIndeterminati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_num_dubbi
     *
     * @mbg.generated
     */
    private Integer tampNumDubbi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.tamp_cat_id
     *
     * @mbg.generated
     */
    private Integer tampCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.id_struttura
     *
     * @mbg.generated
     */
    private String idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.str_categoria_id
     *
     * @mbg.generated
     */
    private Integer strCategoriaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.data_rilevazione
     *
     * @mbg.generated
     */
    private Date dataRilevazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.data_visibilita
     *
     * @mbg.generated
     */
    private Date dataVisibilita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_tamponi.str_tipo_tampone_id
     *
     * @mbg.generated
     */
    private Integer strTipoTamponeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_id
     *
     * @return the value of covidrsa_t_tamponi.tamp_id
     *
     * @mbg.generated
     */
    public Integer getTampId() {
        return tampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_id
     *
     * @param tampId the value for covidrsa_t_tamponi.tamp_id
     *
     * @mbg.generated
     */
    public void setTampId(Integer tampId) {
        this.tampId = tampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_totali
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_totali
     *
     * @mbg.generated
     */
    public Integer getTampNumTotali() {
        return tampNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_totali
     *
     * @param tampNumTotali the value for covidrsa_t_tamponi.tamp_num_totali
     *
     * @mbg.generated
     */
    public void setTampNumTotali(Integer tampNumTotali) {
        this.tampNumTotali = tampNumTotali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_positivi
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_positivi
     *
     * @mbg.generated
     */
    public Integer getTampNumPositivi() {
        return tampNumPositivi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_positivi
     *
     * @param tampNumPositivi the value for covidrsa_t_tamponi.tamp_num_positivi
     *
     * @mbg.generated
     */
    public void setTampNumPositivi(Integer tampNumPositivi) {
        this.tampNumPositivi = tampNumPositivi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_negativi
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_negativi
     *
     * @mbg.generated
     */
    public Integer getTampNumNegativi() {
        return tampNumNegativi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_negativi
     *
     * @param tampNumNegativi the value for covidrsa_t_tamponi.tamp_num_negativi
     *
     * @mbg.generated
     */
    public void setTampNumNegativi(Integer tampNumNegativi) {
        this.tampNumNegativi = tampNumNegativi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_in_attesa
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_in_attesa
     *
     * @mbg.generated
     */
    public Integer getTampNumInAttesa() {
        return tampNumInAttesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_in_attesa
     *
     * @param tampNumInAttesa the value for covidrsa_t_tamponi.tamp_num_in_attesa
     *
     * @mbg.generated
     */
    public void setTampNumInAttesa(Integer tampNumInAttesa) {
        this.tampNumInAttesa = tampNumInAttesa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_indeterminati
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_indeterminati
     *
     * @mbg.generated
     */
    public Integer getTampNumIndeterminati() {
        return tampNumIndeterminati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_indeterminati
     *
     * @param tampNumIndeterminati the value for covidrsa_t_tamponi.tamp_num_indeterminati
     *
     * @mbg.generated
     */
    public void setTampNumIndeterminati(Integer tampNumIndeterminati) {
        this.tampNumIndeterminati = tampNumIndeterminati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_num_dubbi
     *
     * @return the value of covidrsa_t_tamponi.tamp_num_dubbi
     *
     * @mbg.generated
     */
    public Integer getTampNumDubbi() {
        return tampNumDubbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_num_dubbi
     *
     * @param tampNumDubbi the value for covidrsa_t_tamponi.tamp_num_dubbi
     *
     * @mbg.generated
     */
    public void setTampNumDubbi(Integer tampNumDubbi) {
        this.tampNumDubbi = tampNumDubbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.tamp_cat_id
     *
     * @return the value of covidrsa_t_tamponi.tamp_cat_id
     *
     * @mbg.generated
     */
    public Integer getTampCatId() {
        return tampCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.tamp_cat_id
     *
     * @param tampCatId the value for covidrsa_t_tamponi.tamp_cat_id
     *
     * @mbg.generated
     */
    public void setTampCatId(Integer tampCatId) {
        this.tampCatId = tampCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.id_struttura
     *
     * @return the value of covidrsa_t_tamponi.id_struttura
     *
     * @mbg.generated
     */
    public String getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.id_struttura
     *
     * @param idStruttura the value for covidrsa_t_tamponi.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(String idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.str_categoria_id
     *
     * @return the value of covidrsa_t_tamponi.str_categoria_id
     *
     * @mbg.generated
     */
    public Integer getStrCategoriaId() {
        return strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.str_categoria_id
     *
     * @param strCategoriaId the value for covidrsa_t_tamponi.str_categoria_id
     *
     * @mbg.generated
     */
    public void setStrCategoriaId(Integer strCategoriaId) {
        this.strCategoriaId = strCategoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.data_rilevazione
     *
     * @return the value of covidrsa_t_tamponi.data_rilevazione
     *
     * @mbg.generated
     */
    public Date getDataRilevazione() {
        return dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.data_rilevazione
     *
     * @param dataRilevazione the value for covidrsa_t_tamponi.data_rilevazione
     *
     * @mbg.generated
     */
    public void setDataRilevazione(Date dataRilevazione) {
        this.dataRilevazione = dataRilevazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.validita_inizio
     *
     * @return the value of covidrsa_t_tamponi.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_t_tamponi.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.validita_fine
     *
     * @return the value of covidrsa_t_tamponi.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.validita_fine
     *
     * @param validitaFine the value for covidrsa_t_tamponi.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.utente_operazione
     *
     * @return the value of covidrsa_t_tamponi.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_t_tamponi.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.data_creazione
     *
     * @return the value of covidrsa_t_tamponi.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.data_creazione
     *
     * @param dataCreazione the value for covidrsa_t_tamponi.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.data_modifica
     *
     * @return the value of covidrsa_t_tamponi.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.data_modifica
     *
     * @param dataModifica the value for covidrsa_t_tamponi.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.data_cancellazione
     *
     * @return the value of covidrsa_t_tamponi.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_t_tamponi.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.data_visibilita
     *
     * @return the value of covidrsa_t_tamponi.data_visibilita
     *
     * @mbg.generated
     */
    public Date getDataVisibilita() {
        return dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.data_visibilita
     *
     * @param dataVisibilita the value for covidrsa_t_tamponi.data_visibilita
     *
     * @mbg.generated
     */
    public void setDataVisibilita(Date dataVisibilita) {
        this.dataVisibilita = dataVisibilita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_t_tamponi.str_tipo_tampone_id
     *
     * @return the value of covidrsa_t_tamponi.str_tipo_tampone_id
     *
     * @mbg.generated
     */
    public Integer getStrTipoTamponeId() {
        return strTipoTamponeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_t_tamponi.str_tipo_tampone_id
     *
     * @param strTipoTamponeId the value for covidrsa_t_tamponi.str_tipo_tampone_id
     *
     * @mbg.generated
     */
    public void setStrTipoTamponeId(Integer strTipoTamponeId) {
        this.strTipoTamponeId = strTipoTamponeId;
    }
}