/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class RsaTamponeCategoria {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.tamp_cat_id
     *
     * @mbg.generated
     */
    private Integer tampCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.tamp_cat_cod
     *
     * @mbg.generated
     */
    private String tampCatCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.tamp_cat_desc
     *
     * @mbg.generated
     */
    private String tampCatDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_d_tampone_categoria.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.tamp_cat_id
     *
     * @return the value of covidrsa_d_tampone_categoria.tamp_cat_id
     *
     * @mbg.generated
     */
    public Integer getTampCatId() {
        return tampCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.tamp_cat_id
     *
     * @param tampCatId the value for covidrsa_d_tampone_categoria.tamp_cat_id
     *
     * @mbg.generated
     */
    public void setTampCatId(Integer tampCatId) {
        this.tampCatId = tampCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.tamp_cat_cod
     *
     * @return the value of covidrsa_d_tampone_categoria.tamp_cat_cod
     *
     * @mbg.generated
     */
    public String getTampCatCod() {
        return tampCatCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.tamp_cat_cod
     *
     * @param tampCatCod the value for covidrsa_d_tampone_categoria.tamp_cat_cod
     *
     * @mbg.generated
     */
    public void setTampCatCod(String tampCatCod) {
        this.tampCatCod = tampCatCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.tamp_cat_desc
     *
     * @return the value of covidrsa_d_tampone_categoria.tamp_cat_desc
     *
     * @mbg.generated
     */
    public String getTampCatDesc() {
        return tampCatDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.tamp_cat_desc
     *
     * @param tampCatDesc the value for covidrsa_d_tampone_categoria.tamp_cat_desc
     *
     * @mbg.generated
     */
    public void setTampCatDesc(String tampCatDesc) {
        this.tampCatDesc = tampCatDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.validita_inizio
     *
     * @return the value of covidrsa_d_tampone_categoria.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.validita_inizio
     *
     * @param validitaInizio the value for covidrsa_d_tampone_categoria.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.validita_fine
     *
     * @return the value of covidrsa_d_tampone_categoria.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.validita_fine
     *
     * @param validitaFine the value for covidrsa_d_tampone_categoria.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.utente_operazione
     *
     * @return the value of covidrsa_d_tampone_categoria.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.utente_operazione
     *
     * @param utenteOperazione the value for covidrsa_d_tampone_categoria.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.data_creazione
     *
     * @return the value of covidrsa_d_tampone_categoria.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.data_creazione
     *
     * @param dataCreazione the value for covidrsa_d_tampone_categoria.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.data_modifica
     *
     * @return the value of covidrsa_d_tampone_categoria.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.data_modifica
     *
     * @param dataModifica the value for covidrsa_d_tampone_categoria.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column covidrsa_d_tampone_categoria.data_cancellazione
     *
     * @return the value of covidrsa_d_tampone_categoria.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column covidrsa_d_tampone_categoria.data_cancellazione
     *
     * @param dataCancellazione the value for covidrsa_d_tampone_categoria.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}