/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.math.BigDecimal;

public class Sintomo {

	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.id_sintomo
	 * @mbg.generated
	 */
	private Long idSintomo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.id_decorso
	 * @mbg.generated
	 */
	private Long idDecorso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.temperatura
	 * @mbg.generated
	 */
	private BigDecimal temperatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_gusto
	 * @mbg.generated
	 */
	private String flgGusto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_olfatto
	 * @mbg.generated
	 */
	private String flgOlfatto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_tosse
	 * @mbg.generated
	 */
	private String flgTosse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_dolori_musc
	 * @mbg.generated
	 */
	private String flgDoloriMusc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_stanchezza
	 * @mbg.generated
	 */
	private String flgStanchezza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_congiuntivite
	 * @mbg.generated
	 */
	private String flgCongiuntivite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_diarrea
	 * @mbg.generated
	 */
	private String flgDiarrea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_raffreddore
	 * @mbg.generated
	 */
	private String flgRaffreddore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.note_sintomo
	 * @mbg.generated
	 */
	private String noteSintomo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_dispnea
	 * @mbg.generated
	 */
	private String flgDispnea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_cefalea
	 * @mbg.generated
	 */
	private String flgCefalea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sintomo.flg_faringodinia
	 * @mbg.generated
	 */
	private String flgFaringodinia;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.id_sintomo
	 * @return  the value of sintomo.id_sintomo
	 * @mbg.generated
	 */
	public Long getIdSintomo() {
		return idSintomo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.id_sintomo
	 * @param idSintomo  the value for sintomo.id_sintomo
	 * @mbg.generated
	 */
	public void setIdSintomo(Long idSintomo) {
		this.idSintomo = idSintomo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.id_decorso
	 * @return  the value of sintomo.id_decorso
	 * @mbg.generated
	 */
	public Long getIdDecorso() {
		return idDecorso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.id_decorso
	 * @param idDecorso  the value for sintomo.id_decorso
	 * @mbg.generated
	 */
	public void setIdDecorso(Long idDecorso) {
		this.idDecorso = idDecorso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.temperatura
	 * @return  the value of sintomo.temperatura
	 * @mbg.generated
	 */
	public BigDecimal getTemperatura() {
		return temperatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.temperatura
	 * @param temperatura  the value for sintomo.temperatura
	 * @mbg.generated
	 */
	public void setTemperatura(BigDecimal temperatura) {
		this.temperatura = temperatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_gusto
	 * @return  the value of sintomo.flg_gusto
	 * @mbg.generated
	 */
	public String getFlgGusto() {
		return flgGusto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_gusto
	 * @param flgGusto  the value for sintomo.flg_gusto
	 * @mbg.generated
	 */
	public void setFlgGusto(String flgGusto) {
		this.flgGusto = flgGusto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_olfatto
	 * @return  the value of sintomo.flg_olfatto
	 * @mbg.generated
	 */
	public String getFlgOlfatto() {
		return flgOlfatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_olfatto
	 * @param flgOlfatto  the value for sintomo.flg_olfatto
	 * @mbg.generated
	 */
	public void setFlgOlfatto(String flgOlfatto) {
		this.flgOlfatto = flgOlfatto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_tosse
	 * @return  the value of sintomo.flg_tosse
	 * @mbg.generated
	 */
	public String getFlgTosse() {
		return flgTosse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_tosse
	 * @param flgTosse  the value for sintomo.flg_tosse
	 * @mbg.generated
	 */
	public void setFlgTosse(String flgTosse) {
		this.flgTosse = flgTosse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_dolori_musc
	 * @return  the value of sintomo.flg_dolori_musc
	 * @mbg.generated
	 */
	public String getFlgDoloriMusc() {
		return flgDoloriMusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_dolori_musc
	 * @param flgDoloriMusc  the value for sintomo.flg_dolori_musc
	 * @mbg.generated
	 */
	public void setFlgDoloriMusc(String flgDoloriMusc) {
		this.flgDoloriMusc = flgDoloriMusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_stanchezza
	 * @return  the value of sintomo.flg_stanchezza
	 * @mbg.generated
	 */
	public String getFlgStanchezza() {
		return flgStanchezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_stanchezza
	 * @param flgStanchezza  the value for sintomo.flg_stanchezza
	 * @mbg.generated
	 */
	public void setFlgStanchezza(String flgStanchezza) {
		this.flgStanchezza = flgStanchezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_congiuntivite
	 * @return  the value of sintomo.flg_congiuntivite
	 * @mbg.generated
	 */
	public String getFlgCongiuntivite() {
		return flgCongiuntivite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_congiuntivite
	 * @param flgCongiuntivite  the value for sintomo.flg_congiuntivite
	 * @mbg.generated
	 */
	public void setFlgCongiuntivite(String flgCongiuntivite) {
		this.flgCongiuntivite = flgCongiuntivite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_diarrea
	 * @return  the value of sintomo.flg_diarrea
	 * @mbg.generated
	 */
	public String getFlgDiarrea() {
		return flgDiarrea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_diarrea
	 * @param flgDiarrea  the value for sintomo.flg_diarrea
	 * @mbg.generated
	 */
	public void setFlgDiarrea(String flgDiarrea) {
		this.flgDiarrea = flgDiarrea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_raffreddore
	 * @return  the value of sintomo.flg_raffreddore
	 * @mbg.generated
	 */
	public String getFlgRaffreddore() {
		return flgRaffreddore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_raffreddore
	 * @param flgRaffreddore  the value for sintomo.flg_raffreddore
	 * @mbg.generated
	 */
	public void setFlgRaffreddore(String flgRaffreddore) {
		this.flgRaffreddore = flgRaffreddore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.note_sintomo
	 * @return  the value of sintomo.note_sintomo
	 * @mbg.generated
	 */
	public String getNoteSintomo() {
		return noteSintomo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.note_sintomo
	 * @param noteSintomo  the value for sintomo.note_sintomo
	 * @mbg.generated
	 */
	public void setNoteSintomo(String noteSintomo) {
		this.noteSintomo = noteSintomo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_dispnea
	 * @return  the value of sintomo.flg_dispnea
	 * @mbg.generated
	 */
	public String getFlgDispnea() {
		return flgDispnea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_dispnea
	 * @param flgDispnea  the value for sintomo.flg_dispnea
	 * @mbg.generated
	 */
	public void setFlgDispnea(String flgDispnea) {
		this.flgDispnea = flgDispnea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_cefalea
	 * @return  the value of sintomo.flg_cefalea
	 * @mbg.generated
	 */
	public String getFlgCefalea() {
		return flgCefalea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_cefalea
	 * @param flgCefalea  the value for sintomo.flg_cefalea
	 * @mbg.generated
	 */
	public void setFlgCefalea(String flgCefalea) {
		this.flgCefalea = flgCefalea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sintomo.flg_faringodinia
	 * @return  the value of sintomo.flg_faringodinia
	 * @mbg.generated
	 */
	public String getFlgFaringodinia() {
		return flgFaringodinia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sintomo.flg_faringodinia
	 * @param flgFaringodinia  the value for sintomo.flg_faringodinia
	 * @mbg.generated
	 */
	public void setFlgFaringodinia(String flgFaringodinia) {
		this.flgFaringodinia = flgFaringodinia;
	}


}