/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class SoggettoContattoTipo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.contatto_tipo_id
     *
     * @mbg.generated
     */
    private Integer contattoTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.contatto_tipo_cod
     *
     * @mbg.generated
     */
    private String contattoTipoCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.contatto_tipo_desc
     *
     * @mbg.generated
     */
    private String contattoTipoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_contatto_tipo.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.contatto_tipo_id
     *
     * @return the value of d_contatto_tipo.contatto_tipo_id
     *
     * @mbg.generated
     */
    public Integer getContattoTipoId() {
        return contattoTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.contatto_tipo_id
     *
     * @param contattoTipoId the value for d_contatto_tipo.contatto_tipo_id
     *
     * @mbg.generated
     */
    public void setContattoTipoId(Integer contattoTipoId) {
        this.contattoTipoId = contattoTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.contatto_tipo_cod
     *
     * @return the value of d_contatto_tipo.contatto_tipo_cod
     *
     * @mbg.generated
     */
    public String getContattoTipoCod() {
        return contattoTipoCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.contatto_tipo_cod
     *
     * @param contattoTipoCod the value for d_contatto_tipo.contatto_tipo_cod
     *
     * @mbg.generated
     */
    public void setContattoTipoCod(String contattoTipoCod) {
        this.contattoTipoCod = contattoTipoCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.contatto_tipo_desc
     *
     * @return the value of d_contatto_tipo.contatto_tipo_desc
     *
     * @mbg.generated
     */
    public String getContattoTipoDesc() {
        return contattoTipoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.contatto_tipo_desc
     *
     * @param contattoTipoDesc the value for d_contatto_tipo.contatto_tipo_desc
     *
     * @mbg.generated
     */
    public void setContattoTipoDesc(String contattoTipoDesc) {
        this.contattoTipoDesc = contattoTipoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.validita_inizio
     *
     * @return the value of d_contatto_tipo.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.validita_inizio
     *
     * @param validitaInizio the value for d_contatto_tipo.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.validita_fine
     *
     * @return the value of d_contatto_tipo.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.validita_fine
     *
     * @param validitaFine the value for d_contatto_tipo.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.utente_operazione
     *
     * @return the value of d_contatto_tipo.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.utente_operazione
     *
     * @param utenteOperazione the value for d_contatto_tipo.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.data_creazione
     *
     * @return the value of d_contatto_tipo.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.data_creazione
     *
     * @param dataCreazione the value for d_contatto_tipo.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.data_modifica
     *
     * @return the value of d_contatto_tipo.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.data_modifica
     *
     * @param dataModifica the value for d_contatto_tipo.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_contatto_tipo.data_cancellazione
     *
     * @return the value of d_contatto_tipo.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_contatto_tipo.data_cancellazione
     *
     * @param dataCancellazione the value for d_contatto_tipo.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}