/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class SoggettoStrutturaInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.ssi_id
	 * @mbg.generated
	 */
	private Integer ssiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.id_soggetto
	 * @mbg.generated
	 */
	private Integer idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.sti_id
	 * @mbg.generated
	 */
	private Integer stiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidres_r_soggetto_struttura_info.flg_ospite
	 * @mbg.generated
	 */
	private Boolean flgOspite;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.ssi_id
	 * @return  the value of covidres_r_soggetto_struttura_info.ssi_id
	 * @mbg.generated
	 */
	public Integer getSsiId() {
		return ssiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.ssi_id
	 * @param ssiId  the value for covidres_r_soggetto_struttura_info.ssi_id
	 * @mbg.generated
	 */
	public void setSsiId(Integer ssiId) {
		this.ssiId = ssiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.id_soggetto
	 * @return  the value of covidres_r_soggetto_struttura_info.id_soggetto
	 * @mbg.generated
	 */
	public Integer getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.id_soggetto
	 * @param idSoggetto  the value for covidres_r_soggetto_struttura_info.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Integer idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.sti_id
	 * @return  the value of covidres_r_soggetto_struttura_info.sti_id
	 * @mbg.generated
	 */
	public Integer getStiId() {
		return stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.sti_id
	 * @param stiId  the value for covidres_r_soggetto_struttura_info.sti_id
	 * @mbg.generated
	 */
	public void setStiId(Integer stiId) {
		this.stiId = stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.validita_inizio
	 * @return  the value of covidres_r_soggetto_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.validita_inizio
	 * @param validitaInizio  the value for covidres_r_soggetto_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.validita_fine
	 * @return  the value of covidres_r_soggetto_struttura_info.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.validita_fine
	 * @param validitaFine  the value for covidres_r_soggetto_struttura_info.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.data_creazione
	 * @return  the value of covidres_r_soggetto_struttura_info.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.data_creazione
	 * @param dataCreazione  the value for covidres_r_soggetto_struttura_info.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.data_modifica
	 * @return  the value of covidres_r_soggetto_struttura_info.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.data_modifica
	 * @param dataModifica  the value for covidres_r_soggetto_struttura_info.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.data_cancellazione
	 * @return  the value of covidres_r_soggetto_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.data_cancellazione
	 * @param dataCancellazione  the value for covidres_r_soggetto_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.utente_operazione
	 * @return  the value of covidres_r_soggetto_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.utente_operazione
	 * @param utenteOperazione  the value for covidres_r_soggetto_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.id_struttura
	 * @return  the value of covidres_r_soggetto_struttura_info.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.id_struttura
	 * @param idStruttura  the value for covidres_r_soggetto_struttura_info.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidres_r_soggetto_struttura_info.flg_ospite
	 * @return  the value of covidres_r_soggetto_struttura_info.flg_ospite
	 * @mbg.generated
	 */
	public Boolean getFlgOspite() {
		return flgOspite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidres_r_soggetto_struttura_info.flg_ospite
	 * @param flgOspite  the value for covidres_r_soggetto_struttura_info.flg_ospite
	 * @mbg.generated
	 */
	public void setFlgOspite(Boolean flgOspite) {
		this.flgOspite = flgOspite;
	}
}