/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class StrutturaInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer stiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_nome
	 * @mbg.generated
	 */
	
	@JsonProperty("Nome struttura")
	private String stiNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_indirizzo
	 * @mbg.generated
	 */
	
	@JsonProperty("Indirzzo")
	private String stiIndirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_telefono
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiTelefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_email
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_mensa_interna_presente
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiMensaInternaPresente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_asmed_mmg
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiAsmedMmg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_asmed_nommg
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiAsmedNommg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.id_struttura
	 * @mbg.generated
	 */
	@JsonIgnore
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.str_tipo_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer strTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.str_natura_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer strNaturaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.str_accreditamento_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer strAccreditamentoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_comune_istat
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiComuneIstat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_pec
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiPec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_str_presente
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiDirStrPresente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_str_nome
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirStrNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_str_tel_reperibilita
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirStrTelReperibilita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_sanit_presente
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiDirSanitPresente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_sanit_nome
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirSanitNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_sanit_tel_reperibilita
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirSanitTelReperibilita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_coord_inf_presente
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiCoordInfPresente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_coord_inf_nome
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiCoordInfNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_coord_inf_tel_reperibilita
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiCoordInfTelReperibilita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	@JsonIgnore
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.validita_fine
	 * @mbg.generated
	 */
	@JsonIgnore
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	@JsonIgnore
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.data_creazione
	 * @mbg.generated
	 */
	@JsonIgnore
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.data_modifica
	 * @mbg.generated
	 */
	@JsonIgnore
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	@JsonIgnore
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_email2
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiEmail2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_str_email
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirStrEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_dir_sanit_email
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiDirSanitEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_coord_inf_email
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiCoordInfEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_asmed_mista
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiAsmedMista;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_pers_inf_notturno
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiPersInfNotturno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.assmed_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer assmedId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_atto_autorizzativo
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiAttoAutorizzativo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_titolare_autorizzazione
	 * @mbg.generated
	 */
	@JsonIgnore
	private String stiTitolareAutorizzazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.str_tipo_utenza_id
	 * @mbg.generated
	 */
	@JsonIgnore
	private Integer strTipoUtenzaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidrsa_t_struttura_info.sti_escludi_struttura
	 * @mbg.generated
	 */
	@JsonIgnore
	private Boolean stiEscludiStruttura;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_adesione_dgr10
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAdesioneDgr10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_abilitato_sollievo
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAbilitatoSollievo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_abilitato_dim_prot
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAbilitatoDimProt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_abilitato_cavs
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAbilitatoCavs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_abilitato_lungodeg
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAbilitatoLungodeg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column covidrsa_t_struttura_info.sti_abilitato_hospice
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Boolean stiAbilitatoHospice;
    
    
	public Boolean getStiAbilitatoSollievo() {
        return stiAbilitatoSollievo;
    }

    public void setStiAbilitatoSollievo(Boolean stiAbilitatoSollievo) {
        this.stiAbilitatoSollievo = stiAbilitatoSollievo;
    }

    public Boolean getStiAbilitatoDimProt() {
        return stiAbilitatoDimProt;
    }

    public void setStiAbilitatoDimProt(Boolean stiAbilitatoDimProt) {
        this.stiAbilitatoDimProt = stiAbilitatoDimProt;
    }

    public Boolean getStiAbilitatoCavs() {
        return stiAbilitatoCavs;
    }

    public void setStiAbilitatoCavs(Boolean stiAbilitatoCavs) {
        this.stiAbilitatoCavs = stiAbilitatoCavs;
    }

    public Boolean getStiAbilitatoLungodeg() {
        return stiAbilitatoLungodeg;
    }

    public void setStiAbilitatoLungodeg(Boolean stiAbilitatoLungodeg) {
        this.stiAbilitatoLungodeg = stiAbilitatoLungodeg;
    }

    public Boolean getStiAbilitatoHospice() {
        return stiAbilitatoHospice;
    }

    public void setStiAbilitatoHospice(Boolean stiAbilitatoHospice) {
        this.stiAbilitatoHospice = stiAbilitatoHospice;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_id
	 * @return  the value of covidrsa_t_struttura_info.sti_id
	 * @mbg.generated
	 */
	public Integer getStiId() {
		return stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_id
	 * @param stiId  the value for covidrsa_t_struttura_info.sti_id
	 * @mbg.generated
	 */
	public void setStiId(Integer stiId) {
		this.stiId = stiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_nome
	 * @return  the value of covidrsa_t_struttura_info.sti_nome
	 * @mbg.generated
	 */
	public String getStiNome() {
		return stiNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_nome
	 * @param stiNome  the value for covidrsa_t_struttura_info.sti_nome
	 * @mbg.generated
	 */
	public void setStiNome(String stiNome) {
		this.stiNome = stiNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_indirizzo
	 * @return  the value of covidrsa_t_struttura_info.sti_indirizzo
	 * @mbg.generated
	 */
	public String getStiIndirizzo() {
		return stiIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_indirizzo
	 * @param stiIndirizzo  the value for covidrsa_t_struttura_info.sti_indirizzo
	 * @mbg.generated
	 */
	public void setStiIndirizzo(String stiIndirizzo) {
		this.stiIndirizzo = stiIndirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_telefono
	 * @return  the value of covidrsa_t_struttura_info.sti_telefono
	 * @mbg.generated
	 */
	public String getStiTelefono() {
		return stiTelefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_telefono
	 * @param stiTelefono  the value for covidrsa_t_struttura_info.sti_telefono
	 * @mbg.generated
	 */
	public void setStiTelefono(String stiTelefono) {
		this.stiTelefono = stiTelefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_email
	 * @return  the value of covidrsa_t_struttura_info.sti_email
	 * @mbg.generated
	 */
	public String getStiEmail() {
		return stiEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_email
	 * @param stiEmail  the value for covidrsa_t_struttura_info.sti_email
	 * @mbg.generated
	 */
	public void setStiEmail(String stiEmail) {
		this.stiEmail = stiEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_mensa_interna_presente
	 * @return  the value of covidrsa_t_struttura_info.sti_mensa_interna_presente
	 * @mbg.generated
	 */
	public Boolean getStiMensaInternaPresente() {
		return stiMensaInternaPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_mensa_interna_presente
	 * @param stiMensaInternaPresente  the value for covidrsa_t_struttura_info.sti_mensa_interna_presente
	 * @mbg.generated
	 */
	public void setStiMensaInternaPresente(Boolean stiMensaInternaPresente) {
		this.stiMensaInternaPresente = stiMensaInternaPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_asmed_mmg
	 * @return  the value of covidrsa_t_struttura_info.sti_asmed_mmg
	 * @mbg.generated
	 */
	public Boolean getStiAsmedMmg() {
		return stiAsmedMmg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_asmed_mmg
	 * @param stiAsmedMmg  the value for covidrsa_t_struttura_info.sti_asmed_mmg
	 * @mbg.generated
	 */
	public void setStiAsmedMmg(Boolean stiAsmedMmg) {
		this.stiAsmedMmg = stiAsmedMmg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_asmed_nommg
	 * @return  the value of covidrsa_t_struttura_info.sti_asmed_nommg
	 * @mbg.generated
	 */
	public Boolean getStiAsmedNommg() {
		return stiAsmedNommg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_asmed_nommg
	 * @param stiAsmedNommg  the value for covidrsa_t_struttura_info.sti_asmed_nommg
	 * @mbg.generated
	 */
	public void setStiAsmedNommg(Boolean stiAsmedNommg) {
		this.stiAsmedNommg = stiAsmedNommg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.id_struttura
	 * @return  the value of covidrsa_t_struttura_info.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.id_struttura
	 * @param idStruttura  the value for covidrsa_t_struttura_info.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.str_tipo_id
	 * @return  the value of covidrsa_t_struttura_info.str_tipo_id
	 * @mbg.generated
	 */
	public Integer getStrTipoId() {
		return strTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.str_tipo_id
	 * @param strTipoId  the value for covidrsa_t_struttura_info.str_tipo_id
	 * @mbg.generated
	 */
	public void setStrTipoId(Integer strTipoId) {
		this.strTipoId = strTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.str_natura_id
	 * @return  the value of covidrsa_t_struttura_info.str_natura_id
	 * @mbg.generated
	 */
	public Integer getStrNaturaId() {
		return strNaturaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.str_natura_id
	 * @param strNaturaId  the value for covidrsa_t_struttura_info.str_natura_id
	 * @mbg.generated
	 */
	public void setStrNaturaId(Integer strNaturaId) {
		this.strNaturaId = strNaturaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.str_accreditamento_id
	 * @return  the value of covidrsa_t_struttura_info.str_accreditamento_id
	 * @mbg.generated
	 */
	public Integer getStrAccreditamentoId() {
		return strAccreditamentoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.str_accreditamento_id
	 * @param strAccreditamentoId  the value for covidrsa_t_struttura_info.str_accreditamento_id
	 * @mbg.generated
	 */
	public void setStrAccreditamentoId(Integer strAccreditamentoId) {
		this.strAccreditamentoId = strAccreditamentoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_comune_istat
	 * @return  the value of covidrsa_t_struttura_info.sti_comune_istat
	 * @mbg.generated
	 */
	public String getStiComuneIstat() {
		return stiComuneIstat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_comune_istat
	 * @param stiComuneIstat  the value for covidrsa_t_struttura_info.sti_comune_istat
	 * @mbg.generated
	 */
	public void setStiComuneIstat(String stiComuneIstat) {
		this.stiComuneIstat = stiComuneIstat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_pec
	 * @return  the value of covidrsa_t_struttura_info.sti_pec
	 * @mbg.generated
	 */
	public String getStiPec() {
		return stiPec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_pec
	 * @param stiPec  the value for covidrsa_t_struttura_info.sti_pec
	 * @mbg.generated
	 */
	public void setStiPec(String stiPec) {
		this.stiPec = stiPec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_str_presente
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_str_presente
	 * @mbg.generated
	 */
	public Boolean getStiDirStrPresente() {
		return stiDirStrPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_str_presente
	 * @param stiDirStrPresente  the value for covidrsa_t_struttura_info.sti_dir_str_presente
	 * @mbg.generated
	 */
	public void setStiDirStrPresente(Boolean stiDirStrPresente) {
		this.stiDirStrPresente = stiDirStrPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_str_nome
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_str_nome
	 * @mbg.generated
	 */
	public String getStiDirStrNome() {
		return stiDirStrNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_str_nome
	 * @param stiDirStrNome  the value for covidrsa_t_struttura_info.sti_dir_str_nome
	 * @mbg.generated
	 */
	public void setStiDirStrNome(String stiDirStrNome) {
		this.stiDirStrNome = stiDirStrNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_str_tel_reperibilita
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_str_tel_reperibilita
	 * @mbg.generated
	 */
	public String getStiDirStrTelReperibilita() {
		return stiDirStrTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_str_tel_reperibilita
	 * @param stiDirStrTelReperibilita  the value for covidrsa_t_struttura_info.sti_dir_str_tel_reperibilita
	 * @mbg.generated
	 */
	public void setStiDirStrTelReperibilita(String stiDirStrTelReperibilita) {
		this.stiDirStrTelReperibilita = stiDirStrTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_presente
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_sanit_presente
	 * @mbg.generated
	 */
	public Boolean getStiDirSanitPresente() {
		return stiDirSanitPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_presente
	 * @param stiDirSanitPresente  the value for covidrsa_t_struttura_info.sti_dir_sanit_presente
	 * @mbg.generated
	 */
	public void setStiDirSanitPresente(Boolean stiDirSanitPresente) {
		this.stiDirSanitPresente = stiDirSanitPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_nome
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_sanit_nome
	 * @mbg.generated
	 */
	public String getStiDirSanitNome() {
		return stiDirSanitNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_nome
	 * @param stiDirSanitNome  the value for covidrsa_t_struttura_info.sti_dir_sanit_nome
	 * @mbg.generated
	 */
	public void setStiDirSanitNome(String stiDirSanitNome) {
		this.stiDirSanitNome = stiDirSanitNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_tel_reperibilita
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_sanit_tel_reperibilita
	 * @mbg.generated
	 */
	public String getStiDirSanitTelReperibilita() {
		return stiDirSanitTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_tel_reperibilita
	 * @param stiDirSanitTelReperibilita  the value for covidrsa_t_struttura_info.sti_dir_sanit_tel_reperibilita
	 * @mbg.generated
	 */
	public void setStiDirSanitTelReperibilita(String stiDirSanitTelReperibilita) {
		this.stiDirSanitTelReperibilita = stiDirSanitTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_coord_inf_presente
	 * @return  the value of covidrsa_t_struttura_info.sti_coord_inf_presente
	 * @mbg.generated
	 */
	public Boolean getStiCoordInfPresente() {
		return stiCoordInfPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_coord_inf_presente
	 * @param stiCoordInfPresente  the value for covidrsa_t_struttura_info.sti_coord_inf_presente
	 * @mbg.generated
	 */
	public void setStiCoordInfPresente(Boolean stiCoordInfPresente) {
		this.stiCoordInfPresente = stiCoordInfPresente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_coord_inf_nome
	 * @return  the value of covidrsa_t_struttura_info.sti_coord_inf_nome
	 * @mbg.generated
	 */
	public String getStiCoordInfNome() {
		return stiCoordInfNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_coord_inf_nome
	 * @param stiCoordInfNome  the value for covidrsa_t_struttura_info.sti_coord_inf_nome
	 * @mbg.generated
	 */
	public void setStiCoordInfNome(String stiCoordInfNome) {
		this.stiCoordInfNome = stiCoordInfNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_coord_inf_tel_reperibilita
	 * @return  the value of covidrsa_t_struttura_info.sti_coord_inf_tel_reperibilita
	 * @mbg.generated
	 */
	public String getStiCoordInfTelReperibilita() {
		return stiCoordInfTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_coord_inf_tel_reperibilita
	 * @param stiCoordInfTelReperibilita  the value for covidrsa_t_struttura_info.sti_coord_inf_tel_reperibilita
	 * @mbg.generated
	 */
	public void setStiCoordInfTelReperibilita(String stiCoordInfTelReperibilita) {
		this.stiCoordInfTelReperibilita = stiCoordInfTelReperibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.validita_inizio
	 * @return  the value of covidrsa_t_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.validita_inizio
	 * @param validitaInizio  the value for covidrsa_t_struttura_info.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.validita_fine
	 * @return  the value of covidrsa_t_struttura_info.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.validita_fine
	 * @param validitaFine  the value for covidrsa_t_struttura_info.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.utente_operazione
	 * @return  the value of covidrsa_t_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.utente_operazione
	 * @param utenteOperazione  the value for covidrsa_t_struttura_info.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.data_creazione
	 * @return  the value of covidrsa_t_struttura_info.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.data_creazione
	 * @param dataCreazione  the value for covidrsa_t_struttura_info.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.data_modifica
	 * @return  the value of covidrsa_t_struttura_info.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.data_modifica
	 * @param dataModifica  the value for covidrsa_t_struttura_info.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.data_cancellazione
	 * @return  the value of covidrsa_t_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.data_cancellazione
	 * @param dataCancellazione  the value for covidrsa_t_struttura_info.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_email2
	 * @return  the value of covidrsa_t_struttura_info.sti_email2
	 * @mbg.generated
	 */
	public String getStiEmail2() {
		return stiEmail2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_email2
	 * @param stiEmail2  the value for covidrsa_t_struttura_info.sti_email2
	 * @mbg.generated
	 */
	public void setStiEmail2(String stiEmail2) {
		this.stiEmail2 = stiEmail2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_str_email
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_str_email
	 * @mbg.generated
	 */
	public String getStiDirStrEmail() {
		return stiDirStrEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_str_email
	 * @param stiDirStrEmail  the value for covidrsa_t_struttura_info.sti_dir_str_email
	 * @mbg.generated
	 */
	public void setStiDirStrEmail(String stiDirStrEmail) {
		this.stiDirStrEmail = stiDirStrEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_email
	 * @return  the value of covidrsa_t_struttura_info.sti_dir_sanit_email
	 * @mbg.generated
	 */
	public String getStiDirSanitEmail() {
		return stiDirSanitEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_dir_sanit_email
	 * @param stiDirSanitEmail  the value for covidrsa_t_struttura_info.sti_dir_sanit_email
	 * @mbg.generated
	 */
	public void setStiDirSanitEmail(String stiDirSanitEmail) {
		this.stiDirSanitEmail = stiDirSanitEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_coord_inf_email
	 * @return  the value of covidrsa_t_struttura_info.sti_coord_inf_email
	 * @mbg.generated
	 */
	public String getStiCoordInfEmail() {
		return stiCoordInfEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_coord_inf_email
	 * @param stiCoordInfEmail  the value for covidrsa_t_struttura_info.sti_coord_inf_email
	 * @mbg.generated
	 */
	public void setStiCoordInfEmail(String stiCoordInfEmail) {
		this.stiCoordInfEmail = stiCoordInfEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_asmed_mista
	 * @return  the value of covidrsa_t_struttura_info.sti_asmed_mista
	 * @mbg.generated
	 */
	public Boolean getStiAsmedMista() {
		return stiAsmedMista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_asmed_mista
	 * @param stiAsmedMista  the value for covidrsa_t_struttura_info.sti_asmed_mista
	 * @mbg.generated
	 */
	public void setStiAsmedMista(Boolean stiAsmedMista) {
		this.stiAsmedMista = stiAsmedMista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_pers_inf_notturno
	 * @return  the value of covidrsa_t_struttura_info.sti_pers_inf_notturno
	 * @mbg.generated
	 */
	public Boolean getStiPersInfNotturno() {
		return stiPersInfNotturno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_pers_inf_notturno
	 * @param stiPersInfNotturno  the value for covidrsa_t_struttura_info.sti_pers_inf_notturno
	 * @mbg.generated
	 */
	public void setStiPersInfNotturno(Boolean stiPersInfNotturno) {
		this.stiPersInfNotturno = stiPersInfNotturno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.assmed_id
	 * @return  the value of covidrsa_t_struttura_info.assmed_id
	 * @mbg.generated
	 */
	public Integer getAssmedId() {
		return assmedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.assmed_id
	 * @param assmedId  the value for covidrsa_t_struttura_info.assmed_id
	 * @mbg.generated
	 */
	public void setAssmedId(Integer assmedId) {
		this.assmedId = assmedId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_atto_autorizzativo
	 * @return  the value of covidrsa_t_struttura_info.sti_atto_autorizzativo
	 * @mbg.generated
	 */
	public String getStiAttoAutorizzativo() {
		return stiAttoAutorizzativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_atto_autorizzativo
	 * @param stiAttoAutorizzativo  the value for covidrsa_t_struttura_info.sti_atto_autorizzativo
	 * @mbg.generated
	 */
	public void setStiAttoAutorizzativo(String stiAttoAutorizzativo) {
		this.stiAttoAutorizzativo = stiAttoAutorizzativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_titolare_autorizzazione
	 * @return  the value of covidrsa_t_struttura_info.sti_titolare_autorizzazione
	 * @mbg.generated
	 */
	public String getStiTitolareAutorizzazione() {
		return stiTitolareAutorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_titolare_autorizzazione
	 * @param stiTitolareAutorizzazione  the value for covidrsa_t_struttura_info.sti_titolare_autorizzazione
	 * @mbg.generated
	 */
	public void setStiTitolareAutorizzazione(String stiTitolareAutorizzazione) {
		this.stiTitolareAutorizzazione = stiTitolareAutorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.str_tipo_utenza_id
	 * @return  the value of covidrsa_t_struttura_info.str_tipo_utenza_id
	 * @mbg.generated
	 */
	public Integer getStrTipoUtenzaId() {
		return strTipoUtenzaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.str_tipo_utenza_id
	 * @param strTipoUtenzaId  the value for covidrsa_t_struttura_info.str_tipo_utenza_id
	 * @mbg.generated
	 */
	public void setStrTipoUtenzaId(Integer strTipoUtenzaId) {
		this.strTipoUtenzaId = strTipoUtenzaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidrsa_t_struttura_info.sti_escludi_struttura
	 * @return  the value of covidrsa_t_struttura_info.sti_escludi_struttura
	 * @mbg.generated
	 */
	public Boolean getStiEscludiStruttura() {
		return stiEscludiStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidrsa_t_struttura_info.sti_escludi_struttura
	 * @param stiEscludiStruttura  the value for covidrsa_t_struttura_info.sti_escludi_struttura
	 * @mbg.generated
	 */
	public void setStiEscludiStruttura(Boolean stiEscludiStruttura) {
		this.stiEscludiStruttura = stiEscludiStruttura;
	}

    public Boolean getStiAdesioneDgr10() {
        return stiAdesioneDgr10;
    }

    public void setStiAdesioneDgr10(Boolean stiAdesioneDgr10) {
        this.stiAdesioneDgr10 = stiAdesioneDgr10;
    }
}