/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

public class Struttura {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.nome
	 * @mbg.generated
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.natura
	 * @mbg.generated
	 */
	private String natura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.indirizzo
	 * @mbg.generated
	 */
	private String indirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column struttura.comune_istat
	 * @mbg.generated
	 */
	private String comuneIstat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.id_struttura
	 * @return  the value of struttura.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.id_struttura
	 * @param idStruttura  the value for struttura.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.id_ente
	 * @return  the value of struttura.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.id_ente
	 * @param idEnte  the value for struttura.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.nome
	 * @return  the value of struttura.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.nome
	 * @param nome  the value for struttura.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.natura
	 * @return  the value of struttura.natura
	 * @mbg.generated
	 */
	public String getNatura() {
		return natura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.natura
	 * @param natura  the value for struttura.natura
	 * @mbg.generated
	 */
	public void setNatura(String natura) {
		this.natura = natura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.indirizzo
	 * @return  the value of struttura.indirizzo
	 * @mbg.generated
	 */
	public String getIndirizzo() {
		return indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.indirizzo
	 * @param indirizzo  the value for struttura.indirizzo
	 * @mbg.generated
	 */
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column struttura.comune_istat
	 * @return  the value of struttura.comune_istat
	 * @mbg.generated
	 */
	public String getComuneIstat() {
		return comuneIstat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column struttura.comune_istat
	 * @param comuneIstat  the value for struttura.comune_istat
	 * @mbg.generated
	 */
	public void setComuneIstat(String comuneIstat) {
		this.comuneIstat = comuneIstat;
	}
}