/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class Tampone {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_tampone
	 * @mbg.generated
	 */
	private Long idTampone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_soggetto
	 * @mbg.generated
	 */
	private Long idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_laboratorio
	 * @mbg.generated
	 */
	private Long idLaboratorio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	private String criterioEpidemiologicoCovid19;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_test_covid
	 * @mbg.generated
	 */
	private Long idTestCovid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_test_str
	 * @mbg.generated
	 */
	private String dataTestStr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_ris_tamp
	 * @mbg.generated
	 */
	private Long idRisTamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	private String tamponeAutorizzato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	private Date dataInserimentoRichiesta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	private Date dataUltimaModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	private String utenteUltimaModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_test
	 * @mbg.generated
	 */
	private Date dataTest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.medico_richiedente
	 * @mbg.generated
	 */
	private String medicoRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.contatto_richiedente
	 * @mbg.generated
	 */
	private String contattoRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.tampone_motivo_id
	 * @mbg.generated
	 */
	private Integer tamponeMotivoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_univoco
	 * @mbg.generated
	 */
	private String idUnivoco;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_prelievo_prevista
	 * @mbg.generated
	 */
	private Date dataPrelievoPrevista;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_laboratorio_competenza
	 * @mbg.generated
	 */
	private Integer idLaboratorioCompetenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_laboratorio_effettivo
	 * @mbg.generated
	 */
	private Integer idLaboratorioEffettivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_asr
	 * @mbg.generated
	 */
	private Long idAsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.hotspot_dispeff_id
	 * @mbg.generated
	 */
	private Long hotspotDispeffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.criterio_epidemiologico_id
	 * @mbg.generated
	 */
	private Integer criterioEpidemiologicoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.test_tipo_id
	 * @mbg.generated
	 */
	private Integer testTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.medico_refertante
	 * @mbg.generated
	 */
	private String medicoRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.luogo_id
	 * @mbg.generated
	 */
	private Integer luogoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.tampone_stato_id
	 * @mbg.generated
	 */
	private Integer tamponeStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_prelievo_effettiva
	 * @mbg.generated
	 */
	private Date dataPrelievoEffettiva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.test_rapido_jrc_id
	 * @mbg.generated
	 */
	private Integer testRapidoJrcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.webapp_richiedente
	 * @mbg.generated
	 */
	private String webappRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_profilo_richiedente
	 * @mbg.generated
	 */
	private Integer idProfiloRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.ruolo_richiedente
	 * @mbg.generated
	 */
	private String ruoloRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.utente_richiedente
	 * @mbg.generated
	 */
	private String utenteRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_ente_richiedente
	 * @mbg.generated
	 */
	private Integer idEnteRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_struttura_richiedente
	 * @mbg.generated
	 */
	private String idStrutturaRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_area_richiedente
	 * @mbg.generated
	 */
	private Integer idAreaRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.webapp_refertante
	 * @mbg.generated
	 */
	private String webappRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_profilo_refertante
	 * @mbg.generated
	 */
	private Integer idProfiloRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.ruolo_refertante
	 * @mbg.generated
	 */
	private String ruoloRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.utente_refertante
	 * @mbg.generated
	 */
	private String utenteRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_ente_refertante
	 * @mbg.generated
	 */
	private Integer idEnteRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_struttura_refertante
	 * @mbg.generated
	 */
	private String idStrutturaRefertante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_area_refertante
	 * @mbg.generated
	 */
	private Integer idAreaRefertante;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_tampone
	 * @return  the value of tampone.id_tampone
	 * @mbg.generated
	 */
	public Long getIdTampone() {
		return idTampone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_tampone
	 * @param idTampone  the value for tampone.id_tampone
	 * @mbg.generated
	 */
	public void setIdTampone(Long idTampone) {
		this.idTampone = idTampone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_soggetto
	 * @return  the value of tampone.id_soggetto
	 * @mbg.generated
	 */
	public Long getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_soggetto
	 * @param idSoggetto  the value for tampone.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Long idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_laboratorio
	 * @return  the value of tampone.id_laboratorio
	 * @mbg.generated
	 */
	public Long getIdLaboratorio() {
		return idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_laboratorio
	 * @param idLaboratorio  the value for tampone.id_laboratorio
	 * @mbg.generated
	 */
	public void setIdLaboratorio(Long idLaboratorio) {
		this.idLaboratorio = idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.criterio_epidemiologico_covid19
	 * @return  the value of tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	public String getCriterioEpidemiologicoCovid19() {
		return criterioEpidemiologicoCovid19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.criterio_epidemiologico_covid19
	 * @param criterioEpidemiologicoCovid19  the value for tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	public void setCriterioEpidemiologicoCovid19(String criterioEpidemiologicoCovid19) {
		this.criterioEpidemiologicoCovid19 = criterioEpidemiologicoCovid19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_test_covid
	 * @return  the value of tampone.id_test_covid
	 * @mbg.generated
	 */
	public Long getIdTestCovid() {
		return idTestCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_test_covid
	 * @param idTestCovid  the value for tampone.id_test_covid
	 * @mbg.generated
	 */
	public void setIdTestCovid(Long idTestCovid) {
		this.idTestCovid = idTestCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_test_str
	 * @return  the value of tampone.data_test_str
	 * @mbg.generated
	 */
	public String getDataTestStr() {
		return dataTestStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_test_str
	 * @param dataTestStr  the value for tampone.data_test_str
	 * @mbg.generated
	 */
	public void setDataTestStr(String dataTestStr) {
		this.dataTestStr = dataTestStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_ris_tamp
	 * @return  the value of tampone.id_ris_tamp
	 * @mbg.generated
	 */
	public Long getIdRisTamp() {
		return idRisTamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_ris_tamp
	 * @param idRisTamp  the value for tampone.id_ris_tamp
	 * @mbg.generated
	 */
	public void setIdRisTamp(Long idRisTamp) {
		this.idRisTamp = idRisTamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.tampone_autorizzato
	 * @return  the value of tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	public String getTamponeAutorizzato() {
		return tamponeAutorizzato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.tampone_autorizzato
	 * @param tamponeAutorizzato  the value for tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	public void setTamponeAutorizzato(String tamponeAutorizzato) {
		this.tamponeAutorizzato = tamponeAutorizzato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_inserimento_richiesta
	 * @return  the value of tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	public Date getDataInserimentoRichiesta() {
		return dataInserimentoRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_inserimento_richiesta
	 * @param dataInserimentoRichiesta  the value for tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	public void setDataInserimentoRichiesta(Date dataInserimentoRichiesta) {
		this.dataInserimentoRichiesta = dataInserimentoRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_ultima_modifica
	 * @return  the value of tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	public Date getDataUltimaModifica() {
		return dataUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_ultima_modifica
	 * @param dataUltimaModifica  the value for tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	public void setDataUltimaModifica(Date dataUltimaModifica) {
		this.dataUltimaModifica = dataUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.utente_ultima_modifica
	 * @return  the value of tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	public String getUtenteUltimaModifica() {
		return utenteUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.utente_ultima_modifica
	 * @param utenteUltimaModifica  the value for tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	public void setUtenteUltimaModifica(String utenteUltimaModifica) {
		this.utenteUltimaModifica = utenteUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_test
	 * @return  the value of tampone.data_test
	 * @mbg.generated
	 */
	public Date getDataTest() {
		return dataTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_test
	 * @param dataTest  the value for tampone.data_test
	 * @mbg.generated
	 */
	public void setDataTest(Date dataTest) {
		this.dataTest = dataTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.medico_richiedente
	 * @return  the value of tampone.medico_richiedente
	 * @mbg.generated
	 */
	public String getMedicoRichiedente() {
		return medicoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.medico_richiedente
	 * @param medicoRichiedente  the value for tampone.medico_richiedente
	 * @mbg.generated
	 */
	public void setMedicoRichiedente(String medicoRichiedente) {
		this.medicoRichiedente = medicoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.contatto_richiedente
	 * @return  the value of tampone.contatto_richiedente
	 * @mbg.generated
	 */
	public String getContattoRichiedente() {
		return contattoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.contatto_richiedente
	 * @param contattoRichiedente  the value for tampone.contatto_richiedente
	 * @mbg.generated
	 */
	public void setContattoRichiedente(String contattoRichiedente) {
		this.contattoRichiedente = contattoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.tampone_motivo_id
	 * @return  the value of tampone.tampone_motivo_id
	 * @mbg.generated
	 */
	public Integer getTamponeMotivoId() {
		return tamponeMotivoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.tampone_motivo_id
	 * @param tamponeMotivoId  the value for tampone.tampone_motivo_id
	 * @mbg.generated
	 */
	public void setTamponeMotivoId(Integer tamponeMotivoId) {
		this.tamponeMotivoId = tamponeMotivoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_univoco
	 * @return  the value of tampone.id_univoco
	 * @mbg.generated
	 */
	public String getIdUnivoco() {
		return idUnivoco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_univoco
	 * @param idUnivoco  the value for tampone.id_univoco
	 * @mbg.generated
	 */
	public void setIdUnivoco(String idUnivoco) {
		this.idUnivoco = idUnivoco;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_prelievo_prevista
	 * @return  the value of tampone.data_prelievo_prevista
	 * @mbg.generated
	 */
	public Date getDataPrelievoPrevista() {
		return dataPrelievoPrevista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_prelievo_prevista
	 * @param dataPrelievoPrevista  the value for tampone.data_prelievo_prevista
	 * @mbg.generated
	 */
	public void setDataPrelievoPrevista(Date dataPrelievoPrevista) {
		this.dataPrelievoPrevista = dataPrelievoPrevista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_laboratorio_competenza
	 * @return  the value of tampone.id_laboratorio_competenza
	 * @mbg.generated
	 */
	public Integer getIdLaboratorioCompetenza() {
		return idLaboratorioCompetenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_laboratorio_competenza
	 * @param idLaboratorioCompetenza  the value for tampone.id_laboratorio_competenza
	 * @mbg.generated
	 */
	public void setIdLaboratorioCompetenza(Integer idLaboratorioCompetenza) {
		this.idLaboratorioCompetenza = idLaboratorioCompetenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_laboratorio_effettivo
	 * @return  the value of tampone.id_laboratorio_effettivo
	 * @mbg.generated
	 */
	public Integer getIdLaboratorioEffettivo() {
		return idLaboratorioEffettivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_laboratorio_effettivo
	 * @param idLaboratorioEffettivo  the value for tampone.id_laboratorio_effettivo
	 * @mbg.generated
	 */
	public void setIdLaboratorioEffettivo(Integer idLaboratorioEffettivo) {
		this.idLaboratorioEffettivo = idLaboratorioEffettivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_asr
	 * @return  the value of tampone.id_asr
	 * @mbg.generated
	 */
	public Long getIdAsr() {
		return idAsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_asr
	 * @param idAsr  the value for tampone.id_asr
	 * @mbg.generated
	 */
	public void setIdAsr(Long idAsr) {
		this.idAsr = idAsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.hotspot_dispeff_id
	 * @return  the value of tampone.hotspot_dispeff_id
	 * @mbg.generated
	 */
	public Long getHotspotDispeffId() {
		return hotspotDispeffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.hotspot_dispeff_id
	 * @param hotspotDispeffId  the value for tampone.hotspot_dispeff_id
	 * @mbg.generated
	 */
	public void setHotspotDispeffId(Long hotspotDispeffId) {
		this.hotspotDispeffId = hotspotDispeffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.criterio_epidemiologico_id
	 * @return  the value of tampone.criterio_epidemiologico_id
	 * @mbg.generated
	 */
	public Integer getCriterioEpidemiologicoId() {
		return criterioEpidemiologicoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.criterio_epidemiologico_id
	 * @param criterioEpidemiologicoId  the value for tampone.criterio_epidemiologico_id
	 * @mbg.generated
	 */
	public void setCriterioEpidemiologicoId(Integer criterioEpidemiologicoId) {
		this.criterioEpidemiologicoId = criterioEpidemiologicoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.test_tipo_id
	 * @return  the value of tampone.test_tipo_id
	 * @mbg.generated
	 */
	public Integer getTestTipoId() {
		return testTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.test_tipo_id
	 * @param testTipoId  the value for tampone.test_tipo_id
	 * @mbg.generated
	 */
	public void setTestTipoId(Integer testTipoId) {
		this.testTipoId = testTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.medico_refertante
	 * @return  the value of tampone.medico_refertante
	 * @mbg.generated
	 */
	public String getMedicoRefertante() {
		return medicoRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.medico_refertante
	 * @param medicoRefertante  the value for tampone.medico_refertante
	 * @mbg.generated
	 */
	public void setMedicoRefertante(String medicoRefertante) {
		this.medicoRefertante = medicoRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.luogo_id
	 * @return  the value of tampone.luogo_id
	 * @mbg.generated
	 */
	public Integer getLuogoId() {
		return luogoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.luogo_id
	 * @param luogoId  the value for tampone.luogo_id
	 * @mbg.generated
	 */
	public void setLuogoId(Integer luogoId) {
		this.luogoId = luogoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.tampone_stato_id
	 * @return  the value of tampone.tampone_stato_id
	 * @mbg.generated
	 */
	public Integer getTamponeStatoId() {
		return tamponeStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.tampone_stato_id
	 * @param tamponeStatoId  the value for tampone.tampone_stato_id
	 * @mbg.generated
	 */
	public void setTamponeStatoId(Integer tamponeStatoId) {
		this.tamponeStatoId = tamponeStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_prelievo_effettiva
	 * @return  the value of tampone.data_prelievo_effettiva
	 * @mbg.generated
	 */
	public Date getDataPrelievoEffettiva() {
		return dataPrelievoEffettiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_prelievo_effettiva
	 * @param dataPrelievoEffettiva  the value for tampone.data_prelievo_effettiva
	 * @mbg.generated
	 */
	public void setDataPrelievoEffettiva(Date dataPrelievoEffettiva) {
		this.dataPrelievoEffettiva = dataPrelievoEffettiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.test_rapido_jrc_id
	 * @return  the value of tampone.test_rapido_jrc_id
	 * @mbg.generated
	 */
	public Integer getTestRapidoJrcId() {
		return testRapidoJrcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.test_rapido_jrc_id
	 * @param testRapidoJrcId  the value for tampone.test_rapido_jrc_id
	 * @mbg.generated
	 */
	public void setTestRapidoJrcId(Integer testRapidoJrcId) {
		this.testRapidoJrcId = testRapidoJrcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_creazione
	 * @return  the value of tampone.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_creazione
	 * @param dataCreazione  the value for tampone.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_modifica
	 * @return  the value of tampone.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_modifica
	 * @param dataModifica  the value for tampone.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.webapp_richiedente
	 * @return  the value of tampone.webapp_richiedente
	 * @mbg.generated
	 */
	public String getWebappRichiedente() {
		return webappRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.webapp_richiedente
	 * @param webappRichiedente  the value for tampone.webapp_richiedente
	 * @mbg.generated
	 */
	public void setWebappRichiedente(String webappRichiedente) {
		this.webappRichiedente = webappRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_profilo_richiedente
	 * @return  the value of tampone.id_profilo_richiedente
	 * @mbg.generated
	 */
	public Integer getIdProfiloRichiedente() {
		return idProfiloRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_profilo_richiedente
	 * @param idProfiloRichiedente  the value for tampone.id_profilo_richiedente
	 * @mbg.generated
	 */
	public void setIdProfiloRichiedente(Integer idProfiloRichiedente) {
		this.idProfiloRichiedente = idProfiloRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.ruolo_richiedente
	 * @return  the value of tampone.ruolo_richiedente
	 * @mbg.generated
	 */
	public String getRuoloRichiedente() {
		return ruoloRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.ruolo_richiedente
	 * @param ruoloRichiedente  the value for tampone.ruolo_richiedente
	 * @mbg.generated
	 */
	public void setRuoloRichiedente(String ruoloRichiedente) {
		this.ruoloRichiedente = ruoloRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.utente_richiedente
	 * @return  the value of tampone.utente_richiedente
	 * @mbg.generated
	 */
	public String getUtenteRichiedente() {
		return utenteRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.utente_richiedente
	 * @param utenteRichiedente  the value for tampone.utente_richiedente
	 * @mbg.generated
	 */
	public void setUtenteRichiedente(String utenteRichiedente) {
		this.utenteRichiedente = utenteRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_ente_richiedente
	 * @return  the value of tampone.id_ente_richiedente
	 * @mbg.generated
	 */
	public Integer getIdEnteRichiedente() {
		return idEnteRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_ente_richiedente
	 * @param idEnteRichiedente  the value for tampone.id_ente_richiedente
	 * @mbg.generated
	 */
	public void setIdEnteRichiedente(Integer idEnteRichiedente) {
		this.idEnteRichiedente = idEnteRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_struttura_richiedente
	 * @return  the value of tampone.id_struttura_richiedente
	 * @mbg.generated
	 */
	public String getIdStrutturaRichiedente() {
		return idStrutturaRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_struttura_richiedente
	 * @param idStrutturaRichiedente  the value for tampone.id_struttura_richiedente
	 * @mbg.generated
	 */
	public void setIdStrutturaRichiedente(String idStrutturaRichiedente) {
		this.idStrutturaRichiedente = idStrutturaRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_area_richiedente
	 * @return  the value of tampone.id_area_richiedente
	 * @mbg.generated
	 */
	public Integer getIdAreaRichiedente() {
		return idAreaRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_area_richiedente
	 * @param idAreaRichiedente  the value for tampone.id_area_richiedente
	 * @mbg.generated
	 */
	public void setIdAreaRichiedente(Integer idAreaRichiedente) {
		this.idAreaRichiedente = idAreaRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.webapp_refertante
	 * @return  the value of tampone.webapp_refertante
	 * @mbg.generated
	 */
	public String getWebappRefertante() {
		return webappRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.webapp_refertante
	 * @param webappRefertante  the value for tampone.webapp_refertante
	 * @mbg.generated
	 */
	public void setWebappRefertante(String webappRefertante) {
		this.webappRefertante = webappRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_profilo_refertante
	 * @return  the value of tampone.id_profilo_refertante
	 * @mbg.generated
	 */
	public Integer getIdProfiloRefertante() {
		return idProfiloRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_profilo_refertante
	 * @param idProfiloRefertante  the value for tampone.id_profilo_refertante
	 * @mbg.generated
	 */
	public void setIdProfiloRefertante(Integer idProfiloRefertante) {
		this.idProfiloRefertante = idProfiloRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.ruolo_refertante
	 * @return  the value of tampone.ruolo_refertante
	 * @mbg.generated
	 */
	public String getRuoloRefertante() {
		return ruoloRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.ruolo_refertante
	 * @param ruoloRefertante  the value for tampone.ruolo_refertante
	 * @mbg.generated
	 */
	public void setRuoloRefertante(String ruoloRefertante) {
		this.ruoloRefertante = ruoloRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.utente_refertante
	 * @return  the value of tampone.utente_refertante
	 * @mbg.generated
	 */
	public String getUtenteRefertante() {
		return utenteRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.utente_refertante
	 * @param utenteRefertante  the value for tampone.utente_refertante
	 * @mbg.generated
	 */
	public void setUtenteRefertante(String utenteRefertante) {
		this.utenteRefertante = utenteRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_ente_refertante
	 * @return  the value of tampone.id_ente_refertante
	 * @mbg.generated
	 */
	public Integer getIdEnteRefertante() {
		return idEnteRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_ente_refertante
	 * @param idEnteRefertante  the value for tampone.id_ente_refertante
	 * @mbg.generated
	 */
	public void setIdEnteRefertante(Integer idEnteRefertante) {
		this.idEnteRefertante = idEnteRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_struttura_refertante
	 * @return  the value of tampone.id_struttura_refertante
	 * @mbg.generated
	 */
	public String getIdStrutturaRefertante() {
		return idStrutturaRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_struttura_refertante
	 * @param idStrutturaRefertante  the value for tampone.id_struttura_refertante
	 * @mbg.generated
	 */
	public void setIdStrutturaRefertante(String idStrutturaRefertante) {
		this.idStrutturaRefertante = idStrutturaRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_area_refertante
	 * @return  the value of tampone.id_area_refertante
	 * @mbg.generated
	 */
	public Integer getIdAreaRefertante() {
		return idAreaRefertante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_area_refertante
	 * @param idAreaRefertante  the value for tampone.id_area_refertante
	 * @mbg.generated
	 */
	public void setIdAreaRefertante(Integer idAreaRefertante) {
		this.idAreaRefertante = idAreaRefertante;
	}
}