/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class TamponeMotivo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.tampone_motivo_id
	 * @mbg.generated
	 */
	private Integer tamponeMotivoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.tampone_motivo_cod
	 * @mbg.generated
	 */
	private String tamponeMotivoCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.tampone_motivo_desc
	 * @mbg.generated
	 */
	private String tamponeMotivoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_tampone_motivo.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.tampone_motivo_id
	 * @return  the value of d_tampone_motivo.tampone_motivo_id
	 * @mbg.generated
	 */
	public Integer getTamponeMotivoId() {
		return tamponeMotivoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.tampone_motivo_id
	 * @param tamponeMotivoId  the value for d_tampone_motivo.tampone_motivo_id
	 * @mbg.generated
	 */
	public void setTamponeMotivoId(Integer tamponeMotivoId) {
		this.tamponeMotivoId = tamponeMotivoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.tampone_motivo_cod
	 * @return  the value of d_tampone_motivo.tampone_motivo_cod
	 * @mbg.generated
	 */
	public String getTamponeMotivoCod() {
		return tamponeMotivoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.tampone_motivo_cod
	 * @param tamponeMotivoCod  the value for d_tampone_motivo.tampone_motivo_cod
	 * @mbg.generated
	 */
	public void setTamponeMotivoCod(String tamponeMotivoCod) {
		this.tamponeMotivoCod = tamponeMotivoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.tampone_motivo_desc
	 * @return  the value of d_tampone_motivo.tampone_motivo_desc
	 * @mbg.generated
	 */
	public String getTamponeMotivoDesc() {
		return tamponeMotivoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.tampone_motivo_desc
	 * @param tamponeMotivoDesc  the value for d_tampone_motivo.tampone_motivo_desc
	 * @mbg.generated
	 */
	public void setTamponeMotivoDesc(String tamponeMotivoDesc) {
		this.tamponeMotivoDesc = tamponeMotivoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.validita_inizio
	 * @return  the value of d_tampone_motivo.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.validita_inizio
	 * @param validitaInizio  the value for d_tampone_motivo.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.validita_fine
	 * @return  the value of d_tampone_motivo.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.validita_fine
	 * @param validitaFine  the value for d_tampone_motivo.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.utente_operazione
	 * @return  the value of d_tampone_motivo.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.utente_operazione
	 * @param utenteOperazione  the value for d_tampone_motivo.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.data_creazione
	 * @return  the value of d_tampone_motivo.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.data_creazione
	 * @param dataCreazione  the value for d_tampone_motivo.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.data_modifica
	 * @return  the value of d_tampone_motivo.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.data_modifica
	 * @param dataModifica  the value for d_tampone_motivo.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_tampone_motivo.data_cancellazione
	 * @return  the value of d_tampone_motivo.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_tampone_motivo.data_cancellazione
	 * @param dataCancellazione  the value for d_tampone_motivo.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}