/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

import java.util.Date;

public class Test {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_id
	 * @mbg.generated
	 */
	private Long testId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_data_esecuzione
	 * @mbg.generated
	 */
	private Date testDataEsecuzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_range_riferimento
	 * @mbg.generated
	 */
	private String testRangeRiferimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_valore
	 * @mbg.generated
	 */
	private String testValore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_unita_misura
	 * @mbg.generated
	 */
	private String testUnitaMisura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_codice_esito
	 * @mbg.generated
	 */
	private String testCodiceEsito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_laboratorio_desc
	 * @mbg.generated
	 */
	private String testLaboratorioDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_programma
	 * @mbg.generated
	 */
	private String testProgramma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id_soggetto
	 * @mbg.generated
	 */
	private Long idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_esito_id
	 * @mbg.generated
	 */
	private Integer testEsitoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_tipo_id
	 * @mbg.generated
	 */
	private Integer testTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_richiesta_tipo_id
	 * @mbg.generated
	 */
	private Integer testRichiestaTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.intfrdet_id
	 * @mbg.generated
	 */
	private Integer intfrdetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_stato_id
	 * @mbg.generated
	 */
	private Integer testStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.data_prelievo_effettiva
	 * @mbg.generated
	 */
	private Date dataPrelievoEffettiva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.test_rapido_jrc_id
	 * @mbg.generated
	 */
	private Integer testRapidoJrcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.webapp_operazione
	 * @mbg.generated
	 */
	private String webappOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id_profilo_operazione
	 * @mbg.generated
	 */
	private Integer idProfiloOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.ruolo_operazione
	 * @mbg.generated
	 */
	private String ruoloOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id_ente_operazione
	 * @mbg.generated
	 */
	private Integer idEnteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id_struttura_operazione
	 * @mbg.generated
	 */
	private String idStrutturaOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test.id_area_operazione
	 * @mbg.generated
	 */
	private Integer idAreaOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_id
	 * @return  the value of test.test_id
	 * @mbg.generated
	 */
	public Long getTestId() {
		return testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_id
	 * @param testId  the value for test.test_id
	 * @mbg.generated
	 */
	public void setTestId(Long testId) {
		this.testId = testId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_data_esecuzione
	 * @return  the value of test.test_data_esecuzione
	 * @mbg.generated
	 */
	public Date getTestDataEsecuzione() {
		return testDataEsecuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_data_esecuzione
	 * @param testDataEsecuzione  the value for test.test_data_esecuzione
	 * @mbg.generated
	 */
	public void setTestDataEsecuzione(Date testDataEsecuzione) {
		this.testDataEsecuzione = testDataEsecuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_range_riferimento
	 * @return  the value of test.test_range_riferimento
	 * @mbg.generated
	 */
	public String getTestRangeRiferimento() {
		return testRangeRiferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_range_riferimento
	 * @param testRangeRiferimento  the value for test.test_range_riferimento
	 * @mbg.generated
	 */
	public void setTestRangeRiferimento(String testRangeRiferimento) {
		this.testRangeRiferimento = testRangeRiferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_valore
	 * @return  the value of test.test_valore
	 * @mbg.generated
	 */
	public String getTestValore() {
		return testValore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_valore
	 * @param testValore  the value for test.test_valore
	 * @mbg.generated
	 */
	public void setTestValore(String testValore) {
		this.testValore = testValore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_unita_misura
	 * @return  the value of test.test_unita_misura
	 * @mbg.generated
	 */
	public String getTestUnitaMisura() {
		return testUnitaMisura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_unita_misura
	 * @param testUnitaMisura  the value for test.test_unita_misura
	 * @mbg.generated
	 */
	public void setTestUnitaMisura(String testUnitaMisura) {
		this.testUnitaMisura = testUnitaMisura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_codice_esito
	 * @return  the value of test.test_codice_esito
	 * @mbg.generated
	 */
	public String getTestCodiceEsito() {
		return testCodiceEsito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_codice_esito
	 * @param testCodiceEsito  the value for test.test_codice_esito
	 * @mbg.generated
	 */
	public void setTestCodiceEsito(String testCodiceEsito) {
		this.testCodiceEsito = testCodiceEsito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_laboratorio_desc
	 * @return  the value of test.test_laboratorio_desc
	 * @mbg.generated
	 */
	public String getTestLaboratorioDesc() {
		return testLaboratorioDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_laboratorio_desc
	 * @param testLaboratorioDesc  the value for test.test_laboratorio_desc
	 * @mbg.generated
	 */
	public void setTestLaboratorioDesc(String testLaboratorioDesc) {
		this.testLaboratorioDesc = testLaboratorioDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_programma
	 * @return  the value of test.test_programma
	 * @mbg.generated
	 */
	public String getTestProgramma() {
		return testProgramma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_programma
	 * @param testProgramma  the value for test.test_programma
	 * @mbg.generated
	 */
	public void setTestProgramma(String testProgramma) {
		this.testProgramma = testProgramma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id_soggetto
	 * @return  the value of test.id_soggetto
	 * @mbg.generated
	 */
	public Long getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id_soggetto
	 * @param idSoggetto  the value for test.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Long idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_esito_id
	 * @return  the value of test.test_esito_id
	 * @mbg.generated
	 */
	public Integer getTestEsitoId() {
		return testEsitoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_esito_id
	 * @param testEsitoId  the value for test.test_esito_id
	 * @mbg.generated
	 */
	public void setTestEsitoId(Integer testEsitoId) {
		this.testEsitoId = testEsitoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_tipo_id
	 * @return  the value of test.test_tipo_id
	 * @mbg.generated
	 */
	public Integer getTestTipoId() {
		return testTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_tipo_id
	 * @param testTipoId  the value for test.test_tipo_id
	 * @mbg.generated
	 */
	public void setTestTipoId(Integer testTipoId) {
		this.testTipoId = testTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_richiesta_tipo_id
	 * @return  the value of test.test_richiesta_tipo_id
	 * @mbg.generated
	 */
	public Integer getTestRichiestaTipoId() {
		return testRichiestaTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_richiesta_tipo_id
	 * @param testRichiestaTipoId  the value for test.test_richiesta_tipo_id
	 * @mbg.generated
	 */
	public void setTestRichiestaTipoId(Integer testRichiestaTipoId) {
		this.testRichiestaTipoId = testRichiestaTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.intfrdet_id
	 * @return  the value of test.intfrdet_id
	 * @mbg.generated
	 */
	public Integer getIntfrdetId() {
		return intfrdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.intfrdet_id
	 * @param intfrdetId  the value for test.intfrdet_id
	 * @mbg.generated
	 */
	public void setIntfrdetId(Integer intfrdetId) {
		this.intfrdetId = intfrdetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.utente_operazione
	 * @return  the value of test.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.utente_operazione
	 * @param utenteOperazione  the value for test.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.data_creazione
	 * @return  the value of test.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.data_creazione
	 * @param dataCreazione  the value for test.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.data_modifica
	 * @return  the value of test.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.data_modifica
	 * @param dataModifica  the value for test.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.data_cancellazione
	 * @return  the value of test.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.data_cancellazione
	 * @param dataCancellazione  the value for test.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_stato_id
	 * @return  the value of test.test_stato_id
	 * @mbg.generated
	 */
	public Integer getTestStatoId() {
		return testStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_stato_id
	 * @param testStatoId  the value for test.test_stato_id
	 * @mbg.generated
	 */
	public void setTestStatoId(Integer testStatoId) {
		this.testStatoId = testStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.data_prelievo_effettiva
	 * @return  the value of test.data_prelievo_effettiva
	 * @mbg.generated
	 */
	public Date getDataPrelievoEffettiva() {
		return dataPrelievoEffettiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.data_prelievo_effettiva
	 * @param dataPrelievoEffettiva  the value for test.data_prelievo_effettiva
	 * @mbg.generated
	 */
	public void setDataPrelievoEffettiva(Date dataPrelievoEffettiva) {
		this.dataPrelievoEffettiva = dataPrelievoEffettiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.test_rapido_jrc_id
	 * @return  the value of test.test_rapido_jrc_id
	 * @mbg.generated
	 */
	public Integer getTestRapidoJrcId() {
		return testRapidoJrcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.test_rapido_jrc_id
	 * @param testRapidoJrcId  the value for test.test_rapido_jrc_id
	 * @mbg.generated
	 */
	public void setTestRapidoJrcId(Integer testRapidoJrcId) {
		this.testRapidoJrcId = testRapidoJrcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.webapp_operazione
	 * @return  the value of test.webapp_operazione
	 * @mbg.generated
	 */
	public String getWebappOperazione() {
		return webappOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.webapp_operazione
	 * @param webappOperazione  the value for test.webapp_operazione
	 * @mbg.generated
	 */
	public void setWebappOperazione(String webappOperazione) {
		this.webappOperazione = webappOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id_profilo_operazione
	 * @return  the value of test.id_profilo_operazione
	 * @mbg.generated
	 */
	public Integer getIdProfiloOperazione() {
		return idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id_profilo_operazione
	 * @param idProfiloOperazione  the value for test.id_profilo_operazione
	 * @mbg.generated
	 */
	public void setIdProfiloOperazione(Integer idProfiloOperazione) {
		this.idProfiloOperazione = idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.ruolo_operazione
	 * @return  the value of test.ruolo_operazione
	 * @mbg.generated
	 */
	public String getRuoloOperazione() {
		return ruoloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.ruolo_operazione
	 * @param ruoloOperazione  the value for test.ruolo_operazione
	 * @mbg.generated
	 */
	public void setRuoloOperazione(String ruoloOperazione) {
		this.ruoloOperazione = ruoloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id_ente_operazione
	 * @return  the value of test.id_ente_operazione
	 * @mbg.generated
	 */
	public Integer getIdEnteOperazione() {
		return idEnteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id_ente_operazione
	 * @param idEnteOperazione  the value for test.id_ente_operazione
	 * @mbg.generated
	 */
	public void setIdEnteOperazione(Integer idEnteOperazione) {
		this.idEnteOperazione = idEnteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id_struttura_operazione
	 * @return  the value of test.id_struttura_operazione
	 * @mbg.generated
	 */
	public String getIdStrutturaOperazione() {
		return idStrutturaOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id_struttura_operazione
	 * @param idStrutturaOperazione  the value for test.id_struttura_operazione
	 * @mbg.generated
	 */
	public void setIdStrutturaOperazione(String idStrutturaOperazione) {
		this.idStrutturaOperazione = idStrutturaOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test.id_area_operazione
	 * @return  the value of test.id_area_operazione
	 * @mbg.generated
	 */
	public Integer getIdAreaOperazione() {
		return idAreaOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test.id_area_operazione
	 * @param idAreaOperazione  the value for test.id_area_operazione
	 * @mbg.generated
	 */
	public void setIdAreaOperazione(Integer idAreaOperazione) {
		this.idAreaOperazione = idAreaOperazione;
	}
}