/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto;

public class TipoEvento {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_tipo_evento.id_tipo_evento
     *
     * @mbg.generated
     */
    private Integer idTipoEvento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_tipo_evento.desc_tipo_evento
     *
     * @mbg.generated
     */
    private String descTipoEvento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_tipo_evento.segno
     *
     * @mbg.generated
     */
    private String segno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_tipo_evento.id_tipo_evento
     *
     * @return the value of d_tipo_evento.id_tipo_evento
     *
     * @mbg.generated
     */
    public Integer getIdTipoEvento() {
        return idTipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_tipo_evento.id_tipo_evento
     *
     * @param idTipoEvento the value for d_tipo_evento.id_tipo_evento
     *
     * @mbg.generated
     */
    public void setIdTipoEvento(Integer idTipoEvento) {
        this.idTipoEvento = idTipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_tipo_evento.desc_tipo_evento
     *
     * @return the value of d_tipo_evento.desc_tipo_evento
     *
     * @mbg.generated
     */
    public String getDescTipoEvento() {
        return descTipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_tipo_evento.desc_tipo_evento
     *
     * @param descTipoEvento the value for d_tipo_evento.desc_tipo_evento
     *
     * @mbg.generated
     */
    public void setDescTipoEvento(String descTipoEvento) {
        this.descTipoEvento = descTipoEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_tipo_evento.segno
     *
     * @return the value of d_tipo_evento.segno
     *
     * @mbg.generated
     */
    public String getSegno() {
        return segno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_tipo_evento.segno
     *
     * @param segno the value for d_tipo_evento.segno
     *
     * @mbg.generated
     */
    public void setSegno(String segno) {
        this.segno = segno;
    }
}