/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2023-02-08T11:57:16.292+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "AAEPException", targetNamespace = "http://business.aaeporch.aaep.csi.it/")
public class AAEPException_Exception extends Exception {
    
    private it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.AAEPException aaepException;

    public AAEPException_Exception() {
        super();
    }
    
    public AAEPException_Exception(String message) {
        super(message);
    }
    
    public AAEPException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AAEPException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.AAEPException aaepException) {
        super(message);
        this.aaepException = aaepException;
    }

    public AAEPException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.AAEPException aaepException, Throwable cause) {
        super(message, cause);
        this.aaepException = aaepException;
    }

    public it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.AAEPException getFaultInfo() {
        return this.aaepException;
    }
}
