/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2023-02-08T11:57:16.301+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "OrchestratoreImplService", 
                  wsdlLocation = "file:/C:/Users/ALESSA~1.BUS/AppData/Local/Temp/tempdir8301785145176777839.tmp/OrchestratoreService_1.wsdl",
                  targetNamespace = "http://business.aaeporch.aaep.csi.it/") 
public class OrchestratoreImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://business.aaeporch.aaep.csi.it/", "OrchestratoreImplService");
    public final static QName OrchestratoreImplPort = new QName("http://business.aaeporch.aaep.csi.it/", "OrchestratoreImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ALESSA~1.BUS/AppData/Local/Temp/tempdir8301785145176777839.tmp/OrchestratoreService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrchestratoreImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ALESSA~1.BUS/AppData/Local/Temp/tempdir8301785145176777839.tmp/OrchestratoreService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrchestratoreImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrchestratoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrchestratoreImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrchestratoreImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrchestratoreImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrchestratoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrchestratoreIntf
     */
    @WebEndpoint(name = "OrchestratoreImplPort")
    public OrchestratoreIntf getOrchestratoreImplPort() {
        return super.getPort(OrchestratoreImplPort, OrchestratoreIntf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrchestratoreIntf
     */
    @WebEndpoint(name = "OrchestratoreImplPort")
    public OrchestratoreIntf getOrchestratoreImplPort(WebServiceFeature... features) {
        return super.getPort(OrchestratoreImplPort, OrchestratoreIntf.class, features);
    }

}
