/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2023-02-08T11:57:16.286+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "UnrecoverableException", targetNamespace = "http://business.aaeporch.aaep.csi.it/")
public class UnrecoverableException_Exception extends Exception {
    
    private it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UnrecoverableException unrecoverableException;

    public UnrecoverableException_Exception() {
        super();
    }
    
    public UnrecoverableException_Exception(String message) {
        super(message);
    }
    
    public UnrecoverableException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnrecoverableException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UnrecoverableException unrecoverableException) {
        super(message);
        this.unrecoverableException = unrecoverableException;
    }

    public UnrecoverableException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UnrecoverableException unrecoverableException, Throwable cause) {
        super(message, cause);
        this.unrecoverableException = unrecoverableException;
    }

    public it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UnrecoverableException getFaultInfo() {
        return this.unrecoverableException;
    }
}
