/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2023-02-08T11:57:16.283+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "UserException", targetNamespace = "http://business.aaeporch.aaep.csi.it/")
public class UserException_Exception extends Exception {
    
    private it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UserException userException;

    public UserException_Exception() {
        super();
    }
    
    public UserException_Exception(String message) {
        super(message);
    }
    
    public UserException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UserException userException) {
        super(message);
        this.userException = userException;
    }

    public UserException_Exception(String message, it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UserException userException, Throwable cause) {
        super(message, cause);
        this.userException = userException;
    }

    public it.csi.gescovid.gestruttureresapi.integration.orchestratoreservice.impl.UserException getFaultInfo() {
        return this.userException;
    }
}
