/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.gescovid.gestruttureresapi.integration.mef.mef;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-06-10T10:56:57.817+02:00
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "InterrogaMefCovid",
                  wsdlLocation = "https://portale.ruparpiemonte.it/sanitxcovid/AURA.WS.InterrogaMefCovid.cls?wsdl",
                  targetNamespace = "http://InterrogaMefCovid.central.services.auraws.aura.csi.it")
public class InterrogaMefCovid_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://InterrogaMefCovid.central.services.auraws.aura.csi.it", "InterrogaMefCovid");
    public final static QName InterrogaMefCovidSoap = new QName("http://InterrogaMefCovid.central.services.auraws.aura.csi.it", "InterrogaMefCovidSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://portale.ruparpiemonte.it/sanitxcovid/AURA.WS.InterrogaMefCovid.cls?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InterrogaMefCovid_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://portale.ruparpiemonte.it/sanitxcovid/AURA.WS.InterrogaMefCovid.cls?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InterrogaMefCovid_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterrogaMefCovid_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterrogaMefCovid_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InterrogaMefCovid_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InterrogaMefCovid_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterrogaMefCovid_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InterrogaMefCovidSoap
     */
    @WebEndpoint(name = "InterrogaMefCovidSoap")
    public InterrogaMefCovidSoap getInterrogaMefCovidSoap() {
        return super.getPort(InterrogaMefCovidSoap, InterrogaMefCovidSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterrogaMefCovidSoap
     */
    @WebEndpoint(name = "InterrogaMefCovidSoap")
    public InterrogaMefCovidSoap getInterrogaMefCovidSoap(WebServiceFeature... features) {
        return super.getPort(InterrogaMefCovidSoap, InterrogaMefCovidSoap.class, features);
    }

}
