/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.extended;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto.extended.CovidrsaRStrutturaWelfareFileExt;
import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.generated.BaseCovidrsaRStrutturaWelfareFileMapper;
import it.csi.gescovid.gestruttureresapi.dto.CovidrsaRStrutturaWelfareFile;

public interface CovidrsaRStrutturaWelfareFileMapper extends BaseCovidrsaRStrutturaWelfareFileMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table covidrsa_r_struttura_welfare_file
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "crswf.str_welfare_file_id, crswf.str_welfare_id, crswf.file_id, crswf.validita_inizio, crswf.validita_fine, ",
        "crswf.utente_operazione, crswf.data_creazione, crswf.data_modifica, crswf.data_cancellazione, crswf.firma_verificata, crswf.file_tipo_id, ",
        "cdwft.file_tipo_cod, cdwft.file_tipo_desc, cdwft.file_tipo_gruppo ",
        "from covidrsa_r_struttura_welfare_file crswf ",
        "left join covidrsa_d_welfare_file_tipo cdwft on cdwft.file_tipo_id = crswf.file_tipo_id ",
        "where crswf.str_welfare_id = #{strWelfareFileId,jdbcType=INTEGER} ",
        "and crswf.data_cancellazione is null ",
        "and now() between crswf.validita_inizio and coalesce(crswf.validita_fine, now())  "
    })
    @Results({
        @Result(column="str_welfare_file_id", property="strWelfareFileId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="str_welfare_id", property="strWelfareId", jdbcType=JdbcType.INTEGER),
        @Result(column="file_id", property="fileId", jdbcType=JdbcType.INTEGER),
        @Result(column="validita_inizio", property="validitaInizio", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="validita_fine", property="validitaFine", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="utente_operazione", property="utenteOperazione", jdbcType=JdbcType.VARCHAR),
        @Result(column="data_creazione", property="dataCreazione", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data_modifica", property="dataModifica", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data_cancellazione", property="dataCancellazione", jdbcType=JdbcType.TIMESTAMP),
        @Result(column = "firma_verificata", property = "firmaVerificata", jdbcType = JdbcType.BIT),
        @Result(column = "file_tipo_id", property = "fileTipoId", jdbcType = JdbcType.INTEGER),
        @Result(column = "file_tipo_cod", property = "fileTipoCod", jdbcType = JdbcType.VARCHAR),
        @Result(column = "file_tipo_desc", property = "fileTipoDesc", jdbcType = JdbcType.VARCHAR) ,
        @Result(column = "file_tipo_gruppo", property = "fileTipoGruppo", jdbcType = JdbcType.VARCHAR) 
    })
    List<CovidrsaRStrutturaWelfareFileExt> selectByStrWelfareId(Integer strWelfareFileId);

    @Update({
        "update covidrsa_r_struttura_welfare_file",
        "set ",
          "utente_operazione = #{utenteOperazione,jdbcType=VARCHAR}, ",
          "data_modifica = now(), ",
          "data_cancellazione = now() ",
        "where str_welfare_file_id = #{strWelfareFileId,jdbcType=INTEGER} "
    })
    int logicDeletByPrimaryKey(CovidrsaRStrutturaWelfareFile record);
    

    @Insert({ "insert into covidrsa_r_struttura_welfare_file (str_welfare_id, file_id, ",
            "validita_inizio, validita_fine, ", "utente_operazione, data_creazione, ",
            "data_modifica, data_cancellazione, ", "firma_verificata, file_tipo_id)",
            "values (#{strWelfareId,jdbcType=INTEGER}, #{fileId,jdbcType=INTEGER}, ",
            "#{validitaInizio,jdbcType=TIMESTAMP}, #{validitaFine,jdbcType=TIMESTAMP}, ",
            "#{utenteOperazione,jdbcType=VARCHAR}, now(), ",
            "now(), #{dataCancellazione,jdbcType=TIMESTAMP}, ",
            "#{firmaVerificata,jdbcType=BIT}, #{fileTipoId,jdbcType=INTEGER})" })
    @Options(useGeneratedKeys = true, keyProperty = "strWelfareFileId")
    int insert(CovidrsaRStrutturaWelfareFile record);

}
