/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.extended;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto.extended.RsaPostiExt;
import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.generated.BaseCovidrsaTPostiMapper;
import it.csi.gescovid.gestruttureresapi.dto.RsaPostiJson;

public interface RsaPostiMapper extends BaseCovidrsaTPostiMapper {
	
	  @Select({
	        "select",
			"p.posti_num_occupati_paganti, ",
			"p.posti_num_occupati_convenzionati, ",
            "p.posti_num_occupati_dgr23, ",
            "p.posti_num_occupabili_dgr10, ",
	        "p.posti_id, p.posti_num_totali, p.posti_num_occupati, p.posti_num_ospedalizzati, p.posti_num_totali_singole, ",
	        "p.posti_num_singole_residue, p.id_struttura, p.str_categoria_id, p.data_rilevazione, p.accessi_in_ps_num, ",
	        "p.validita_inizio, p.validita_fine, p.utente_operazione, p.data_creazione, p.data_modifica, ",
	        "p.posti_num_occupati_dgr_uomini, p.posti_num_occupati_dgr_donne, p.posti_num_occupabili_dgr_uomini, ",
	        "p.posti_num_occupabili_dgr_donne, p.posti_num_liberi, p.posti_num_occupati_paganti_ss, ",
	        "p.posti_num_sollievo_occupati, p.posti_num_sollievo_liberi, p.posti_num_sollievo_liberi_uomini, ",
	        "p.posti_num_sollievo_liberi_donne, p.posti_num_sollievo_liberi_indiff, p.posti_num_dim_prot_occupati, ",
	        "p.posti_num_dim_prot_liberi, p.posti_num_dim_prot_liberi_uomini, p.posti_num_dim_prot_liberi_donne, ",
	        "p.posti_num_dim_prot_liberi_indiff, p.posti_num_cavs_occupati, p.posti_num_cavs_liberi, ",
	        "p.posti_num_cavs_liberi_uomini, p.posti_num_cavs_liberi_donne, p.posti_num_cavs_liberi_indiff, ",
	        "p.posti_num_lungodeg_occupati, p.posti_num_lungodeg_liberi, p.posti_num_lungodeg_liberi_uomini, ",
	        "p.posti_num_lungodeg_liberi_donne, p.posti_num_lungodeg_liberi_indiff, p.posti_num_hospice_occupati, ",
	        "p.posti_num_hospice_liberi, p.posti_num_hospice_liberi_uomini, p.posti_num_hospice_liberi_donne, ",
	        "p.posti_num_hospice_liberi_indiff, " ,
            "p.posti_num_liberi_uomini, p.posti_num_liberi_donne, p.posti_num_liberi_indiff, ",
	        "p.data_cancellazione, p.data_visibilita, str_categoria_desc, concat('Dal ',to_char(p.validita_inizio, 'dd/mm/yyyy'),' al ' ,to_char(p.validita_fine, 'dd/mm/yyyy') ) as dati_validi, ",
	        " (coalesce(p.posti_num_totali, 0) + coalesce(p.posti_num_occupati, 0) +coalesce(p.posti_num_ospedalizzati, 0) + coalesce(p.posti_num_totali_singole, 0) + coalesce(p.posti_num_singole_residue, 0)) as totale ",
	        "from covidrsa_t_posti p ",
	        "left join covidrsa_d_struttura_categoria cs on p.str_categoria_id = cs.str_categoria_id ",
	        "where p.data_cancellazione is null ",
	        "and p.id_struttura=#{idStruttura,jdbcType=VARCHAR}  ",
	        "order by p.data_rilevazione desc  "
	    })
	    @Results({
	        @Result(column="posti_id", property="postiId", jdbcType=JdbcType.INTEGER, id=true),
	        @Result(column="posti_num_totali", property="postiNumTotali", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati", property="postiNumOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_ospedalizzati", property="postiNumOspedalizzati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_totali_singole", property="postiNumTotaliSingole", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_singole_residue", property="postiNumSingoleResidue", jdbcType=JdbcType.INTEGER),
	        @Result(column="id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
	        @Result(column="str_categoria_id", property="strCategoriaId", jdbcType=JdbcType.INTEGER),
	        @Result(column="data_rilevazione", property="dataRilevazione", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="validita_inizio", property="validitaInizio", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="validita_fine", property="validitaFine", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="utente_operazione", property="utenteOperazione", jdbcType=JdbcType.VARCHAR),
	        @Result(column="data_creazione", property="dataCreazione", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="data_modifica", property="dataModifica", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="data_cancellazione", property="dataCancellazione", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="data_visibilita", property="dataVisibilita", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="dati_validi", property="datiValidi", jdbcType=JdbcType.VARCHAR),
	        @Result(column="str_categoria_desc", property="tipologiaStrutturaDesc", jdbcType=JdbcType.VARCHAR),
	        @Result(column="accessi_in_ps_num", property="accessiInPsNum", jdbcType=JdbcType.INTEGER),
	        @Result(column="totale", property="totale", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_paganti", property="postiNumOccupatiPaganti", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_convenzionati", property="postiNumOccupatiConvenzionati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_dgr23", property="postiNumOccupatiDgr23", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupabili_dgr10", property="postiNumOccupabiliDgr10", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_dgr_uomini", property="postiNumOccupatiDgrUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_dgr_donne", property="postiNumOccupatiDgrDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupabili_dgr_uomini", property="postiNumOccupabiliDgrUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupabili_dgr_donne", property="postiNumOccupabiliDgrDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_liberi", property="postiNumLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_paganti_ss", property="postiNumOccupatiPagantiSs", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_sollievo_occupati", property="postiNumSollievoOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_sollievo_liberi", property="postiNumSollievoLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_sollievo_liberi_uomini", property="postiNumSollievoLiberiUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_sollievo_liberi_donne", property="postiNumSollievoLiberiDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_sollievo_liberi_indiff", property="postiNumSollievoLiberiIndiff", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_dim_prot_occupati", property="postiNumDimProtOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_dim_prot_liberi", property="postiNumDimProtLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_dim_prot_liberi_uomini", property="postiNumDimProtLiberiUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_dim_prot_liberi_donne", property="postiNumDimProtLiberiDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_dim_prot_liberi_indiff", property="postiNumDimProtLiberiIndiff", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_cavs_occupati", property="postiNumCavsOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_cavs_liberi", property="postiNumCavsLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_cavs_liberi_uomini", property="postiNumCavsLiberiUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_cavs_liberi_donne", property="postiNumCavsLiberiDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_cavs_liberi_indiff", property="postiNumCavsLiberiIndiff", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_lungodeg_occupati", property="postiNumLungodegOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_lungodeg_liberi", property="postiNumLungodegLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_lungodeg_liberi_uomini", property="postiNumLungodegLiberiUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_lungodeg_liberi_donne", property="postiNumLungodegLiberiDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_lungodeg_liberi_indiff", property="postiNumLungodegLiberiIndiff", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_hospice_occupati", property="postiNumHospiceOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_hospice_liberi", property="postiNumHospiceLiberi", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_hospice_liberi_uomini", property="postiNumHospiceLiberiUomini", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_hospice_liberi_donne", property="postiNumHospiceLiberiDonne", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_hospice_liberi_indiff", property="postiNumHospiceLiberiIndiff", jdbcType=JdbcType.INTEGER),          
	        @Result(column = "posti_num_liberi_uomini", property = "postiNumLiberiUomini", jdbcType = JdbcType.INTEGER),
            @Result(column = "posti_num_liberi_donne", property = "postiNumLiberiDonne", jdbcType = JdbcType.INTEGER),
            @Result(column = "posti_num_liberi_indiff", property = "postiNumLiberiIndiff", jdbcType = JdbcType.INTEGER)
	    })
	    List<RsaPostiExt> selectValidByIdStruttura(String idStruttura);
	  
	  @Select({
		  "<script>",
	        "select",
	        " case when COALESCE(st.nome, '')  !='' ",
		    " 	 then  st.nome ",
		    "    else ctsi.sti_nome ",
		    "end nome_st, ",
			"p.posti_num_occupati_paganti, ",
			"p.posti_num_occupati_convenzionati, ",
            "p.posti_num_occupati_dgr23, ",
            "p.posti_num_occupabili_dgr10, ",
	        "p.posti_id, p.posti_num_totali, p.posti_num_occupati, p.posti_num_ospedalizzati, p.posti_num_totali_singole, ",
	        "p.posti_num_singole_residue, p.id_struttura, p.str_categoria_id, to_char(p.data_rilevazione, 'dd/mm/yyyy') as data_rilevazione_string , ",
	        "p.validita_inizio, p.validita_fine, p.utente_operazione, p.data_creazione, p.data_modifica, accessi_in_ps_num,",
            "p.posti_num_occupati_dgr_uomini, p.posti_num_occupati_dgr_donne, p.posti_num_occupabili_dgr_uomini, ",
            "p.posti_num_occupabili_dgr_donne, p.posti_num_liberi, p.posti_num_occupati_paganti_ss, ",
            "p.posti_num_sollievo_occupati, p.posti_num_sollievo_liberi, p.posti_num_sollievo_liberi_uomini, ",
            "p.posti_num_sollievo_liberi_donne, p.posti_num_sollievo_liberi_indiff, p.posti_num_dim_prot_occupati, ",
            "p.posti_num_dim_prot_liberi, p.posti_num_dim_prot_liberi_uomini, p.posti_num_dim_prot_liberi_donne, ",
            "p.posti_num_dim_prot_liberi_indiff, p.posti_num_cavs_occupati, p.posti_num_cavs_liberi, ",
            "p.posti_num_cavs_liberi_uomini, p.posti_num_cavs_liberi_donne, p.posti_num_cavs_liberi_indiff, ",
            "p.posti_num_lungodeg_occupati, p.posti_num_lungodeg_liberi, p.posti_num_lungodeg_liberi_uomini, ",
            "p.posti_num_lungodeg_liberi_donne, p.posti_num_lungodeg_liberi_indiff, p.posti_num_hospice_occupati, ",
            "p.posti_num_hospice_liberi, p.posti_num_hospice_liberi_uomini, p.posti_num_hospice_liberi_donne, ",
            "p.posti_num_hospice_liberi_indiff, " ,
            "p.posti_num_liberi_uomini, p.posti_num_liberi_donne, p.posti_num_liberi_indiff, ",
	        "p.data_cancellazione, p.data_visibilita, str_categoria_desc, concat('Dal ',to_char(p.validita_inizio, 'dd/mm/yyyy'),' al ' ,to_char(p.validita_fine, 'dd/mm/yyyy') ) as dati_validi ",
	        "from covidrsa_t_posti p ",
	        "left join covidrsa_d_struttura_categoria cs on p.str_categoria_id = cs.str_categoria_id ",
	        "left join struttura st  on p.id_struttura = st.id_struttura " ,	
	        "left join covidrsa_t_struttura_info ctsi  on ctsi.id_struttura = st.id_struttura " ,
	        "<if test='cfUtente != null'> " , 
	        "left join r_utente_struttura rus on p.id_struttura = rus.id_struttura " ,
	    	"</if>",
	        "where p.data_cancellazione is null ",
	    	"<if test='cfUtente != null'> " ,
	    	"and rus.cf_utente = #{cfUtente, jdbcType=VARCHAR}  ",
	    	"</if>",
	    	"<if test='dataRilevazioneDa != null'> ", 
			" and p.data_rilevazione >= #{dataRilevazioneDa, jdbcType = TIMESTAMP}",
			"</if>",
			"<if test='dataRilevazioneA != null'> ", 
			"and   #{dataRilevazioneA, jdbcType = TIMESTAMP} > p.data_rilevazione ", 
			"</if>",
			"<if test='idStruttura != null'> " ,
	    	"and p.id_struttura = #{idStruttura, jdbcType=VARCHAR}  ",
	    	"</if>",
	        "order by nome_st asc, p.data_rilevazione desc  ",
			"</script>",
	    })
	    @Results({
	        @Result(column="nome_st", property="nomeStruttura", jdbcType=JdbcType.VARCHAR),
	        @Result(column="posti_num_occupati", property="postiNumOccupati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_ospedalizzati", property="postiNumOspedalizzati", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_totali_singole", property="postiNumTotaliSingole", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_singole_residue", property="postiNumSingoleResidue", jdbcType=JdbcType.INTEGER),
	        @Result(column="accessi_in_ps_num", property="accessiInPsNum", jdbcType=JdbcType.INTEGER),
	        @Result(column="data_rilevazione_string", property="dataRilevazioneString", jdbcType=JdbcType.TIMESTAMP),
	        @Result(column="dati_validi", property="datiValidi", jdbcType=JdbcType.VARCHAR),
	        @Result(column="str_categoria_desc", property="tipologiaStrutturaDesc", jdbcType=JdbcType.VARCHAR),
	        @Result(column="posti_num_occupati_paganti", property="postiNumOccupatiPaganti", jdbcType=JdbcType.INTEGER),
	        @Result(column="posti_num_occupati_convenzionati", property="postiNumOccupatiConvenzionati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_liberi", property="postiNumLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_occupati_paganti_ss", property="postiNumOccupatiPagantiSs", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_sollievo_occupati", property="postiNumSollievoOccupati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_sollievo_liberi", property="postiNumSollievoLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_sollievo_liberi_uomini", property="postiNumSollievoLiberiUomini", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_sollievo_liberi_donne", property="postiNumSollievoLiberiDonne", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_sollievo_liberi_indiff", property="postiNumSollievoLiberiIndiff", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_dim_prot_occupati", property="postiNumDimProtOccupati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_dim_prot_liberi", property="postiNumDimProtLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_dim_prot_liberi_uomini", property="postiNumDimProtLiberiUomini", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_dim_prot_liberi_donne", property="postiNumDimProtLiberiDonne", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_dim_prot_liberi_indiff", property="postiNumDimProtLiberiIndiff", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_cavs_occupati", property="postiNumCavsOccupati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_cavs_liberi", property="postiNumCavsLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_cavs_liberi_uomini", property="postiNumCavsLiberiUomini", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_cavs_liberi_donne", property="postiNumCavsLiberiDonne", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_cavs_liberi_indiff", property="postiNumCavsLiberiIndiff", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_lungodeg_occupati", property="postiNumLungodegOccupati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_lungodeg_liberi", property="postiNumLungodegLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_lungodeg_liberi_uomini", property="postiNumLungodegLiberiUomini", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_lungodeg_liberi_donne", property="postiNumLungodegLiberiDonne", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_lungodeg_liberi_indiff", property="postiNumLungodegLiberiIndiff", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_hospice_occupati", property="postiNumHospiceOccupati", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_hospice_liberi", property="postiNumHospiceLiberi", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_hospice_liberi_uomini", property="postiNumHospiceLiberiUomini", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_hospice_liberi_donne", property="postiNumHospiceLiberiDonne", jdbcType=JdbcType.INTEGER),
            @Result(column="posti_num_hospice_liberi_indiff", property="postiNumHospiceLiberiIndiff", jdbcType=JdbcType.INTEGER),
            @Result(column = "posti_num_liberi_uomini", property = "postiNumLiberiUomini", jdbcType = JdbcType.INTEGER),
	        @Result(column = "posti_num_liberi_donne", property = "postiNumLiberiDonne", jdbcType = JdbcType.INTEGER),
	        @Result(column = "posti_num_liberi_indiff", property = "postiNumLiberiIndiff", jdbcType = JdbcType.INTEGER),
	        @Result(column = "posti_num_liberi_uomini", property = "postiNumLiberiUomini", jdbcType = JdbcType.INTEGER),
	        @Result(column = "posti_num_liberi_donne", property = "postiNumLiberiDonne", jdbcType = JdbcType.INTEGER),
	        @Result(column = "posti_num_liberi_indiff", property = "postiNumLiberiIndiff", jdbcType = JdbcType.INTEGER)
})
	    List<RsaPostiJson> selectValidByCfUtenteAndDataRilevazioneDaAndDataRilevazioneAAndIdStruttura(@Param("cfUtente") String cfUtente,
	    		@Param("dataRilevazioneDa") Date dataRilevazioneDa, 
	    		@Param("dataRilevazioneA") Date dataRilevazioneA,
	    		@Param("idStruttura") String idStruttura);
	  
	  

		@Insert({ "INSERT INTO covidrsa_t_posti( ",
			"   id_struttura, ",
			"   str_categoria_id, ",
			"   posti_num_totali, ",
			"   posti_num_occupati, ",
			"   posti_num_ospedalizzati, ",
			"   posti_num_totali_singole, ",
			"   posti_num_singole_residue, ",
			"   posti_num_occupati_paganti, ",
			"   posti_num_occupati_convenzionati, ",
            "   posti_num_occupati_dgr23, ",
            "   posti_num_occupabili_dgr10, ",
			"   accessi_in_ps_num, ",
            "   posti_num_occupati_dgr_uomini, posti_num_occupati_dgr_donne, posti_num_occupabili_dgr_uomini, ",
            "posti_num_occupabili_dgr_donne, posti_num_liberi, posti_num_occupati_paganti_ss, ",
            "posti_num_sollievo_occupati, posti_num_sollievo_liberi, posti_num_sollievo_liberi_uomini, ",
            "posti_num_sollievo_liberi_donne, posti_num_sollievo_liberi_indiff, posti_num_dim_prot_occupati, ",
            "posti_num_dim_prot_liberi, posti_num_dim_prot_liberi_uomini, posti_num_dim_prot_liberi_donne, ",
            "posti_num_dim_prot_liberi_indiff, posti_num_cavs_occupati, posti_num_cavs_liberi, ",
            "posti_num_cavs_liberi_uomini, posti_num_cavs_liberi_donne, posti_num_cavs_liberi_indiff, ",
            "posti_num_lungodeg_occupati, posti_num_lungodeg_liberi, posti_num_lungodeg_liberi_uomini, ",
            "posti_num_lungodeg_liberi_donne, posti_num_lungodeg_liberi_indiff, posti_num_hospice_occupati, ",
            "posti_num_hospice_liberi, posti_num_hospice_liberi_uomini, posti_num_hospice_liberi_donne, ",
            "posti_num_hospice_liberi_indiff, " ,
            "posti_num_liberi_uomini, posti_num_liberi_donne, posti_num_liberi_indiff, ",
			"   data_rilevazione, ",
			"   validita_inizio, ",
			"   validita_fine, ",
			"   utente_operazione ",
			") ",
			"SELECT ",
			"   #{idStruttura, jdbcType=VARCHAR} , ",
			"   #{strCategoriaId, jdbcType=INTEGER}, ",
			"   0,0,0,0,0,0,0,0,0,0,0,0,0,0,",
            "   0,0,0,0,0,0,0,0,0,0,0,0,0,0,",
            "   0,0,0,0,0,0,0,0,0,0,0,0,0, 0,0,0, ",
			"(#{dataRilevazione, jdbcType = DATE})::TIMESTAMP, ",
			"(#{dataRilevazione, jdbcType = DATE})::TIMESTAMP - INTERVAL '7 days', ",
			"(#{dataRilevazione, jdbcType = DATE})::TIMESTAMP - INTERVAL '1 day', ",
			"   #{cfUtente, jdbcType=VARCHAR} ",
			"FROM DUAL ",
			"WHERE NOT EXISTS ( ",
			"   SELECT 1 ",
			"   FROM covidrsa_t_posti ",
			"   WHERE id_struttura = #{idStruttura, jdbcType=VARCHAR} ",
			"     AND str_categoria_id = #{strCategoriaId, jdbcType=INTEGER} ",
			"     AND TRUNC(data_rilevazione) = #{dataRilevazione, jdbcType = DATE} ",
			"     AND data_cancellazione IS NULL ",
			") "})
		int insertDefaultIfNotPresente( @Param("idStruttura") String idStruttura, @Param("strCategoriaId") Integer strCategoriaId, @Param("dataRilevazione") Date dataRilevazione, @Param("cfUtente") String cfUtente);



        @Select({ 
            "SELECT ",
            "  SUM(COALESCE(posti_num_occupati         ,0))+ ",
            "  SUM(COALESCE(posti_num_occupati_dgr23   ,0))+ ",
            "  SUM(COALESCE(posti_num_sollievo_occupati,0))+ ",
            "  SUM(COALESCE(posti_num_dim_prot_occupati,0))+ ",
            "  SUM(COALESCE(posti_num_cavs_occupati    ,0))+ ",
            "  SUM(COALESCE(posti_num_lungodeg_occupati,0))+ ",
            "  SUM(COALESCE(posti_num_hospice_occupati ,0)) ",
            "FROM covidrsa_t_posti p, ",
            "( ",
            "  SELECT MAX(TRUNC(data_rilevazione)) max_data_rilevazione ",
            "  FROM covidrsa_t_posti ",
            "  WHERE data_cancellazione IS NULL ",
            "    AND id_struttura = #{idStruttura, jdbcType=VARCHAR} ",
            ") x ",
            "WHERE p.data_cancellazione IS NULL ",
            "  AND p.id_struttura = #{idStruttura, jdbcType=VARCHAR} ",
            "  AND TRUNC(p.data_rilevazione) = x.max_data_rilevazione "
        })
        Integer selectMaxTamponiForStruttura( @Param("idStruttura") String idStruttura);
}
