/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.extended;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.dto.extended.StrutturaInfoExt;
import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.generated.BaseCovidrsaTStrutturaInfoMapper;
import it.csi.gescovid.gestruttureresapi.business.be.impl.mapper.util.Paginazione;

public interface StrutturaInfoMapper extends BaseCovidrsaTStrutturaInfoMapper {

	@Select({
		"<script>",
		"select count(*) OVER() AS full_count, ",
		"ctsi.sti_id, ctsi.sti_nome, ctsi.sti_indirizzo, ctsi.sti_telefono, ctsi.sti_email, ctsi.sti_mensa_interna_presente, ",
		"ctsi.sti_asmed_mmg, ctsi.sti_asmed_nommg, st.id_struttura, ",
		" case when COALESCE(st.nome, '')  !='' ",
	    " 	 then  st.nome ",
	    "    else ctsi.sti_nome ",
	    "end nome_st, ",
		"ctsi.str_tipo_id, ctsi.str_natura_id, ctsi.str_accreditamento_id, ",
		"ctsi.sti_comune_istat, ctsi.sti_pec, ctsi.sti_dir_str_presente, ctsi.sti_dir_str_nome, ctsi.sti_dir_str_tel_reperibilita, ",
		"ctsi.sti_dir_sanit_presente, ctsi.sti_dir_sanit_nome, ctsi.sti_dir_sanit_tel_reperibilita, ",
		"ctsi.sti_coord_inf_presente, ctsi.sti_coord_inf_nome, ctsi.sti_coord_inf_tel_reperibilita, ",
		"ctsi.validita_inizio, ctsi.validita_fine, ctsi.utente_operazione, ctsi.data_creazione, ctsi.data_modifica, ",
		"ctsi.data_cancellazione, ctsi.sti_email2, ctsi.sti_dir_str_email, ctsi.sti_dir_sanit_email, ctsi.sti_coord_inf_email, ",
		"ctsi.sti_asmed_mista, ctsi.sti_pers_inf_notturno, ctsi.assmed_id, ctsi.sti_atto_autorizzativo, ctsi.sti_titolare_autorizzazione, ",
		"ctsi.str_tipo_utenza_id, ctsi.sti_escludi_struttura, str_tipo_utenza_desc, e.id_ente, e.nome as nome_ente, sn.str_natura_desc, ts.str_tipo_desc, nome_comune, ",
		"str_accreditamento_cod, str_accreditamento_desc, cpr.sigla_prov, ",
        "ctsi.sti_adesione_dgr10, ctsi.sti_abilitato_sollievo, ctsi.sti_abilitato_dim_prot, ctsi.sti_abilitato_cavs, ",
        "ctsi.sti_abilitato_lungodeg, ctsi.sti_abilitato_hospice, ",
        "EXISTS ( ",
        "  SELECT 1 ",
        "  FROM covidrsa_r_struttura_welfare sw ",
        "  JOIN covidrsa_r_struttura_welfare_file swf ON swf.str_welfare_id = sw.str_welfare_id  ",
        "    AND swf.data_cancellazione IS NULL ",
        "    AND swf.validita_fine IS NULL ",
        "  JOIN covidrsa_d_welfare_file_tipo wft ON wft.file_tipo_id = swf.file_tipo_id ",
        "    AND wft.file_tipo_gruppo = 'FIN' ",
        "    AND wft.data_cancellazione is null ",
        "    AND NOW() BETWEEN wft.validita_inizio AND COALESCE(wft.validita_fine, NOW()) ",
        "  WHERE sw.id_struttura = st.id_struttura ",
        "    AND sw.data_cancellazione IS NULL ",
        "    AND sw.validita_fine IS NULL ",
        ") AS adesione_buono_welfare ",
		"from struttura st  " ,
		"left join covidrsa_t_struttura_info ctsi  on ctsi.id_struttura = st.id_struttura " ,
		"                           and now() between ctsi.validita_inizio and coalesce(ctsi.validita_fine, now()) ",
		"                           and ctsi.data_cancellazione is null ",
        "left join ente e on st.id_ente= e.id_ente " ,
        "left join comuni_province_regione cpr on cpr.cod_comune = ctsi.sti_comune_istat " ,
		"left join covidrsa_d_tipo_utenza tu on  tu.str_tipo_utenza_id= ctsi.str_tipo_utenza_id ",
		"left join covidrsa_d_struttura_natura sn on  sn.str_natura_id= ctsi.str_natura_id ",
		"<if test='cfUtente != null'> " , 
		"left join r_utente_struttura rus on rus.id_struttura = st.id_struttura ",
		" AND rus.data_cancellazione IS NULL AND NOW() BETWEEN rus.validita_inizio AND COALESCE(rus.validita_fine,NOW()) " ,
		"</if>",
		" left join covidrsa_d_struttura_tipo ts on ts.str_tipo_id = ctsi.str_tipo_id ",
		" left join comuni c on c.istat_comune = ctsi.sti_comune_istat ",
		" left join covidrsa_d_struttura_accreditamento acc on acc.str_accreditamento_id = ctsi.str_accreditamento_id ",
		"<if test='strCategoriaId != null'> " , 
		" left join covidrsa_r_struttura_categoria rsc on rsc.id_struttura = st.id_struttura ",
		"                               and now() between rsc.validita_inizio and coalesce(rsc.validita_fine, now()) ",
		"                           	and rsc.data_cancellazione is null ",
		"</if> ",
		"where ", 
		" now() between ctsi.validita_inizio and coalesce(ctsi.validita_fine, now()) ",
		" and ctsi.data_cancellazione is null ",
		" and NOW() BETWEEN st.validita_inizio AND COALESCE(st.validita_fine,NOW()) AND st.data_cancellazione IS NULL ",
		" and UPPER(natura) not in ('EROGATORI','USCA') ",
		"<if test='cfUtente != null'> " , 
		"and rus.cf_utente = #{cfUtente, jdbcType=VARCHAR}  ",
		"</if>",
		"<if test='natura != null'> " , 
		"and UPPER(natura) = #{natura, jdbcType=VARCHAR}  ",
		"</if>",
		"<if test='nomeSti != null'> " , 
		" and (ctsi.sti_nome ilike  concat('%',#{nomeSti, jdbcType = VARCHAR},'%') or st.nome ilike  concat('%',#{nomeSti, jdbcType = VARCHAR},'%') )",
		"</if>",
		"<if test='idStruttura != null'> " , 
		" and upper(ctsi.id_struttura) = upper(#{idStruttura, jdbcType = VARCHAR}) ",
		"</if>",
		"<if test='idEnte != null'> " , 
		" and st.id_ente = #{idEnte, jdbcType = INTEGER} ",
		"</if>",
		"<if test='idTipoUtenza != null'> " , 
		" and ctsi.str_tipo_utenza_id = #{idTipoUtenza, jdbcType = INTEGER} ",
		"</if>",
		"<if test='strCategoriaId != null'> " , 
		" and rsc.str_categoria_id = #{strCategoriaId, jdbcType = INTEGER} ",
		"</if>",

        "<if test='paginazione != null'>",
        "<if test='paginazione.orderBy != null'>ORDER BY ${paginazione.orderBy} </if>  ",
        "<if test='paginazione.limit !=-1'>OFFSET #{paginazione.offset,jdbcType=BIGINT} LIMIT #{paginazione.limit,jdbcType=BIGINT}</if> ",
        "</if>  ",
		"</script>"
	})
	@Results({ @Result(column="sti_id", property="stiId", jdbcType=JdbcType.INTEGER, id=true),
		@Result(column="nome_st", property="stiNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_indirizzo", property="stiIndirizzo", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_telefono", property="stiTelefono", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_email", property="stiEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_mensa_interna_presente", property="stiMensaInternaPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_asmed_mmg", property="stiAsmedMmg", jdbcType=JdbcType.BIT),
		@Result(column="sti_asmed_nommg", property="stiAsmedNommg", jdbcType=JdbcType.BIT),
		@Result(column="id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_id", property="strTipoId", jdbcType=JdbcType.INTEGER),
		@Result(column="str_natura_id", property="strNaturaId", jdbcType=JdbcType.INTEGER),
		@Result(column="str_accreditamento_id", property="strAccreditamentoId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_comune_istat", property="stiComuneIstat", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_pec", property="stiPec", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_presente", property="stiDirStrPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_dir_str_nome", property="stiDirStrNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_tel_reperibilita", property="stiDirStrTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_presente", property="stiDirSanitPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_dir_sanit_nome", property="stiDirSanitNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_tel_reperibilita", property="stiDirSanitTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_presente", property="stiCoordInfPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_coord_inf_nome", property="stiCoordInfNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_tel_reperibilita", property="stiCoordInfTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="validita_inizio", property="validitaInizio", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="validita_fine", property="validitaFine", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="utente_operazione", property="utenteOperazione", jdbcType=JdbcType.VARCHAR),
		@Result(column="data_creazione", property="dataCreazione", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="data_modifica", property="dataModifica", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="data_cancellazione", property="dataCancellazione", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="sti_email2", property="stiEmail2", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_email", property="stiDirStrEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_email", property="stiDirSanitEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_email", property="stiCoordInfEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_asmed_mista", property="stiAsmedMista", jdbcType=JdbcType.BIT),
		@Result(column="sti_pers_inf_notturno", property="stiPersInfNotturno", jdbcType=JdbcType.BIT),
		@Result(column="assmed_id", property="assmedId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_atto_autorizzativo", property="stiAttoAutorizzativo", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_titolare_autorizzazione", property="stiTitolareAutorizzazione", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_utenza_id", property="strTipoUtenzaId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_escludi_struttura", property="stiEscludiStruttura", jdbcType=JdbcType.BIT),
		@Result(column="str_tipo_utenza_desc", property="tipoUtenzaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="nome_ente", property="nomeEnte", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_natura_desc", property="naturaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_desc", property="tipoStrutturaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="nome_comune", property="comune", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_accreditamento_cod", property="accreditamentoCod", jdbcType=JdbcType.VARCHAR),
        @Result(column = "full_count", property = "fullCount", jdbcType = JdbcType.INTEGER),
        @Result(column = "id_ente", property = "idEnte", jdbcType = JdbcType.INTEGER),
        @Result(column="sti_adesione_dgr10", property="stiAdesioneDgr10", jdbcType=JdbcType.BIT),
        @Result(column="sigla_prov", property="siglaProv", jdbcType=JdbcType.VARCHAR),
        @Result(column="sti_abilitato_sollievo", property="stiAbilitatoSollievo", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_dim_prot", property="stiAbilitatoDimProt", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_cavs", property="stiAbilitatoCavs", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_lungodeg", property="stiAbilitatoLungodeg", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_hospice", property="stiAbilitatoHospice", jdbcType=JdbcType.BIT),
        @Result(column="adesione_buono_welfare", property="adesioneBuonoWelfare", jdbcType=JdbcType.BIT)
	})
	List<StrutturaInfoExt> selectStrutturaInfoByFilter(@Param("cfUtente") String cfUtente,
			@Param("natura") String natura,
			@Param("idStruttura") String idStruttura,
			@Param("nomeSti") String nomeSti,
			@Param("idEnte") Integer idEnte,
			@Param("idTipoUtenza") Integer idTipoUtenza,
			@Param("strCategoriaId") Integer strCategoriaId,
			@Param("paginazione") Paginazione paginazione
			);
	
	@Select({		
		"select distinct  st.id_struttura, ",
		" case when COALESCE(st.nome, '')  !='' ",
	    "  	 then  st.nome ",
	    "    else ctsi.sti_nome ",
	    "end nome_st, ",
		"ctsi.sti_id, ctsi.sti_nome, ctsi.sti_indirizzo, ctsi.sti_telefono, ctsi.sti_email, ctsi.sti_mensa_interna_presente, ",
		"ctsi.sti_asmed_mmg, ctsi.sti_asmed_nommg,  ctsi.str_tipo_id, ctsi.str_natura_id, ctsi.str_accreditamento_id, ",
		"ctsi.sti_comune_istat, ctsi.sti_pec, ctsi.sti_dir_str_presente, ctsi.sti_dir_str_nome, ctsi.sti_dir_str_tel_reperibilita, ",
		"ctsi.sti_dir_sanit_presente, ctsi.sti_dir_sanit_nome, ctsi.sti_dir_sanit_tel_reperibilita, ",
		"ctsi.sti_coord_inf_presente, ctsi.sti_coord_inf_nome, ctsi.sti_coord_inf_tel_reperibilita, ",
		"ctsi.validita_inizio, ctsi.validita_fine, ctsi.utente_operazione, ctsi.data_creazione, ctsi.data_modifica, ",
		"ctsi.data_cancellazione, ctsi.sti_email2, ctsi.sti_dir_str_email, ctsi.sti_dir_sanit_email, ctsi.sti_coord_inf_email, ",
		"ctsi.sti_asmed_mista, ctsi.sti_pers_inf_notturno, ctsi.assmed_id, ctsi.sti_atto_autorizzativo, ctsi.sti_titolare_autorizzazione, ",
		"ctsi.str_tipo_utenza_id, ctsi.sti_escludi_struttura, str_tipo_utenza_desc, e.nome as nome_ente, sn.str_natura_desc, ts.str_tipo_desc, nome_comune, ",
        "str_accreditamento_cod, str_accreditamento_desc, ",
        "ctsi.sti_adesione_dgr10, ctsi.sti_abilitato_sollievo, ctsi.sti_abilitato_dim_prot, ctsi.sti_abilitato_cavs, ",
        "ctsi.sti_abilitato_lungodeg, ctsi.sti_abilitato_hospice ",
		"from struttura st  " ,
		"left join covidrsa_t_struttura_info ctsi  on ctsi.id_struttura = st.id_struttura " ,
		"                           and now() between ctsi.validita_inizio and coalesce(ctsi.validita_fine, now()) ",
		"                           and ctsi.data_cancellazione is null ",
		"left join ente e on st.id_ente= e.id_ente " ,
		"left join covidrsa_d_tipo_utenza tu on  tu.str_tipo_utenza_id= ctsi.str_tipo_utenza_id ",
		"left join covidrsa_d_struttura_natura sn on  sn.str_natura_id= ctsi.str_natura_id ",
		"left join r_utente_struttura rus on rus.id_struttura = st.id_struttura " ,
		" left join covidrsa_d_struttura_tipo ts on ts.str_tipo_id = ctsi.str_tipo_id ",
		" left join comuni c on c.istat_comune = ctsi.sti_comune_istat ",
		" left join covidrsa_d_struttura_accreditamento acc on acc.str_accreditamento_id = ctsi.str_accreditamento_id ",
		"where st.id_struttura = #{idStruttura,jdbcType=VARCHAR}"
		
	})
	@Results({ @Result(column="sti_id", property="stiId", jdbcType=JdbcType.INTEGER, id=true),
		@Result(column="nome_st", property="stiNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_indirizzo", property="stiIndirizzo", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_telefono", property="stiTelefono", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_email", property="stiEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_mensa_interna_presente", property="stiMensaInternaPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_asmed_mmg", property="stiAsmedMmg", jdbcType=JdbcType.BIT),
		@Result(column="sti_asmed_nommg", property="stiAsmedNommg", jdbcType=JdbcType.BIT),
		@Result(column="id_struttura", property="idStruttura", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_id", property="strTipoId", jdbcType=JdbcType.INTEGER),
		@Result(column="str_natura_id", property="strNaturaId", jdbcType=JdbcType.INTEGER),
		@Result(column="str_accreditamento_id", property="strAccreditamentoId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_comune_istat", property="stiComuneIstat", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_pec", property="stiPec", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_presente", property="stiDirStrPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_dir_str_nome", property="stiDirStrNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_tel_reperibilita", property="stiDirStrTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_presente", property="stiDirSanitPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_dir_sanit_nome", property="stiDirSanitNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_tel_reperibilita", property="stiDirSanitTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_presente", property="stiCoordInfPresente", jdbcType=JdbcType.BIT),
		@Result(column="sti_coord_inf_nome", property="stiCoordInfNome", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_tel_reperibilita", property="stiCoordInfTelReperibilita", jdbcType=JdbcType.VARCHAR),
		@Result(column="validita_inizio", property="validitaInizio", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="validita_fine", property="validitaFine", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="utente_operazione", property="utenteOperazione", jdbcType=JdbcType.VARCHAR),
		@Result(column="data_creazione", property="dataCreazione", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="data_modifica", property="dataModifica", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="data_cancellazione", property="dataCancellazione", jdbcType=JdbcType.TIMESTAMP),
		@Result(column="sti_email2", property="stiEmail2", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_str_email", property="stiDirStrEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_dir_sanit_email", property="stiDirSanitEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_coord_inf_email", property="stiCoordInfEmail", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_asmed_mista", property="stiAsmedMista", jdbcType=JdbcType.BIT),
		@Result(column="sti_pers_inf_notturno", property="stiPersInfNotturno", jdbcType=JdbcType.BIT),
		@Result(column="assmed_id", property="assmedId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_atto_autorizzativo", property="stiAttoAutorizzativo", jdbcType=JdbcType.VARCHAR),
		@Result(column="sti_titolare_autorizzazione", property="stiTitolareAutorizzazione", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_utenza_id", property="strTipoUtenzaId", jdbcType=JdbcType.INTEGER),
		@Result(column="sti_escludi_struttura", property="stiEscludiStruttura", jdbcType=JdbcType.BIT),
		@Result(column="str_tipo_utenza_desc", property="tipoUtenzaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="nome_ente", property="nomeEnte", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_natura_desc", property="naturaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_tipo_desc", property="tipoStrutturaDesc", jdbcType=JdbcType.VARCHAR),
		@Result(column="nome_comune", property="comune", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_accreditamento_cod", property="accreditamentoCod", jdbcType=JdbcType.VARCHAR),
		@Result(column="str_accreditamento_desc", property="accreditamentoDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="sti_adesione_dgr10", property="stiAdesioneDgr10", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_sollievo", property="stiAbilitatoSollievo", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_dim_prot", property="stiAbilitatoDimProt", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_cavs", property="stiAbilitatoCavs", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_lungodeg", property="stiAbilitatoLungodeg", jdbcType=JdbcType.BIT),
        @Result(column="sti_abilitato_hospice", property="stiAbilitatoHospice", jdbcType=JdbcType.BIT)
	})
	StrutturaInfoExt selectDettaglioStrutturaInfo(String idStruttura);


}
